Spark::SpResourcePath Class Reference
#include <SpResourcePath.h>
Detailed Description
Resource utility class for querying a file system and loading datafiles.
Definition at line 41 of file SpResourcePath.h.
Public Types
typedef stat FileStat
Type Definitions:.
Public Member Functions
SpString & filepath ()
Access Methods:.
const SpString & filepath () const
SpString & pathname ()
const SpString & pathname () const
SpStringArray & searchpath ()
const SpStringArray & searchpath () const
void addPath (const SpString &rkPathname)
Attributes:.
SpString getPath (const SpString &rkFilename)
SpString getFile (const SpString &rkFilename)
char * loadTextFile (const char *acFilename)
File Methods:.
SpString loadTextFile (const SpString &rkFilename)
FILE * loadDataFile (const SpString &rkFilename, const char *acMode=`rb`)
int getFileStats (const SpString &rkFilename, FileStat *pkStat)
Member Typedef Documentation
typedef struct stat Spark::SpResourcePath::FileStat
Type Definitions:.
Definition at line 50 of file SpResourcePath.h.
Referenced by getFileStats(), and loadTextFile().
Member Function Documentation
void Spark::SpResourcePath::addPath (const SpString & rkPathname) [inline]
Attributes:.
Definition at line 77 of file SpResourcePath.h.
const SpString& Spark::SpResourcePath::filepath () const [inline]
Definition at line 59 of file SpResourcePath.h.
SpString& Spark::SpResourcePath::filepath () [inline]
Access Methods:.
Definition at line 56 of file SpResourcePath.h.
SpString SpResourcePath::getFile (const SpString & rkFilename)
Definition at line 86 of file SpResourcePath.cpp.
References Spark::SpString::SizeType.
int SpResourcePath::getFileStats (const SpString & rkFilename, FileStat * pkStat)
Definition at line 208 of file SpResourcePath.cpp.
References FileStat.
Referenced by loadTextFile().
SpString SpResourcePath::getPath (const SpString & rkFilename)
Definition at line 16 of file SpResourcePath.cpp.
References Spark::SpString::SizeType.
FILE * SpResourcePath::loadDataFile (const SpString & rkFilename, const char * acMode = `rb`)
Definition at line 135 of file SpResourcePath.cpp.
Referenced by loadTextFile().
SpString SpResourcePath::loadTextFile (const SpString & rkFilename)
Definition at line 193 of file SpResourcePath.cpp.
References loadTextFile().
char * SpResourcePath::loadTextFile (const char * acFilename)
File Methods:.
Definition at line 160 of file SpResourcePath.cpp.
References FileStat, getFileStats(), and loadDataFile().
Referenced by Spark::SpGlslManager::loadFragmentProgramFromFile(), loadTextFile(), and Spark::SpGlslManager::loadVertexProgramFromFile().
const SpString& Spark::SpResourcePath::pathname () const [inline]
Definition at line 65 of file SpResourcePath.h.
SpString& Spark::SpResourcePath::pathname () [inline]
Definition at line 62 of file SpResourcePath.h.
const SpStringArray& Spark::SpResourcePath::searchpath () const [inline]
Definition at line 71 of file SpResourcePath.h.
References Spark::SpStringArray.
SpStringArray& Spark::SpResourcePath::searchpath () [inline]
Definition at line 68 of file SpResourcePath.h.
References Spark::SpStringArray.
The documentation for this class was generated from the following files:
SpResourcePath.h
SpResourcePath.cpp