Spark::SpTimer Class Reference
#include <SpTimer.h>
Detailed Description
Basic Timer for profiling and retrieving performance/time info.
Definition at line 32 of file SpTimer.h.
Public Types
enum TimerState { TS_OFF,
TS_ON,
TS_HOLD,
TS_COUNT
 }
Typedefs:.
Public Member Functions
SpTimer ()
Construction:.
~SpTimer ()
void start ()
Operations:.
void stop ()
void suspend ()
void resume ()
void reset ()
void count ()
float elapsedTime ()
unsigned int elapsedCount ()
unsigned int elapsedHours ()
unsigned int elapsedMinutes ()
unsigned int elapsedSeconds ()
unsigned int elapsedMilliseconds ()
unsigned int seconds ()
unsigned int milliseconds ()
Member Enumeration Documentation
enum Spark::SpTimer::TimerState
Typedefs:.
Enumeration values:
TS_OFF
TS_ON
TS_HOLD
TS_COUNT
Definition at line 38 of file SpTimer.h.
Constructor & Destructor Documentation
SpTimer::SpTimer ()
Construction:.
Definition at line 42 of file SpTimer.cpp.
References reset().
Spark::SpTimer::~SpTimer () [inline]
Definition at line 119 of file SpTimer.h.
Member Function Documentation
void Spark::SpTimer::count () [inline]
Definition at line 170 of file SpTimer.h.
unsigned int Spark::SpTimer::elapsedCount () [inline]
Definition at line 243 of file SpTimer.h.
Referenced by Spark::SpWindow::onIdle().
unsigned int Spark::SpTimer::elapsedHours () [inline]
Definition at line 192 of file SpTimer.h.
unsigned int Spark::SpTimer::elapsedMilliseconds () [inline]
Definition at line 222 of file SpTimer.h.
unsigned int Spark::SpTimer::elapsedMinutes () [inline]
Definition at line 197 of file SpTimer.h.
unsigned int Spark::SpTimer::elapsedSeconds () [inline]
Definition at line 202 of file SpTimer.h.
Referenced by Spark::SpWindow::drawFrameRate().
float Spark::SpTimer::elapsedTime () [inline]
Definition at line 175 of file SpTimer.h.
unsigned int Spark::SpTimer::milliseconds () [inline]
Definition at line 253 of file SpTimer.h.
void Spark::SpTimer::reset () [inline]
Definition at line 161 of file SpTimer.h.
Referenced by SpTimer().
void Spark::SpTimer::resume () [inline]
Definition at line 146 of file SpTimer.h.
unsigned int Spark::SpTimer::seconds () [inline]
Definition at line 248 of file SpTimer.h.
void Spark::SpTimer::start () [inline]
Operations:.
Definition at line 124 of file SpTimer.h.
void Spark::SpTimer::stop () [inline]
Definition at line 131 of file SpTimer.h.
void Spark::SpTimer::suspend () [inline]
Definition at line 137 of file SpTimer.h.
The documentation for this class was generated from the following files:
SpTimer.h
SpTimer.cpp