Spark::SpWindow Class Reference
#include <SpWindow.h>
Detailed Description
Abstract base class for a graphical display window.
Definition at line 37 of file SpWindow.h.
Public Member Functions
virtual ~SpWindow ()
virtual bool onStartup ()
virtual bool onInitialize ()
virtual void onTerminate ()
virtual void onMove (int iX, int iY)
virtual void onReshape (int iWidth, int iHeight)
virtual void onUpdate (int iValue)
virtual void onDisplay ()
virtual void onKeyDown (unsigned char ucKey, int iX, int iY)
virtual void onKeyUp (unsigned char ucKey, int iX, int iY)
virtual void onSpecialKeyDown (int iKey, int iX, int iY)
virtual void onSpecialKeyUp (int iKey, int iX, int iY)
virtual void onPassiveMotion (int iX, int iY)
virtual void onMouseMotion (int iX, int iY, unsigned int uiModifiers)
virtual void onMouseClick (int iButton, int iState, int iX, int iY, unsigned int uiModifiers)
virtual void onIdle ()
void drawImage (const unsigned char *aucBuffer, unsigned int uiPosX, unsigned int uiPosY, unsigned int uiWidth, unsigned int uiHeight, bool bAlpha)
void drawImage (const float *afBuffer, unsigned int uiPosX, unsigned int uiPosY, unsigned int uiWidth, unsigned int uiHeight, bool bAlpha)
void drawString (const char *pcString, int iX, int iY, const SpColor4f &rkColor)
void drawFrameRate (int iX, int iY, const SpColor4f &rkColor)
virtual void postRedisplay ()
virtual void swapBuffers ()
void updateClicks ()
void makeCurrent ()
char * title ()
unsigned int x ()
unsigned int y ()
unsigned int width ()
unsigned int height ()
const SpColor4f & bg ()
SpTimer & timer ()
void setWindowId (int iSpWindowID)
int id ()
Static Public Member Functions
SpWindow * current ()
Static Public Attributes
const int KEY_ESCAPE = 0x1B
const int KEY_LEFT_ARROW = GLUT_KEY_LEFT
const int KEY_RIGHT_ARROW = GLUT_KEY_RIGHT
const int KEY_UP_ARROW = GLUT_KEY_UP
const int KEY_DOWN_ARROW = GLUT_KEY_DOWN
const int KEY_HOME = GLUT_KEY_HOME
const int KEY_END = GLUT_KEY_END
const int KEY_PAGE_UP = GLUT_KEY_PAGE_UP
const int KEY_PAGE_DOWN = GLUT_KEY_PAGE_DOWN
const int KEY_INSERT = GLUT_KEY_INSERT
const int KEY_DELETE = 0x2E
const int KEY_F1 = GLUT_KEY_F1
const int KEY_F2 = GLUT_KEY_F2
const int KEY_F3 = GLUT_KEY_F3
const int KEY_F4 = GLUT_KEY_F4
const int KEY_F5 = GLUT_KEY_F5
const int KEY_F6 = GLUT_KEY_F6
const int KEY_F7 = GLUT_KEY_F7
const int KEY_F8 = GLUT_KEY_F8
const int KEY_F9 = GLUT_KEY_F9
const int KEY_F10 = GLUT_KEY_F10
const int KEY_F11 = GLUT_KEY_F11
const int KEY_F12 = GLUT_KEY_F12
const int KEY_SHIFT = GLUT_ACTIVE_SHIFT
const int KEY_CONTROL = GLUT_ACTIVE_CTRL
const int KEY_ALT = GLUT_ACTIVE_ALT
const int KEY_COMMAND = 0
const int MOUSE_LEFT_BUTTON = GLUT_LEFT_BUTTON
const int MOUSE_MIDDLE_BUTTON = GLUT_MIDDLE_BUTTON
const int MOUSE_RIGHT_BUTTON = GLUT_RIGHT_BUTTON
const int MOUSE_UP = GLUT_UP
const int MOUSE_DOWN = GLUT_DOWN
const int MOD_LBUTTON
const int MOD_MBUTTON
const int MOD_RBUTTON
Protected Member Functions
SpWindow (char *acWindowTitle, int iX, int iY, int iWidth, int iHeight, const SpColor4f &rkBgColor)
Protected Attributes
bool m_bMouseDown
bool m_bLeftMousePressed
bool m_bRightMousePressed
bool m_bMiddleMousePressed
int m_iLastMouseX
int m_iLastMouseY
float m_fFrameRate
int m_iClicks
int m_iTimer
int m_iMaxTimer
char * m_acWindowTitle
int m_iSpWindowID
int m_iX
int m_iY
int m_iWidth
int m_iHeight
SpColor4f m_kBgColor
SpTimer m_kTimer
Static Protected Attributes
SpWindow * ms_pkWindow = NULL
Constructor & Destructor Documentation
SpWindow::~SpWindow () [virtual]
Definition at line 25 of file SpWindow.cpp.
References ms_pkWindow, and onTerminate().
SpWindow::SpWindow (char * acWindowTitle, int iX, int iY, int iWidth, int iHeight, const SpColor4f & rkBgColor) [protected]
Definition at line 9 of file SpWindow.cpp.
References m_acWindowTitle, m_iClicks, m_iHeight, m_iMaxTimer, m_iTimer, m_iWidth, m_iX, m_iY, m_kBgColor, ms_pkWindow, and Spark::SpColor4f.
Member Function Documentation
const SpColor4f & Spark::SpWindow::bg () [inline]
Definition at line 235 of file SpWindow.h.
SpWindow * Spark::SpWindow::current () [inline, static]
Definition at line 205 of file SpWindow.h.
Referenced by main().
void SpWindow::drawFrameRate (int iX, int iY, const SpColor4f & rkColor)
Definition at line 132 of file SpWindow.cpp.
References drawString(), Spark::SpTimer::elapsedSeconds(), m_fFrameRate, m_iClicks, m_iMaxTimer, m_iTimer, m_kTimer, and Spark::SpColor4f.
void SpWindow::drawImage (const float * afBuffer, unsigned int uiPosX, unsigned int uiPosY, unsigned int uiWidth, unsigned int uiHeight, bool bAlpha)
Definition at line 210 of file SpGlutWindow.cpp.
References m_iHeight, and m_iWidth.
void SpWindow::drawImage (const unsigned char * aucBuffer, unsigned int uiPosX, unsigned int uiPosY, unsigned int uiWidth, unsigned int uiHeight, bool bAlpha)
Definition at line 148 of file SpGlutWindow.cpp.
References m_iHeight, and m_iWidth.
void SpWindow::drawString (const char * pcString, int iX, int iY, const SpColor4f & rkColor)
Definition at line 132 of file SpGlutWindow.cpp.
References Spark::SpTuple4< Real >::a(), Spark::SpTuple4< Real >::b(), Spark::SpTuple4< Real >::g(), Spark::SpTuple4< Real >::r(), and Spark::SpColor4f.
Referenced by drawFrameRate().
unsigned int Spark::SpWindow::height () [inline]
Definition at line 230 of file SpWindow.h.
Referenced by main().
int Spark::SpWindow::id () [inline]
Definition at line 245 of file SpWindow.h.
Referenced by main().
void SpWindow::makeCurrent ()
Definition at line 116 of file SpGlutWindow.cpp.
References ms_pkWindow.
void SpWindow::onDisplay () [virtual]
Definition at line 54 of file SpWindow.cpp.
void SpWindow::onIdle () [virtual]
Definition at line 59 of file SpWindow.cpp.
References Spark::SpTimer::elapsedCount(), m_kTimer, onUpdate(), and postRedisplay().
bool SpWindow::onInitialize () [virtual]
Definition at line 37 of file SpWindow.cpp.
Referenced by main().
void SpWindow::onKeyDown (unsigned char ucKey, int iX, int iY) [virtual]
Definition at line 65 of file SpWindow.cpp.
References KEY_ESCAPE, and onTerminate().
void SpWindow::onKeyUp (unsigned char ucKey, int iX, int iY) [virtual]
Definition at line 72 of file SpWindow.cpp.
void SpWindow::onMouseClick (int iButton, int iState, int iX, int iY, unsigned int uiModifiers) [virtual]
Definition at line 87 of file SpWindow.cpp.
References m_bLeftMousePressed, m_bMiddleMousePressed, m_bMouseDown, m_bRightMousePressed, m_iLastMouseX, and m_iLastMouseY.
void SpWindow::onMouseMotion (int iX, int iY, unsigned int uiModifiers) [virtual]
Definition at line 115 of file SpWindow.cpp.
void SpWindow::onMove (int iX, int iY) [virtual]
Definition at line 42 of file SpWindow.cpp.
References m_iX, and m_iY.
void SpWindow::onPassiveMotion (int iX, int iY) [virtual]
Definition at line 120 of file SpWindow.cpp.
void SpWindow::onReshape (int iWidth, int iHeight) [virtual]
Definition at line 48 of file SpWindow.cpp.
References m_iHeight, and m_iWidth.
void SpWindow::onSpecialKeyDown (int iKey, int iX, int iY) [virtual]
Definition at line 77 of file SpWindow.cpp.
void SpWindow::onSpecialKeyUp (int iKey, int iX, int iY) [virtual]
Definition at line 82 of file SpWindow.cpp.
bool SpWindow::onStartup () [virtual]
Definition at line 32 of file SpWindow.cpp.
Referenced by main().
void SpWindow::onTerminate () [virtual]
Definition at line 102 of file SpGlutWindow.cpp.
Referenced by onKeyDown(), and ~SpWindow().
void SpWindow::onUpdate (int iValue) [virtual]
Definition at line 107 of file SpGlutWindow.cpp.
References postRedisplay().
Referenced by onIdle().
void SpWindow::postRedisplay () [virtual]
Definition at line 122 of file SpGlutWindow.cpp.
Referenced by onIdle(), and onUpdate().
void Spark::SpWindow::setWindowId (int iSpWindowID) [inline]
Definition at line 240 of file SpWindow.h.
Referenced by main().
void SpWindow::swapBuffers () [virtual]
Definition at line 127 of file SpGlutWindow.cpp.
SpTimer & Spark::SpWindow::timer () [inline]
Definition at line 250 of file SpWindow.h.
char * Spark::SpWindow::title () [inline]
Definition at line 210 of file SpWindow.h.
Referenced by main().
void SpWindow::updateClicks ()
Definition at line 125 of file SpWindow.cpp.
References m_iClicks.
unsigned int Spark::SpWindow::width () [inline]
Definition at line 225 of file SpWindow.h.
Referenced by main().
unsigned int Spark::SpWindow::x () [inline]
Definition at line 215 of file SpWindow.h.
unsigned int Spark::SpWindow::y () [inline]
Definition at line 220 of file SpWindow.h.
Member Data Documentation
const int SpWindow::KEY_ALT = GLUT_ACTIVE_ALT [static]
Definition at line 59 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_COMMAND = 0 [static]
Definition at line 60 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_CONTROL = GLUT_ACTIVE_CTRL [static]
Definition at line 58 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_DELETE = 0x2E [static]
Definition at line 41 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_DOWN_ARROW = GLUT_KEY_DOWN [static]
Definition at line 35 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_END = GLUT_KEY_END [static]
Definition at line 37 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_ESCAPE = 0x1B [static]
Definition at line 31 of file SpGlutKeyBindings.h.
Referenced by onKeyDown().
const int SpWindow::KEY_F1 = GLUT_KEY_F1 [static]
Definition at line 42 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F10 = GLUT_KEY_F10 [static]
Definition at line 51 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F11 = GLUT_KEY_F11 [static]
Definition at line 52 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F12 = GLUT_KEY_F12 [static]
Definition at line 53 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F2 = GLUT_KEY_F2 [static]
Definition at line 43 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F3 = GLUT_KEY_F3 [static]
Definition at line 44 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F4 = GLUT_KEY_F4 [static]
Definition at line 45 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F5 = GLUT_KEY_F5 [static]
Definition at line 46 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F6 = GLUT_KEY_F6 [static]
Definition at line 47 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F7 = GLUT_KEY_F7 [static]
Definition at line 48 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F8 = GLUT_KEY_F8 [static]
Definition at line 49 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_F9 = GLUT_KEY_F9 [static]
Definition at line 50 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_HOME = GLUT_KEY_HOME [static]
Definition at line 36 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_INSERT = GLUT_KEY_INSERT [static]
Definition at line 40 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_LEFT_ARROW = GLUT_KEY_LEFT [static]
Definition at line 32 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_PAGE_DOWN = GLUT_KEY_PAGE_DOWN [static]
Definition at line 39 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_PAGE_UP = GLUT_KEY_PAGE_UP [static]
Definition at line 38 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_RIGHT_ARROW = GLUT_KEY_RIGHT [static]
Definition at line 33 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_SHIFT = GLUT_ACTIVE_SHIFT [static]
Definition at line 57 of file SpGlutKeyBindings.h.
const int SpWindow::KEY_UP_ARROW = GLUT_KEY_UP [static]
Definition at line 34 of file SpGlutKeyBindings.h.
char* Spark::SpWindow::m_acWindowTitle [protected]
Definition at line 194 of file SpWindow.h.
Referenced by SpWindow().
bool Spark::SpWindow::m_bLeftMousePressed [protected]
Definition at line 180 of file SpWindow.h.
Referenced by onMouseClick().
bool Spark::SpWindow::m_bMiddleMousePressed [protected]
Definition at line 182 of file SpWindow.h.
Referenced by onMouseClick().
bool Spark::SpWindow::m_bMouseDown [protected]
Definition at line 179 of file SpWindow.h.
Referenced by onMouseClick().
bool Spark::SpWindow::m_bRightMousePressed [protected]
Definition at line 181 of file SpWindow.h.
Referenced by onMouseClick().
float Spark::SpWindow::m_fFrameRate [protected]
Definition at line 187 of file SpWindow.h.
Referenced by drawFrameRate().
int Spark::SpWindow::m_iClicks [protected]
Definition at line 188 of file SpWindow.h.
Referenced by drawFrameRate(), SpWindow(), and updateClicks().
int Spark::SpWindow::m_iHeight [protected]
Definition at line 197 of file SpWindow.h.
Referenced by drawImage(), onReshape(), and SpWindow().
int Spark::SpWindow::m_iLastMouseX [protected]
Definition at line 183 of file SpWindow.h.
Referenced by onMouseClick().
int Spark::SpWindow::m_iLastMouseY [protected]
Definition at line 184 of file SpWindow.h.
Referenced by onMouseClick().
int Spark::SpWindow::m_iMaxTimer [protected]
Definition at line 190 of file SpWindow.h.
Referenced by drawFrameRate(), and SpWindow().
int Spark::SpWindow::m_iSpWindowID [protected]
Definition at line 195 of file SpWindow.h.
int Spark::SpWindow::m_iTimer [protected]
Definition at line 189 of file SpWindow.h.
Referenced by drawFrameRate(), and SpWindow().
int Spark::SpWindow::m_iWidth [protected]
Definition at line 197 of file SpWindow.h.
Referenced by drawImage(), onReshape(), and SpWindow().
int Spark::SpWindow::m_iX [protected]
Definition at line 196 of file SpWindow.h.
Referenced by onMove(), and SpWindow().
int Spark::SpWindow::m_iY [protected]
Definition at line 196 of file SpWindow.h.
Referenced by onMove(), and SpWindow().
SpColor4f Spark::SpWindow::m_kBgColor [protected]
Definition at line 198 of file SpWindow.h.
Referenced by SpWindow().
SpTimer Spark::SpWindow::m_kTimer [protected]
Definition at line 199 of file SpWindow.h.
Referenced by drawFrameRate(), and onIdle().
const int Spark::SpWindow::MOD_LBUTTON [static]
Definition at line 86 of file SpWindow.h.
const int Spark::SpWindow::MOD_MBUTTON [static]
Definition at line 87 of file SpWindow.h.
const int Spark::SpWindow::MOD_RBUTTON [static]
Definition at line 88 of file SpWindow.h.
const int SpWindow::MOUSE_DOWN = GLUT_DOWN [static]
Definition at line 68 of file SpGlutKeyBindings.h.
const int SpWindow::MOUSE_LEFT_BUTTON = GLUT_LEFT_BUTTON [static]
Definition at line 64 of file SpGlutKeyBindings.h.
const int SpWindow::MOUSE_MIDDLE_BUTTON = GLUT_MIDDLE_BUTTON [static]
Definition at line 65 of file SpGlutKeyBindings.h.
const int SpWindow::MOUSE_RIGHT_BUTTON = GLUT_RIGHT_BUTTON [static]
Definition at line 66 of file SpGlutKeyBindings.h.
const int SpWindow::MOUSE_UP = GLUT_UP [static]
Definition at line 67 of file SpGlutKeyBindings.h.
SpWindow * SpWindow::ms_pkWindow = NULL [static, protected]
Definition at line 6 of file SpWindow.cpp.
Referenced by makeCurrent(), SpWindow(), and ~SpWindow().
The documentation for this class was generated from the following files:
SpWindow.h
SpGlutKeyBindings.h
SpGlutWindow.cpp
SpWindow.cpp