Spark::SpGlslManager Class Reference
#include <SpGlslManager.h>
Detailed Description
Static manager class for interfacing with GLSL.
Definition at line 38 of file SpGlslManager.h.
Public Member Functions
~SpGlslManager ()
Construction:.
Static Public Member Functions
bool compile (SpGpuProgram *pkSpGpuProgram)
Operations:.
bool bind (SpGpuProgram *pkSpGpuProgram)
bool enable (SpGpuProgram *pkSpGpuProgram)
bool disable (SpGpuProgram *pkSpGpuProgram)
bool release (SpGpuProgram *pkSpGpuProgram)
bool isSupported (const SpGpuProgram *pkSpGpuProgram)
SpGpuProgram * loadFromFile (const char *acFilename, SpGpuProgram::Type)
SpGlslVertexProgram * loadVertexProgramFromFile (const char *acFilename)
SpGlslFragmentProgram * loadFragmentProgramFromFile (const char *acFilename)
void printInfoLog (unsigned int uiHandle)
SpResourcePath & searchpath ()
void enableTexturePassThrough (bool bIsRectangle=false)
void enableFragmentPassThrough ()
void enableFragmentPrograms ()
void enableVertexPrograms ()
void disableFragmentPrograms ()
void disableVertexPrograms ()
Static Protected Attributes
SpResourcePath ms_kSpResourcePath
Internal Data:.
SpGpuProgram * ms_apkCurrent [SpGpuProgram::GPU_PROGRAM_COUNT]
Static Data:.
Constructor & Destructor Documentation
SpGlslManager::~SpGlslManager ()
Construction:.
Definition at line 19 of file SpGlslManager.cpp.
References ms_apkCurrent, and release().
Member Function Documentation
bool SpGlslManager::bind (SpGpuProgram * pkSpGpuProgram) [static]
Definition at line 112 of file SpGlslManager.cpp.
References compile(), Spark::SpGpuProgram::getType(), Spark::SpGpuProgram::getUserData(), and ms_apkCurrent.
Referenced by Spark::SpVertexNoiseSb::initialize().
bool SpGlslManager::compile (SpGpuProgram * pkSpGpuProgram) [static]
Operations:.
Definition at line 32 of file SpGlslManager.cpp.
References Spark::SpGpuProgram::getLength(), Spark::SpGpuProgram::getSource(), Spark::SpGpuProgram::getType(), isSupported(), printInfoLog(), and Spark::SpGpuProgram::setUserData().
Referenced by bind(), enable(), Spark::SpVertexNoiseSb::initialize(), and Spark::SpTurbulenceOp::initialize().
bool SpGlslManager::disable (SpGpuProgram * pkSpGpuProgram) [static]
Definition at line 152 of file SpGlslManager.cpp.
Referenced by Spark::SpVertexNoiseSb::disable(), and Spark::SpTurbulenceOp::updateOutputStream().
void SpGlslManager::disableFragmentPrograms () [static]
Definition at line 347 of file SpGlslManager.cpp.
void SpGlslManager::disableVertexPrograms () [static]
Definition at line 352 of file SpGlslManager.cpp.
bool SpGlslManager::enable (SpGpuProgram * pkSpGpuProgram) [static]
Definition at line 132 of file SpGlslManager.cpp.
References compile(), Spark::SpGpuProgram::getType(), Spark::SpGpuProgram::getUserData(), and ms_apkCurrent.
Referenced by Spark::SpVertexNoiseSb::enable(), and Spark::SpTurbulenceOp::updateOutputStream().
void SpGlslManager::enableFragmentPassThrough () [static]
Definition at line 308 of file SpGlslManager.cpp.
void SpGlslManager::enableFragmentPrograms () [static]
Definition at line 337 of file SpGlslManager.cpp.
void SpGlslManager::enableTexturePassThrough (bool bIsRectangle = false) [static]
Definition at line 263 of file SpGlslManager.cpp.
void SpGlslManager::enableVertexPrograms () [static]
Definition at line 342 of file SpGlslManager.cpp.
bool SpGlslManager::isSupported (const SpGpuProgram * pkSpGpuProgram) [static]
Definition at line 176 of file SpGlslManager.cpp.
References Spark::SpGpuProgram::getType().
Referenced by compile().
SpGlslFragmentProgram * SpGlslManager::loadFragmentProgramFromFile (const char * acFilename) [static]
Definition at line 235 of file SpGlslManager.cpp.
References Spark::SpResourcePath::loadTextFile(), and searchpath().
Referenced by Spark::SpTurbulenceOp::initialize(), loadFromFile(), and Spark::SpVertexNoiseSb::SpVertexNoiseSb().
SpGpuProgram * SpGlslManager::loadFromFile (const char * acFilename, SpGpuProgram::Type) [static]
Definition at line 212 of file SpGlslManager.cpp.
References loadFragmentProgramFromFile(), and loadVertexProgramFromFile().
SpGlslVertexProgram * SpGlslManager::loadVertexProgramFromFile (const char * acFilename) [static]
Definition at line 223 of file SpGlslManager.cpp.
References Spark::SpResourcePath::loadTextFile(), and searchpath().
Referenced by Spark::SpTurbulenceOp::initialize(), loadFromFile(), and Spark::SpVertexNoiseSb::SpVertexNoiseSb().
void SpGlslManager::printInfoLog (unsigned int uiHandle) [static]
Definition at line 252 of file SpGlslManager.cpp.
Referenced by compile().
bool SpGlslManager::release (SpGpuProgram * pkSpGpuProgram) [static]
Definition at line 158 of file SpGlslManager.cpp.
References Spark::SpGpuProgram::getUserData(), and Spark::SpGpuProgram::setUserData().
Referenced by Spark::SpVertexNoiseSb::destroy(), and ~SpGlslManager().
SpResourcePath & SpGlslManager::searchpath () [static]
Definition at line 247 of file SpGlslManager.cpp.
References ms_kSpResourcePath.
Referenced by loadFragmentProgramFromFile(), and loadVertexProgramFromFile().
Member Data Documentation
SpGpuProgram * SpGlslManager::ms_apkCurrent [static, protected]
Static Data:.
Definition at line 17 of file SpGlslManager.cpp.
Referenced by bind(), enable(), and ~SpGlslManager().
SpResourcePath SpGlslManager::ms_kSpResourcePath [static, protected]
Internal Data:.
Definition at line 16 of file SpGlslManager.cpp.
Referenced by searchpath().
The documentation for this class was generated from the following files:
SpGlslManager.h
SpGlslManager.cpp