Spark::SpTuple3< Real > Class Template Reference
#include <SpTuple.h>
Detailed Description
template<class Real> class Spark::SpTuple3< Real >
3D tuple data class with support for vector mathematics
Definition at line 141 of file SpTuple.h.
Public Member Functions
SpTuple3 (const SpTuple< 3, Real > &rkV)
Construction.
SpTuple3 (Real fX=0, Real fY=0, Real fZ=0)
Real x () const
Position Coordinate Access:.
Real & x ()
Real y () const
Real & y ()
Real z () const
Real & z ()
Real r () const
Color Component Access:.
Real & r ()
Real g () const
Real & g ()
Real b () const
Real & b ()
Real s () const
Texture Coordinate Access:.
Real & s ()
Real t () const
Real & t ()
Real p () const
Real & p ()
Constructor & Destructor Documentation
template<class Real> Spark::SpTuple3< Real >::SpTuple3 (const SpTuple< 3, Real > & rkV) [inline]
Construction.
Definition at line 147 of file SpTuple.h.
template<class Real> Spark::SpTuple3< Real >::SpTuple3 (Real fX = 0, Real fY = 0, Real fZ = 0) [inline]
Definition at line 150 of file SpTuple.h.
References Spark::SpTuple3< Real >::x(), Spark::SpTuple3< Real >::y(), and Spark::SpTuple3< Real >::z().
Member Function Documentation
template<class Real> Real& Spark::SpTuple3< Real >::b () [inline]
Definition at line 171 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::b () const [inline]
Definition at line 170 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::g () [inline]
Definition at line 169 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::g () const [inline]
Definition at line 168 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::p () [inline]
Definition at line 181 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::p () const [inline]
Definition at line 180 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::r () [inline]
Definition at line 167 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::r () const [inline]
Color Component Access:.
Definition at line 166 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::s () [inline]
Definition at line 177 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::s () const [inline]
Texture Coordinate Access:.
Definition at line 176 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::t () [inline]
Definition at line 179 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::t () const [inline]
Definition at line 178 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple3< Real >::x () [inline]
Definition at line 157 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::x () const [inline]
Position Coordinate Access:.
Definition at line 156 of file SpTuple.h.
Referenced by Spark::SpTuple3< Real >::SpTuple3().
template<class Real> Real& Spark::SpTuple3< Real >::y () [inline]
Definition at line 159 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::y () const [inline]
Definition at line 158 of file SpTuple.h.
Referenced by Spark::SpTuple3< Real >::SpTuple3().
template<class Real> Real& Spark::SpTuple3< Real >::z () [inline]
Definition at line 161 of file SpTuple.h.
template<class Real> Real Spark::SpTuple3< Real >::z () const [inline]
Definition at line 160 of file SpTuple.h.
Referenced by Spark::SpTuple3< Real >::SpTuple3().
The documentation for this class was generated from the following file:
SpTuple.h