Spark::SpVertexNoiseSb Class Reference
#include <SpVertexNoiseSb.h>
Detailed Description
Noise generating stream basis which operates on vertex data.
Definition at line 40 of file SpVertexNoiseSb.h.
Public Member Functions
SpVertexNoiseSb (bool bAbsNoise=false, float fOffsetX=1, float fOffsetY=1, float fOffsetZ=1, float fScaleX=1, float fScaleY=1, float fScaleZ=1, unsigned int uiGridResolution=150, unsigned long iSeed=1234)
Construction:.
virtual ~SpVertexNoiseSb ()
void initialize ()
Operations:.
void destroy ()
void preload ()
void enable ()
void disable ()
virtual void setScale (float fX, float fY, float fZ)
virtual void getScale (float &rfX, float &rfY, float &rfZ) const
virtual void setOffset (float fX, float fY, float fZ)
virtual void getOffset (float &rfX, float &rfY, float &rfZ) const
virtual void setWeight (float fWeight)
virtual float getWeight () const
void setGridResolution (unsigned int uiResolution)
SpGlslVertexProgram * program ()
virtual bool hasChanged ()
Inherited Methods:.
virtual bool sendOutputToBuffer (SpStreamBuffer *pkBuffer, SpCopyToTextureFb *pkCopy)
Protected Attributes
SpGlslVertexProgram * m_pkVertexProgram
Internal Data:.
SpGlslFragmentProgram * m_pkFragmentProgram
int * m_aiP
SpVector4f * m_akPG
bool m_bIsInitialized
bool m_bHasChanged
unsigned long m_ulSeed
SpTexturedGridSg m_kGrid
float m_fOffsetX
float m_fOffsetY
float m_fOffsetZ
float m_fScaleX
float m_fScaleY
float m_fScaleZ
float m_fWeight
Constructor & Destructor Documentation
SpVertexNoiseSb::SpVertexNoiseSb (bool bAbsNoise = false, float fOffsetX = 1, float fOffsetY = 1, float fOffsetZ = 1, float fScaleX = 1, float fScaleY = 1, float fScaleZ = 1, unsigned int uiGridResolution = 150, unsigned long iSeed = 1234)
Construction:.
Definition at line 23 of file SpVertexNoiseSb.cpp.
References Spark::SpGlslManager::loadFragmentProgramFromFile(), Spark::SpGlslManager::loadVertexProgramFromFile(), m_bHasChanged, m_kGrid, m_pkFragmentProgram, m_pkVertexProgram, and Spark::SpTexturedGridSg::setResolution().
SpVertexNoiseSb::~SpVertexNoiseSb () [virtual]
Definition at line 64 of file SpVertexNoiseSb.cpp.
References destroy().
Member Function Documentation
void SpVertexNoiseSb::destroy ()
Definition at line 132 of file SpVertexNoiseSb.cpp.
References m_aiP, m_akPG, m_pkVertexProgram, and Spark::SpGlslManager::release().
Referenced by ~SpVertexNoiseSb().
void SpVertexNoiseSb::disable ()
Definition at line 172 of file SpVertexNoiseSb.cpp.
References Spark::SpGlslManager::disable(), m_pkFragmentProgram, and m_pkVertexProgram.
Referenced by sendOutputToBuffer().
void SpVertexNoiseSb::enable ()
Definition at line 154 of file SpVertexNoiseSb.cpp.
References Spark::SpGlslManager::enable(), initialize(), m_bIsInitialized, m_fWeight, m_pkFragmentProgram, m_pkVertexProgram, and Spark::SpGlslVertexProgram::setParameter1f().
Referenced by sendOutputToBuffer().
virtual void Spark::SpVertexNoiseSb::getOffset (float & rfX, float & rfY, float & rfZ) const [inline, virtual]
Reimplemented from Spark::SpStreamBasis (p.).
Definition at line 87 of file SpVertexNoiseSb.h.
References m_fOffsetX, m_fOffsetY, and m_fOffsetZ.
virtual void Spark::SpVertexNoiseSb::getScale (float & rfX, float & rfY, float & rfZ) const [inline, virtual]
Reimplemented from Spark::SpStreamBasis (p.).
Definition at line 72 of file SpVertexNoiseSb.h.
References m_fScaleX, m_fScaleY, and m_fScaleZ.
virtual float Spark::SpVertexNoiseSb::getWeight () const [inline, virtual]
Definition at line 100 of file SpVertexNoiseSb.h.
References m_fWeight.
bool SpVertexNoiseSb::hasChanged () [virtual]
Inherited Methods:.
Implements Spark::SpStreamBasis (p.).
Definition at line 182 of file SpVertexNoiseSb.cpp.
References m_bHasChanged.
void SpVertexNoiseSb::initialize ()
Operations:.
Definition at line 69 of file SpVertexNoiseSb.cpp.
References Spark::SpGlslManager::bind(), Spark::SpGlslManager::compile(), m_aiP, m_akPG, m_bIsInitialized, m_pkVertexProgram, m_ulSeed, Spark::Normalize(), Spark::RandomSymmetricFloat(), Spark::RandomUInt(), Spark::SeedRandom(), Spark::SpGlslVertexProgram::setParameter4fv(), and Spark::SpVector4f.
Referenced by enable(), and preload().
void SpVertexNoiseSb::preload ()
Definition at line 148 of file SpVertexNoiseSb.cpp.
References initialize(), and m_bIsInitialized.
SpGlslVertexProgram* Spark::SpVertexNoiseSb::program () [inline]
Definition at line 111 of file SpVertexNoiseSb.h.
References m_pkVertexProgram.
bool SpVertexNoiseSb::sendOutputToBuffer (SpStreamBuffer * pkBuffer, SpCopyToTextureFb * pkCopy) [virtual]
Definition at line 187 of file SpVertexNoiseSb.cpp.
References Spark::SpStreamBuffer::disable(), disable(), enable(), Spark::SpStreamBuffer::enable(), Spark::SpStreamBuffer::isDoubleBuffered(), Spark::SpStreamBuffer::isInitialized(), m_bHasChanged, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fScaleX, m_fScaleY, m_fScaleZ, m_kGrid, Spark::SpTexturedGridSg::render(), and Spark::SpCopyToTextureFb::updateOutput().
void Spark::SpVertexNoiseSb::setGridResolution (unsigned int uiResolution) [inline]
Definition at line 105 of file SpVertexNoiseSb.h.
References m_bHasChanged, m_kGrid, and Spark::SpTexturedGridSg::setResolution().
virtual void Spark::SpVertexNoiseSb::setOffset (float fX, float fY, float fZ) [inline, virtual]
Reimplemented from Spark::SpStreamBasis (p.).
Definition at line 79 of file SpVertexNoiseSb.h.
References m_bHasChanged, m_fOffsetX, m_fOffsetY, and m_fOffsetZ.
virtual void Spark::SpVertexNoiseSb::setScale (float fX, float fY, float fZ) [inline, virtual]
Reimplemented from Spark::SpStreamBasis (p.).
Definition at line 64 of file SpVertexNoiseSb.h.
References m_bHasChanged, m_fScaleX, m_fScaleY, and m_fScaleZ.
virtual void Spark::SpVertexNoiseSb::setWeight (float fWeight) [inline, virtual]
Reimplemented from Spark::SpStreamBasis (p.).
Definition at line 94 of file SpVertexNoiseSb.h.
References m_bHasChanged, and m_fWeight.
Member Data Documentation
int* Spark::SpVertexNoiseSb::m_aiP [protected]
Definition at line 130 of file SpVertexNoiseSb.h.
Referenced by destroy(), and initialize().
SpVector4f* Spark::SpVertexNoiseSb::m_akPG [protected]
Definition at line 133 of file SpVertexNoiseSb.h.
Referenced by destroy(), and initialize().
bool Spark::SpVertexNoiseSb::m_bHasChanged [protected]
Definition at line 139 of file SpVertexNoiseSb.h.
Referenced by hasChanged(), sendOutputToBuffer(), setGridResolution(), setOffset(), setScale(), setWeight(), and SpVertexNoiseSb().
bool Spark::SpVertexNoiseSb::m_bIsInitialized [protected]
Definition at line 136 of file SpVertexNoiseSb.h.
Referenced by enable(), initialize(), and preload().
float Spark::SpVertexNoiseSb::m_fOffsetX [protected]
Definition at line 148 of file SpVertexNoiseSb.h.
Referenced by getOffset(), sendOutputToBuffer(), and setOffset().
float Spark::SpVertexNoiseSb::m_fOffsetY [protected]
Definition at line 149 of file SpVertexNoiseSb.h.
Referenced by getOffset(), sendOutputToBuffer(), and setOffset().
float Spark::SpVertexNoiseSb::m_fOffsetZ [protected]
Definition at line 150 of file SpVertexNoiseSb.h.
Referenced by getOffset(), sendOutputToBuffer(), and setOffset().
float Spark::SpVertexNoiseSb::m_fScaleX [protected]
Definition at line 153 of file SpVertexNoiseSb.h.
Referenced by getScale(), sendOutputToBuffer(), and setScale().
float Spark::SpVertexNoiseSb::m_fScaleY [protected]
Definition at line 154 of file SpVertexNoiseSb.h.
Referenced by getScale(), sendOutputToBuffer(), and setScale().
float Spark::SpVertexNoiseSb::m_fScaleZ [protected]
Definition at line 155 of file SpVertexNoiseSb.h.
Referenced by getScale(), sendOutputToBuffer(), and setScale().
float Spark::SpVertexNoiseSb::m_fWeight [protected]
Definition at line 158 of file SpVertexNoiseSb.h.
Referenced by enable(), getWeight(), and setWeight().
SpTexturedGridSg Spark::SpVertexNoiseSb::m_kGrid [protected]
Definition at line 145 of file SpVertexNoiseSb.h.
Referenced by sendOutputToBuffer(), setGridResolution(), and SpVertexNoiseSb().
SpGlslFragmentProgram* Spark::SpVertexNoiseSb::m_pkFragmentProgram [protected]
Definition at line 127 of file SpVertexNoiseSb.h.
Referenced by disable(), enable(), and SpVertexNoiseSb().
SpGlslVertexProgram* Spark::SpVertexNoiseSb::m_pkVertexProgram [protected]
Internal Data:.
Definition at line 124 of file SpVertexNoiseSb.h.
Referenced by destroy(), disable(), enable(), initialize(), program(), and SpVertexNoiseSb().
unsigned long Spark::SpVertexNoiseSb::m_ulSeed [protected]
Definition at line 142 of file SpVertexNoiseSb.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
SpVertexNoiseSb.h
SpVertexNoiseSb.cpp