Spark::SpTuple2< Real > Class Template Reference
#include <SpTuple.h>
Detailed Description
template<class Real> class Spark::SpTuple2< Real >
2D tuple data class with support for vector mathematics
Definition at line 107 of file SpTuple.h.
Public Member Functions
SpTuple2 (const SpTuple< 2, Real > &rkV)
Construction.
SpTuple2 (Real fX=0, Real fY=0)
Real x () const
Position Coordinate Access:.
Real & x ()
Real y () const
Real & y ()
Real s () const
Texture Coordinate Access:.
Real & s ()
Real t () const
Real & t ()
Constructor & Destructor Documentation
template<class Real> Spark::SpTuple2< Real >::SpTuple2 (const SpTuple< 2, Real > & rkV) [inline]
Construction.
Definition at line 113 of file SpTuple.h.
template<class Real> Spark::SpTuple2< Real >::SpTuple2 (Real fX = 0, Real fY = 0) [inline]
Definition at line 116 of file SpTuple.h.
References Spark::SpTuple2< Real >::x(), and Spark::SpTuple2< Real >::y().
Member Function Documentation
template<class Real> Real& Spark::SpTuple2< Real >::s () [inline]
Definition at line 131 of file SpTuple.h.
template<class Real> Real Spark::SpTuple2< Real >::s () const [inline]
Texture Coordinate Access:.
Definition at line 130 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple2< Real >::t () [inline]
Definition at line 133 of file SpTuple.h.
template<class Real> Real Spark::SpTuple2< Real >::t () const [inline]
Definition at line 132 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple2< Real >::x () [inline]
Definition at line 123 of file SpTuple.h.
template<class Real> Real Spark::SpTuple2< Real >::x () const [inline]
Position Coordinate Access:.
Definition at line 122 of file SpTuple.h.
Referenced by Spark::SpTuple2< Real >::SpTuple2().
template<class Real> Real& Spark::SpTuple2< Real >::y () [inline]
Definition at line 125 of file SpTuple.h.
template<class Real> Real Spark::SpTuple2< Real >::y () const [inline]
Definition at line 124 of file SpTuple.h.
Referenced by Spark::SpTuple2< Real >::SpTuple2().
The documentation for this class was generated from the following file:
SpTuple.h