Spark::SpGpuProgram Class Reference
#include <SpGpuProgram.h>
Detailed Description
Abstract base class for a GPU program.
Definition at line 33 of file SpGpuProgram.h.
Public Types
enum Type { GPU_INVALID_PROGRAM,
GPU_GLSL_VERTEX_PROGRAM,
GPU_GLSL_FRAGMENT_PROGRAM,
GPU_PROGRAM_COUNT
 }
Enumerations:.
Public Member Functions
virtual ~SpGpuProgram ()
Construction:.
char * getSource ()
Attributes:.
void setSource (const char *acSpGpuProgram)
unsigned int getLength ()
SpGpuProgram::Type getType () const
void setUserData (const void *pvData, int iSize)
User Data Methods:.
void getUserData (void *pvData, int iSize) const
void setState ()
State Methods:.
void resetState ()
void enableClientState (const char *acName)
void disableClientState (const char *acName)
void destroy ()
virtual bool setParameter1i (const char *acName, int iX)
Parameter Methods:.
virtual bool setParameter2i (const char *acName, int iX, int iY)
virtual bool setParameter3i (const char *acName, int iX, int iY, int iZ)
virtual bool setParameter4i (const char *acName, int iX, int iY, int iZ, int iW)
virtual bool setParameter1iv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter2iv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter3iv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter4iv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter1f (const char *acName, float fX)
virtual bool setParameter2f (const char *acName, float fX, float fY)
virtual bool setParameter3f (const char *acName, float fX, float fY, float fZ)
virtual bool setParameter4f (const char *acName, float fX, float fY, float fZ, float fW)
virtual bool setParameter1fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter4fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter4fv (const char *acName, const float *afValues, int iCount=1)
Protected Member Functions
SpGpuProgram (SpGpuProgram::Type eType=GPU_INVALID_PROGRAM)
Internal Data:.
EnableReferencing ()
Protected Attributes
char * m_acSource
char m_acUserData [8]
unsigned int m_uiLength
SpGpuProgram::Type m_eType
Member Enumeration Documentation
enum Spark::SpGpuProgram::Type
Enumerations:.
Enumeration values:
GPU_INVALID_PROGRAM
GPU_GLSL_VERTEX_PROGRAM
GPU_GLSL_FRAGMENT_PROGRAM
GPU_PROGRAM_COUNT
Definition at line 40 of file SpGpuProgram.h.
Constructor & Destructor Documentation
SpGpuProgram::~SpGpuProgram () [virtual]
Construction:.
Definition at line 16 of file SpGpuProgram.cpp.
References m_acSource.
SpGpuProgram::SpGpuProgram (SpGpuProgram::Type eType = GPU_INVALID_PROGRAM) [protected]
Internal Data:.
Definition at line 8 of file SpGpuProgram.cpp.
References m_acSource, m_acUserData, and m_uiLength.
Member Function Documentation
void Spark::SpGpuProgram::destroy ()
void Spark::SpGpuProgram::disableClientState (const char * acName)
void Spark::SpGpuProgram::enableClientState (const char * acName)
Spark::SpGpuProgram::EnableReferencing () [protected]
unsigned int Spark::SpGpuProgram::getLength () [inline]
Definition at line 129 of file SpGpuProgram.h.
Referenced by Spark::SpGlslManager::compile().
char * Spark::SpGpuProgram::getSource () [inline]
Attributes:.
Definition at line 124 of file SpGpuProgram.h.
References Spark::SpGpuProgramPtr.
Referenced by Spark::SpGlslManager::compile().
SpGpuProgram::Type Spark::SpGpuProgram::getType () const [inline]
Definition at line 134 of file SpGpuProgram.h.
Referenced by Spark::SpGlslManager::bind(), Spark::SpGlslManager::compile(), Spark::SpGlslManager::enable(), and Spark::SpGlslManager::isSupported().
void Spark::SpGpuProgram::getUserData (void * pvData, int iSize) const [inline]
Definition at line 144 of file SpGpuProgram.h.
Referenced by Spark::SpGlslManager::bind(), Spark::SpGlslManager::enable(), Spark::SpGlslVertexProgram::getParameterRegister(), Spark::SpGlslFragmentProgram::getParameterRegister(), and Spark::SpGlslManager::release().
void Spark::SpGpuProgram::resetState ()
bool SpGpuProgram::setMatrixParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 128 of file SpGpuProgram.cpp.
bool SpGpuProgram::setMatrixParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 134 of file SpGpuProgram.cpp.
bool SpGpuProgram::setMatrixParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 140 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter1f (const char * acName, float fX) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 80 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter1fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 104 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter1i (const char * acName, int iX) [virtual]
Parameter Methods:.
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 32 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter1iv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Definition at line 56 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter2f (const char * acName, float fX, float fY) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 86 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 110 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter2i (const char * acName, int iX, int iY) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 38 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter2iv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Definition at line 62 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter3f (const char * acName, float fX, float fY, float fZ) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 92 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 116 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter3i (const char * acName, int iX, int iY, int iZ) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 44 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter3iv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Definition at line 68 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter4f (const char * acName, float fX, float fY, float fZ, float fW) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 98 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 122 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter4i (const char * acName, int iX, int iY, int iZ, int iW) [virtual]
Reimplemented in Spark::SpGlslFragmentProgram (p.), and Spark::SpGlslVertexProgram (p.).
Definition at line 50 of file SpGpuProgram.cpp.
bool SpGpuProgram::setParameter4iv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Definition at line 74 of file SpGpuProgram.cpp.
void SpGpuProgram::setSource (const char * acSpGpuProgram)
Definition at line 21 of file SpGpuProgram.cpp.
References m_acSource, and m_uiLength.
Referenced by Spark::SpGlslFragmentProgram::SpGlslFragmentProgram(), and Spark::SpGlslVertexProgram::SpGlslVertexProgram().
void Spark::SpGpuProgram::setState ()
State Methods:.
void Spark::SpGpuProgram::setUserData (const void * pvData, int iSize) [inline]
User Data Methods:.
Definition at line 139 of file SpGpuProgram.h.
Referenced by Spark::SpGlslManager::compile(), and Spark::SpGlslManager::release().
Member Data Documentation
char* Spark::SpGpuProgram::m_acSource [protected]
Definition at line 111 of file SpGpuProgram.h.
Referenced by setSource(), SpGpuProgram(), and ~SpGpuProgram().
char Spark::SpGpuProgram::m_acUserData[8] [protected]
Definition at line 112 of file SpGpuProgram.h.
Referenced by SpGpuProgram().
SpGpuProgram::Type Spark::SpGpuProgram::m_eType [protected]
Definition at line 116 of file SpGpuProgram.h.
unsigned int Spark::SpGpuProgram::m_uiLength [protected]
Definition at line 114 of file SpGpuProgram.h.
Referenced by setSource(), and SpGpuProgram().
The documentation for this class was generated from the following files:
SpGpuProgram.h
SpGpuProgram.cpp