Spark::SpParameter Class Reference
#include <SpParameter.h>
Detailed Description
Storage class for multiple data types for use with GPU programs.
Definition at line 33 of file SpParameter.h.
Public Types
enum Type {
PT_NONE,
PT_BOOL,
PT_INT,
PT_IVEC2,
PT_IVEC3,
PT_IVEC4,
PT_FLOAT,
PT_VEC2,
PT_VEC3,
PT_VEC4,
PT_MAT2,
PT_MAT3,
PT_MAT4,
PT_MAX_COUNT
 }
Enumerations:.
enum Option { PO_NONE,
PO_COLOR,
PO_MAX_COLOR
 }
Valid SpParameter(p.) Options.
Public Member Functions
SpParameter ()
Construction:.
SpParameter (const char *acName, SpParameter::Type eType, unsigned int uiRegister=0, int iCount=1, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, const float *afData, int iCount, SpParameter::Type eType, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, bool bEnable, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, int iX, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, int iX, int iY, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, int iX, int iY, int iZ, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, float fX, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, float fX, float fY, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const char *acName, float fX, float fY, float fZ, unsigned int uiRegister=0, SpParameter::Option eOption=PO_NONE)
SpParameter (const SpParameter *pkSpParameter)
SpParameter (const SpParameter &rkConst)
virtual ~SpParameter ()
SpParameter & operator= (const SpParameter &rkConst)
Assignment:.
const char * getName () const
Access Methods:.
int getSize () const
int getSize (SpParameter::Type eType) const
int getCount () const
SpParameter::Type getType () const
SpParameter::Option getOption () const
void setOption (SpParameter::Option eOption)
unsigned int getRegister () const
void setRegister (unsigned int uiRegister)
const void * getData () const
void setData (bool bEnable)
void setData (int iX)
void setData (int iX, int iY)
void setData (int iX, int iY, int iZ)
void setData (int iX, int iY, int iZ, int iW)
void setData (float fX)
void setData (float fX, float fY)
void setData (float fX, float fY, float fZ)
void setData (float fX, float fY, float fZ, float fW)
void setData (const float akData[2][2])
void setData (const float akData[3][3])
void setData (const float akData[4][4])
void setData (const void *pvData, int iCount, SpParameter::Type eType)
bool isNamed (const char *acName) const
bool isBoolean () const
bool isInteger () const
bool isFloat () const
bool hasChanged () const
void setChanged (bool bChanged=false)
Protected Member Functions
EnableReferencing ()
Protected Attributes
unsigned int m_uiRegister
Internal Data:.
void * m_pvData
int m_iSize
int m_iCount
SpParameter::Type m_eType
SpParameter::Option m_eOption
char * m_acName
bool m_bHasChanged
Member Enumeration Documentation
enum Spark::SpParameter::Option
Valid SpParameter(p.) Options.
Enumeration values:
PO_NONE
PO_COLOR
PO_MAX_COLOR
Definition at line 59 of file SpParameter.h.
enum Spark::SpParameter::Type
Enumerations:.
Enumeration values:
PT_NONE
PT_BOOL
PT_INT
PT_IVEC2
PT_IVEC3
PT_IVEC4
PT_FLOAT
PT_VEC2
PT_VEC3
PT_VEC4
PT_MAT2
PT_MAT3
PT_MAT4
PT_MAX_COUNT
Definition at line 40 of file SpParameter.h.
Constructor & Destructor Documentation
SpParameter::SpParameter ()
Construction:.
Definition at line 6 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_eType, m_iCount, m_iSize, m_pvData, m_uiRegister, PO_NONE, and PT_NONE.
SpParameter::SpParameter (const char * acName, SpParameter::Type eType, unsigned int uiRegister = 0, int iCount = 1, SpParameter::Option eOption = PO_NONE)
Definition at line 18 of file SpParameter.cpp.
References getSize(), m_acName, m_bHasChanged, m_eOption, m_eType, m_iCount, m_iSize, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, const float * afData, int iCount, SpParameter::Type eType, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 35 of file SpParameter.cpp.
References getSize(), m_acName, m_bHasChanged, m_eOption, m_eType, m_iCount, m_iSize, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, bool bEnable, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 57 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_eType, m_iCount, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, int iX, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 76 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, int iX, int iY, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 93 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, int iX, int iY, int iZ, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 111 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, float fX, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 130 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, float fX, float fY, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 147 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const char * acName, float fX, float fY, float fZ, unsigned int uiRegister = 0, SpParameter::Option eOption = PO_NONE)
Definition at line 165 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_pvData, m_uiRegister, and setData().
SpParameter::SpParameter (const SpParameter * pkSpParameter)
Definition at line 184 of file SpParameter.cpp.
References m_acName, and m_pvData.
SpParameter::SpParameter (const SpParameter & rkConst)
Definition at line 194 of file SpParameter.cpp.
References m_acName, and m_pvData.
SpParameter::~SpParameter () [virtual]
Definition at line 225 of file SpParameter.cpp.
References m_acName, m_iCount, and m_pvData.
Member Function Documentation
Spark::SpParameter::EnableReferencing () [protected]
int Spark::SpParameter::getCount () const [inline]
Definition at line 288 of file SpParameter.h.
const void * Spark::SpParameter::getData () const [inline]
Definition at line 231 of file SpParameter.h.
const char * Spark::SpParameter::getName () const [inline]
Access Methods:.
Definition at line 211 of file SpParameter.h.
References Spark::SpParameterPtr.
Referenced by Spark::SpParameterSet::insert().
SpParameter::Option Spark::SpParameter::getOption () const [inline]
Definition at line 298 of file SpParameter.h.
unsigned int Spark::SpParameter::getRegister () const [inline]
Definition at line 216 of file SpParameter.h.
int Spark::SpParameter::getSize (SpParameter::Type eType) const [inline]
Definition at line 236 of file SpParameter.h.
int Spark::SpParameter::getSize () const [inline]
Definition at line 283 of file SpParameter.h.
Referenced by setData(), and SpParameter().
SpParameter::Type Spark::SpParameter::getType () const [inline]
Definition at line 293 of file SpParameter.h.
bool Spark::SpParameter::hasChanged () const [inline]
Definition at line 221 of file SpParameter.h.
bool Spark::SpParameter::isBoolean () const [inline]
Definition at line 321 of file SpParameter.h.
Referenced by setData().
bool Spark::SpParameter::isFloat () const [inline]
Definition at line 352 of file SpParameter.h.
Referenced by setData().
bool Spark::SpParameter::isInteger () const [inline]
Definition at line 335 of file SpParameter.h.
Referenced by setData().
bool Spark::SpParameter::isNamed (const char * acName) const [inline]
Definition at line 313 of file SpParameter.h.
SpParameter & SpParameter::operator= (const SpParameter & rkConst)
Assignment:.
Definition at line 201 of file SpParameter.cpp.
References m_acName, m_bHasChanged, m_eOption, m_eType, m_iCount, m_iSize, m_pvData, m_uiRegister, and setData().
void Spark::SpParameter::setChanged (bool bChanged = false) [inline]
Definition at line 226 of file SpParameter.h.
void SpParameter::setData (const void * pvData, int iCount, SpParameter::Type eType)
Definition at line 237 of file SpParameter.cpp.
References getSize(), isBoolean(), isFloat(), isInteger(), m_bHasChanged, m_eType, m_iCount, m_iSize, and m_pvData.
void SpParameter::setData (const float akData[4][4])
Definition at line 344 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_MAT4.
void SpParameter::setData (const float akData[3][3])
Definition at line 313 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_MAT3.
void SpParameter::setData (const float akData[2][2])
Definition at line 288 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_MAT2.
void SpParameter::setData (float fX, float fY, float fZ, float fW)
Definition at line 560 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_VEC4.
void SpParameter::setData (float fX, float fY, float fZ)
Definition at line 537 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_VEC3.
void SpParameter::setData (float fX, float fY)
Definition at line 515 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_VEC2.
void SpParameter::setData (float fX)
Definition at line 494 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_FLOAT.
void SpParameter::setData (int iX, int iY, int iZ, int iW)
Definition at line 470 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_IVEC4.
void SpParameter::setData (int iX, int iY, int iZ)
Definition at line 447 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_IVEC3.
void SpParameter::setData (int iX, int iY)
Definition at line 425 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_IVEC2.
void SpParameter::setData (int iX)
Definition at line 404 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_INT.
void SpParameter::setData (bool bEnable)
Definition at line 383 of file SpParameter.cpp.
References m_bHasChanged, m_eType, m_iCount, m_iSize, m_pvData, and PT_BOOL.
Referenced by operator=(), and SpParameter().
void Spark::SpParameter::setOption (SpParameter::Option eOption) [inline]
Definition at line 308 of file SpParameter.h.
void Spark::SpParameter::setRegister (unsigned int uiRegister) [inline]
Definition at line 303 of file SpParameter.h.
Member Data Documentation
char* Spark::SpParameter::m_acName [protected]
Definition at line 202 of file SpParameter.h.
Referenced by operator=(), SpParameter(), and ~SpParameter().
bool Spark::SpParameter::m_bHasChanged [protected]
Definition at line 203 of file SpParameter.h.
Referenced by operator=(), setData(), and SpParameter().
SpParameter::Option Spark::SpParameter::m_eOption [protected]
Definition at line 200 of file SpParameter.h.
Referenced by operator=(), and SpParameter().
SpParameter::Type Spark::SpParameter::m_eType [protected]
Definition at line 199 of file SpParameter.h.
Referenced by operator=(), setData(), and SpParameter().
int Spark::SpParameter::m_iCount [protected]
Definition at line 197 of file SpParameter.h.
Referenced by operator=(), setData(), SpParameter(), and ~SpParameter().
int Spark::SpParameter::m_iSize [protected]
Definition at line 196 of file SpParameter.h.
Referenced by operator=(), setData(), and SpParameter().
void* Spark::SpParameter::m_pvData [protected]
Definition at line 194 of file SpParameter.h.
Referenced by operator=(), setData(), SpParameter(), and ~SpParameter().
unsigned int Spark::SpParameter::m_uiRegister [protected]
Internal Data:.
Definition at line 192 of file SpParameter.h.
Referenced by operator=(), and SpParameter().
The documentation for this class was generated from the following files:
SpParameter.h
SpParameter.cpp