Spark::SpGlslFragmentProgram Class Reference
#include <SpGlslFragmentProgram.h>
Detailed Description
Interface for a GLSL Fragment Program.
Definition at line 32 of file SpGlslFragmentProgram.h.
Public Member Functions
SpGlslFragmentProgram (const char *acSource)
Construction:.
virtual bool setParameter1i (const char *acName, int iX)
Parameter Methods:.
virtual bool setParameter2i (const char *acName, int iX, int iY)
virtual bool setParameter3i (const char *acName, int iX, int iY, int iZ)
virtual bool setParameter4i (const char *acName, int iX, int iY, int iZ, int iW)
virtual bool setParameter1iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter2iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter3iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter4iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter1f (const char *acName, float fX)
virtual bool setParameter2f (const char *acName, float fX, float fY)
virtual bool setParameter3f (const char *acName, float fX, float fY, float fZ)
virtual bool setParameter4f (const char *acName, float fX, float fY, float fZ, float fW)
virtual bool setParameter1fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter4fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter4fv (const char *acName, const float *afValues, int iCount=1)
Protected Member Functions
SpGlslFragmentProgram ()
Internal Data:.
int getParameterRegister (const char *acName)
Constructor & Destructor Documentation
SpGlslFragmentProgram::SpGlslFragmentProgram (const char * acSource)
Construction:.
Definition at line 9 of file SpGlslFragmentProgram.cpp.
References Spark::SpGpuProgram::setSource().
SpGlslFragmentProgram::SpGlslFragmentProgram () [protected]
Internal Data:.
Definition at line 16 of file SpGlslFragmentProgram.cpp.
Member Function Documentation
int SpGlslFragmentProgram::getParameterRegister (const char * acName) [protected]
Definition at line 22 of file SpGlslFragmentProgram.cpp.
References Spark::SpGpuProgram::getUserData().
Referenced by setMatrixParameter2fv(), setMatrixParameter3fv(), setMatrixParameter4fv(), setParameter1f(), setParameter1fv(), setParameter1i(), setParameter1iv(), setParameter2f(), setParameter2fv(), setParameter2i(), setParameter2iv(), setParameter3f(), setParameter3fv(), setParameter3i(), setParameter3iv(), setParameter4f(), setParameter4fv(), setParameter4i(), and setParameter4iv().
bool SpGlslFragmentProgram::setMatrixParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 232 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setMatrixParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 244 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setMatrixParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 256 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter1f (const char * acName, float fX) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 136 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter1fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 184 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter1i (const char * acName, int iX) [virtual]
Parameter Methods:.
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 40 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
Referenced by Spark::SpTurbulenceOp::updateOutputStream().
bool SpGlslFragmentProgram::setParameter1iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 88 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter2f (const char * acName, float fX, float fY) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 148 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 196 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter2i (const char * acName, int iX, int iY) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 52 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter2iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 100 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter3f (const char * acName, float fX, float fY, float fZ) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 160 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 208 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter3i (const char * acName, int iX, int iY, int iZ) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 64 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter3iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 112 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter4f (const char * acName, float fX, float fY, float fZ, float fW) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 172 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 220 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter4i (const char * acName, int iX, int iY, int iZ, int iW) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 76 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
bool SpGlslFragmentProgram::setParameter4iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 124 of file SpGlslFragmentProgram.cpp.
References getParameterRegister().
The documentation for this class was generated from the following files:
SpGlslFragmentProgram.h
SpGlslFragmentProgram.cpp