Spark::SpGlslVertexProgram Class Reference
#include <SpGlslVertexProgram.h>
Detailed Description
Interface for a GLSL Fragment Program.
Definition at line 32 of file SpGlslVertexProgram.h.
Public Member Functions
SpGlslVertexProgram (const char *acSource)
Construction:.
virtual bool setParameter1i (const char *acName, int iX)
Access Methods:.
virtual bool setParameter2i (const char *acName, int iX, int iY)
virtual bool setParameter3i (const char *acName, int iX, int iY, int iZ)
virtual bool setParameter4i (const char *acName, int iX, int iY, int iZ, int iW)
virtual bool setParameter1iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter2iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter3iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter4iv (const char *acName, const int *aiValues, int iCount=1)
virtual bool setParameter1f (const char *acName, float fX)
virtual bool setParameter2f (const char *acName, float fX, float fY)
virtual bool setParameter3f (const char *acName, float fX, float fY, float fZ)
virtual bool setParameter4f (const char *acName, float fX, float fY, float fZ, float fW)
virtual bool setParameter1fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setParameter4fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter2fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter3fv (const char *acName, const float *afValues, int iCount=1)
virtual bool setMatrixParameter4fv (const char *acName, const float *afValues, int iCount=1)
Protected Member Functions
SpGlslVertexProgram ()
Constructor for load function.
int getParameterRegister (const char *acName)
Constructor & Destructor Documentation
SpGlslVertexProgram::SpGlslVertexProgram (const char * acSource)
Construction:.
Definition at line 8 of file SpGlslVertexProgram.cpp.
References Spark::SpGpuProgram::setSource().
SpGlslVertexProgram::SpGlslVertexProgram () [protected]
Constructor for load function.
Definition at line 15 of file SpGlslVertexProgram.cpp.
Member Function Documentation
int SpGlslVertexProgram::getParameterRegister (const char * acName) [protected]
Definition at line 21 of file SpGlslVertexProgram.cpp.
References Spark::SpGpuProgram::getUserData().
Referenced by setMatrixParameter2fv(), setMatrixParameter3fv(), setMatrixParameter4fv(), setParameter1f(), setParameter1fv(), setParameter1i(), setParameter1iv(), setParameter2f(), setParameter2fv(), setParameter2i(), setParameter2iv(), setParameter3f(), setParameter3fv(), setParameter3i(), setParameter3iv(), setParameter4f(), setParameter4fv(), setParameter4i(), and setParameter4iv().
bool SpGlslVertexProgram::setMatrixParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 231 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setMatrixParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 243 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setMatrixParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 255 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter1f (const char * acName, float fX) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 135 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
Referenced by Spark::SpVertexNoiseSb::enable().
bool SpGlslVertexProgram::setParameter1fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 183 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter1i (const char * acName, int iX) [virtual]
Access Methods:.
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 39 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter1iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 87 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter2f (const char * acName, float fX, float fY) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 147 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter2fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 195 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter2i (const char * acName, int iX, int iY) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 51 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter2iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 99 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter3f (const char * acName, float fX, float fY, float fZ) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 159 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter3fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 207 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter3i (const char * acName, int iX, int iY, int iZ) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 63 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter3iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 111 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter4f (const char * acName, float fX, float fY, float fZ, float fW) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 171 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter4fv (const char * acName, const float * afValues, int iCount = 1) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 219 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
Referenced by Spark::SpVertexNoiseSb::initialize().
bool SpGlslVertexProgram::setParameter4i (const char * acName, int iX, int iY, int iZ, int iW) [virtual]
Reimplemented from Spark::SpGpuProgram (p.).
Definition at line 75 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
bool SpGlslVertexProgram::setParameter4iv (const char * acName, const int * aiValues, int iCount = 1) [virtual]
Definition at line 123 of file SpGlslVertexProgram.cpp.
References getParameterRegister().
The documentation for this class was generated from the following files:
SpGlslVertexProgram.h
SpGlslVertexProgram.cpp