Spark::SpParameterSet Class Reference
#include <SpParameterSet.h>
Detailed Description
Container class for parameters used with GPU programs.
Definition at line 34 of file SpParameterSet.h.
Public Member Functions
SpParameterSet ()
Construction:.
SpParameterSet (const SpParameterSet &rkConstants)
virtual ~SpParameterSet ()
void insert (const SpParameter &rkParam)
Insertion:.
void insert (const SpParameter *pkParam)
SpParameterPtr retrieve (const char *acName) const
Retrieval:.
SpParameterPtr retrieve (int iIndex) const
int size () const
Attributes:.
Protected Attributes
std::vector< SpParameterPtr > m_kSpParameters
Internal Data:.
Constructor & Destructor Documentation
SpParameterSet::SpParameterSet ()
Construction:.
Definition at line 6 of file SpParameterSet.cpp.
SpParameterSet::SpParameterSet (const SpParameterSet & rkConstants)
Definition at line 11 of file SpParameterSet.cpp.
References m_kSpParameters, retrieve(), and size().
SpParameterSet::~SpParameterSet () [virtual]
Definition at line 18 of file SpParameterSet.cpp.
Member Function Documentation
void SpParameterSet::insert (const SpParameter * pkParam)
Definition at line 39 of file SpParameterSet.cpp.
References Spark::SpParameter::getName(), and m_kSpParameters.
void SpParameterSet::insert (const SpParameter & rkParam)
Insertion:.
Definition at line 23 of file SpParameterSet.cpp.
References Spark::SpParameter::getName(), and m_kSpParameters.
SpParameterPtr Spark::SpParameterSet::retrieve (int iIndex) const [inline]
Definition at line 74 of file SpParameterSet.h.
SpParameterPtr SpParameterSet::retrieve (const char * acName) const
Retrieval:.
Definition at line 55 of file SpParameterSet.cpp.
References m_kSpParameters, and Spark::SpParameterPtr.
Referenced by SpParameterSet().
int Spark::SpParameterSet::size () const [inline]
Attributes:.
Definition at line 79 of file SpParameterSet.h.
Referenced by SpParameterSet().
Member Data Documentation
std::vector<SpParameterPtr> Spark::SpParameterSet::m_kSpParameters [protected]
Internal Data:.
Definition at line 67 of file SpParameterSet.h.
Referenced by insert(), retrieve(), and SpParameterSet().
The documentation for this class was generated from the following files:
SpParameterSet.h
SpParameterSet.cpp