Spark::SpStreamOperator Class Reference
#include <SpStreamOperator.h>
Detailed Description
Abstract base class for a stream operator which modifies an input stream.
Definition at line 34 of file SpStreamOperator.h.
Public Member Functions
SpStreamOperator ()
Construction:.
virtual ~SpStreamOperator ()
virtual void setInputStream (SpStreamInput *pkInputStream)
Operations:.
virtual bool hasChanged ()
Methods:.
virtual bool sendOutputToBuffer (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkOutput)
Protected Member Functions
virtual bool compute (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
Internal Methods:.
virtual bool enableOutputStream (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
virtual bool setupState (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
virtual bool processStream (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
virtual bool updateOutputStream (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
virtual bool resetState (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
virtual bool disableOutputStream (SpStreamBuffer *pkBuffer, SpStreamFeedback *pkCopy)
Constructor & Destructor Documentation
SpStreamOperator::SpStreamOperator ()
Construction:.
Definition at line 7 of file SpStreamOperator.cpp.
SpStreamOperator::~SpStreamOperator () [virtual]
Definition at line 13 of file SpStreamOperator.cpp.
Member Function Documentation
bool SpStreamOperator::compute (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Internal Methods:.
Definition at line 45 of file SpStreamOperator.cpp.
References disableOutputStream(), enableOutputStream(), processStream(), resetState(), setupState(), and updateOutputStream().
Referenced by sendOutputToBuffer().
bool SpStreamOperator::disableOutputStream (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 101 of file SpStreamOperator.cpp.
Referenced by compute().
bool SpStreamOperator::enableOutputStream (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 76 of file SpStreamOperator.cpp.
Referenced by compute().
bool SpStreamOperator::hasChanged () [virtual]
Methods:.
Implements Spark::SpStreamInput (p.).
Definition at line 24 of file SpStreamOperator.cpp.
References Spark::SpStreamInput::hasChanged().
bool SpStreamOperator::processStream (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 86 of file SpStreamOperator.cpp.
Referenced by compute().
bool SpStreamOperator::resetState (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 96 of file SpStreamOperator.cpp.
Referenced by compute().
bool SpStreamOperator::sendOutputToBuffer (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkOutput) [virtual]
Implements Spark::SpStreamInput (p.).
Definition at line 37 of file SpStreamOperator.cpp.
References compute().
void SpStreamOperator::setInputStream (SpStreamInput * pkInputStream) [virtual]
Operations:.
Reimplemented from Spark::SpStreamOutput (p.).
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 18 of file SpStreamOperator.cpp.
Referenced by Spark::SpTurbulenceOp::setInputStream().
bool SpStreamOperator::setupState (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 81 of file SpStreamOperator.cpp.
Referenced by compute().
bool SpStreamOperator::updateOutputStream (SpStreamBuffer * pkBuffer, SpStreamFeedback * pkCopy) [protected, virtual]
Reimplemented in Spark::SpTurbulenceOp (p.).
Definition at line 91 of file SpStreamOperator.cpp.
Referenced by compute().
The documentation for this class was generated from the following files:
SpStreamOperator.h
SpStreamOperator.cpp