Spark::SpGlManager Class Reference
#include <SpGlManager.h>
Detailed Description
Static manager class for interfacing with OpenGL.
Definition at line 30 of file SpGlManager.h.
Public Member Functions
~SpGlManager ()
Construction:.
Static Public Member Functions
void deleteTexture (unsigned int uiTextureId)
Operations:.
unsigned int createTexture (int iWidth, int iHeight, GLenum eTextureMode=GL_TEXTURE_2D, GLenum eImageFormat=GL_RGBA8, GLenum ePixelFormat=GL_RGBA, GLenum eComponentFormat=GL_FLOAT, void *pvData=NULL)
unsigned int createFilteredTexture (int iWidth, int iHeight, GLenum eTextureMode=GL_TEXTURE_2D, GLenum eImageFormat=GL_RGBA8, GLenum ePixelFormat=GL_RGBA, GLenum eComponentFormat=GL_FLOAT, GLenum eMinFilterMode=GL_NEAREST, GLenum eMagFilterMode=GL_NEAREST, GLenum eSWrapMode=GL_CLAMP_TO_EDGE, GLenum eTWrapMode=GL_CLAMP_TO_EDGE, void *pvData=NULL)
void printOnError (char *acMsg)
Constructor & Destructor Documentation
Spark::SpGlManager::~SpGlManager ()
Construction:.
Member Function Documentation
unsigned int SpGlManager::createFilteredTexture (int iWidth, int iHeight, GLenum eTextureMode = GL_TEXTURE_2D, GLenum eImageFormat = GL_RGBA8, GLenum ePixelFormat = GL_RGBA, GLenum eComponentFormat = GL_FLOAT, GLenum eMinFilterMode = GL_NEAREST, GLenum eMagFilterMode = GL_NEAREST, GLenum eSWrapMode = GL_CLAMP_TO_EDGE, GLenum eTWrapMode = GL_CLAMP_TO_EDGE, void * pvData = NULL) [static]
Definition at line 42 of file SpGlManager.cpp.
References createTexture().
Referenced by Spark::SpTurbulenceOp::initialize().
unsigned int SpGlManager::createTexture (int iWidth, int iHeight, GLenum eTextureMode = GL_TEXTURE_2D, GLenum eImageFormat = GL_RGBA8, GLenum ePixelFormat = GL_RGBA, GLenum eComponentFormat = GL_FLOAT, void * pvData = NULL) [static]
Definition at line 15 of file SpGlManager.cpp.
Referenced by createFilteredTexture().
void SpGlManager::deleteTexture (unsigned int uiTextureId) [static]
Operations:.
Definition at line 10 of file SpGlManager.cpp.
Referenced by Spark::SpTurbulenceOp::initialize(), and Spark::SpTurbulenceOp::~SpTurbulenceOp().
void SpGlManager::printOnError (char * acMsg) [static]
Definition at line 88 of file SpGlManager.cpp.
The documentation for this class was generated from the following files:
SpGlManager.h
SpGlManager.cpp