Spark::SpTuple4< Real > Class Template Reference
#include <SpTuple.h>
Detailed Description
template<class Real> class Spark::SpTuple4< Real >
4D tuple data class with support for vector mathematics
Definition at line 188 of file SpTuple.h.
Public Member Functions
SpTuple4 (const SpTuple< 4, Real > &rkV)
Construction.
SpTuple4 (Real fX=0, Real fY=0, Real fZ=0, Real fW=1)
Real x () const
Position Coordinate Access:.
Real & x ()
Real y () const
Real & y ()
Real z () const
Real & z ()
Real w () const
Real & w ()
Real r () const
Color Component Access:.
Real & r ()
Real g () const
Real & g ()
Real b () const
Real & b ()
Real a () const
Real & a ()
Real s () const
Texture Coordinate Access:.
Real & s ()
Real t () const
Real & t ()
Real p () const
Real & p ()
Real q () const
Real & q ()
Constructor & Destructor Documentation
template<class Real> Spark::SpTuple4< Real >::SpTuple4 (const SpTuple< 4, Real > & rkV) [inline]
Construction.
Definition at line 194 of file SpTuple.h.
template<class Real> Spark::SpTuple4< Real >::SpTuple4 (Real fX = 0, Real fY = 0, Real fZ = 0, Real fW = 1) [inline]
Definition at line 197 of file SpTuple.h.
Member Function Documentation
template<class Real> Real& Spark::SpTuple4< Real >::a () [inline]
Definition at line 222 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::a () const [inline]
Definition at line 221 of file SpTuple.h.
Referenced by Spark::SpWindow::drawString().
template<class Real> Real& Spark::SpTuple4< Real >::b () [inline]
Definition at line 220 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::b () const [inline]
Definition at line 219 of file SpTuple.h.
Referenced by Spark::SpWindow::drawString().
template<class Real> Real& Spark::SpTuple4< Real >::g () [inline]
Definition at line 218 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::g () const [inline]
Definition at line 217 of file SpTuple.h.
Referenced by Spark::SpWindow::drawString().
template<class Real> Real& Spark::SpTuple4< Real >::p () [inline]
Definition at line 232 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::p () const [inline]
Definition at line 231 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple4< Real >::q () [inline]
Definition at line 234 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::q () const [inline]
Definition at line 233 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple4< Real >::r () [inline]
Definition at line 216 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::r () const [inline]
Color Component Access:.
Definition at line 215 of file SpTuple.h.
Referenced by Spark::SpWindow::drawString().
template<class Real> Real& Spark::SpTuple4< Real >::s () [inline]
Definition at line 228 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::s () const [inline]
Texture Coordinate Access:.
Definition at line 227 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple4< Real >::t () [inline]
Definition at line 230 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::t () const [inline]
Definition at line 229 of file SpTuple.h.
template<class Real> Real& Spark::SpTuple4< Real >::w () [inline]
Definition at line 210 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::w () const [inline]
Definition at line 209 of file SpTuple.h.
Referenced by Spark::SpTuple4< float >::SpTuple4().
template<class Real> Real& Spark::SpTuple4< Real >::x () [inline]
Definition at line 204 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::x () const [inline]
Position Coordinate Access:.
Definition at line 203 of file SpTuple.h.
Referenced by Spark::SpTuple4< float >::SpTuple4().
template<class Real> Real& Spark::SpTuple4< Real >::y () [inline]
Definition at line 206 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::y () const [inline]
Definition at line 205 of file SpTuple.h.
Referenced by Spark::SpTuple4< float >::SpTuple4().
template<class Real> Real& Spark::SpTuple4< Real >::z () [inline]
Definition at line 208 of file SpTuple.h.
template<class Real> Real Spark::SpTuple4< Real >::z () const [inline]
Definition at line 207 of file SpTuple.h.
Referenced by Spark::SpTuple4< float >::SpTuple4().
The documentation for this class was generated from the following file:
SpTuple.h