Detailed Description
SpAllocate.h(p.) : Custom Memory Allocation Routines for Multiple Dimensions.
Classes
class Spark::SpCopyToTexture3d
Sliced 3D Copy To Texture (CTT) feedback mechanism via OpenGL.
class Spark::SpCopyToTexture3dFb
Sliced 3D Copy To Texture (CTT) feedback mechanism via OpenGL.
class Spark::SpCopyToTextureFb
Copy To Texture (CTT) feedback mechanism via OpenGL.
class Spark::SpGlManager
Static manager class for interfacing with OpenGL.
class Spark::SpGlslFragmentProgram
Interface for a GLSL Fragment Program.
class Spark::SpGlslManager
Static manager class for interfacing with GLSL.
class Spark::SpGlslVertexProgram
Interface for a GLSL Fragment Program.
class Spark::SpGpuProgram
Abstract base class for a GPU program.
class Spark::SpGridSg
Multi-resolution grid-based stream geometry.
class Spark::SpMaths< Real >
Static utility class for mathematical constants.
class Spark::SpMatrix< N, Real >
NxN Matrix base class for vector algebra.
class Spark::SpMatrix2< Real >
2x2 pMatrix class for vector algebra
class Spark::SpMatrix3< Real >
3x3 Matrix class for vector algebra
class Spark::SpMatrix4< Real >
4x4 Matrix class for vector algebra
class Spark::SpMultiTexturedGridSg
Multi-resolution grid-based stream geometry w/ multi-texturing support.
class Spark::SpMultiTexturedQuadSg
Quad-based stream geometry w/ multi-texturing support.
class Spark::SpParameter
Storage class for multiple data types for use with GPU programs.
class Spark::SpParameterSet
Container class for parameters used with GPU programs.
class Spark::SpQuadSg
Quad-based stream geometry.
class Spark::SpReference< ClassType >
Reference class with garbage collection for supporting shared objects.
class Spark::SpResourcePath
Resource utility class for querying a file system and loading datafiles.
class Spark::SpStreamBasis
Abstract base class for a stream basis for spectral synthesis.
class Spark::SpStreamBuffer
A multi-format OpenGL GPU resident data buffer and render-to-texture (RTT) interface.
class Spark::SpStreamFeedback
Abstract base class for a stream feedback mechanism for returning results.
class Spark::SpStreamGeometry
Abstract base class for generating a data stream by rendering geometry.
class Spark::SpStreamInput
Abstract base class for an input stream for loading/generating a data stream.
class Spark::SpStreamOperator
Abstract base class for a stream operator which modifies an input stream.
class Spark::SpStreamOutput
Abstract base class for an output stream used fo saving/viewing stream data.
class Spark::SpStreamViewer
Stream viewer output class for visualizing a data stream.
class Spark::SpString
String utility class for character data.
class Spark::SpTexturedGridSg
Multi-resolution grid-based stream geometry w/ texturing support.
class Spark::SpTexturedQuadSg
Quad-based stream geometry w/ texturing support.
class Spark::SpTimer
Basic Timer for profiling and retrieving performance/time info.
class Spark::SpTuple< N, Real >
N-Dimensional data class with support for vector mathematics.
class Spark::SpTuple2< Real >
2D tuple data class with support for vector mathematics
class Spark::SpTuple3< Real >
3D tuple data class with support for vector mathematics
class Spark::SpTuple4< Real >
4D tuple data class with support for vector mathematics
class Spark::SpTurbulenceOp
Turbulence stream operator to be used with a stream basis class.
class Spark::SpVertexNoiseSb
Noise generating stream basis which operates on vertex data.
class Spark::SpWindow
Abstract base class for a graphical display window.
Typedefs
typedef SpReference< SpGpuProgram > SpGpuProgramPtr
typedef SpReference< SpParameter > SpParameterPtr
typedef std::string SpStringBase
typedef std::stringstream SpStringStreamType
typedef std::vector< SpString > SpStringArray
typedef std::list< SpString > SpStringList
typedef std::pair< SpString, SpString > SpStringPair
typedef SpTuple2< float > vec2
typedef SpTuple3< float > vec3
typedef SpTuple4< float > vec4
typedef SpTuple2< int > ivec2
typedef SpTuple3< int > ivec3
typedef SpTuple4< int > ivec4
typedef SpTuple2< bool > bvec2
typedef SpTuple3< bool > bvec3
typedef SpTuple4< bool > bvec4
typedef SpTuple2< float > float2
typedef SpTuple3< float > float3
typedef SpTuple4< float > float4
typedef SpTuple2< float > SpVector2f
typedef SpTuple3< float > SpVector3f
typedef SpTuple4< float > SpVector4f
typedef SpTuple3< char > SpColor3b
typedef SpTuple4< char > SpColor4b
typedef SpTuple3< unsigned char > SpColor3ub
typedef SpTuple4< unsigned char > SpColor4ub
typedef SpTuple3< int > SpColor3i
typedef SpTuple4< int > SpColor4i
typedef SpTuple3< unsigned int > SpColor3ui
typedef SpTuple4< unsigned int > SpColor4ui
typedef SpTuple3< float > SpColor3f
typedef SpTuple4< float > SpColor4f
Functions
template<class T> void Allocate2D (int iCols, int iRows, T **&raatArray)
template<class T> void Deallocate2D (T **aatArray)
template<class T> void Allocate3D (int iCols, int iRows, int iSlices, T ***&raaatArray)
template<class T> void Deallocate3D (int iRows, int iSlices, T ***aaatArray)
template<class Real> Real Erfc (Real fX)
template<class Real> Real LogGamma (Real fX)
template<class Real> Real Radians (Real fDeg)
template<class Real> Real Degrees (Real fRad)
template<class Real> Real Abs (Real fValue)
template<class Real> Real Ceil (Real fValue)
template<class Real> Real Clamp (Real fV, Real fMin, Real fMax)
template<class Real> Real Exp (Real fValue)
template<class Real> Real Floor (Real fValue)
template<class Real> Real InvSqrt (Real fValue)
template<class Real> Real Log (Real fValue)
template<class Real> Real Pow (Real fBase, Real fExponent)
template<class Real> Real Cub (Real fValue)
template<class Real> Real Square (Real fValue)
template<class Real> Real Sqr (Real fValue)
template<class Real> Real Sqrt (Real fValue)
template<class Real> Real Sign (Real fValue)
template<class Real> Real Gamma (Real fX)
template<class Real> Real Gaussian (Real fX, Real fStdDev)
template<class Real> Real Min (Real fX, Real fA)
template<class Real> Real Max (Real fX, Real fA)
template<class Real> Real Mod (Real fX, Real fA)
template<class Real> Real Frac (const Real fX)
template<class Real> Real Step (Real fX, Real fA)
template<class Real> Real Erf (Real fX)
template<class Real> Real ArcCosine (Real fValue)
template<class Real> Real ArcSine (Real fValue)
template<class Real> Real ArcTangent (Real fValue)
template<class Real> Real ArcTangent (Real fY, Real fX)
template<class Real> Real Cosine (Real fValue)
template<class Real> Real Sine (Real fValue)
template<class Real> Real Tangent (Real fValue)
bool IsPowerOfTwo (int iWidth, int iHeight)
template<unsigned int N, class Real> SpMatrix< N, Real > operator * (Real fScalar, const SpMatrix< N, Real > &rkM)
template<unsigned int N, class Real> SpTuple< N, Real > operator * (const SpTuple< N, Real > &rkV, const SpMatrix< N, Real > &rkM)
template<class Real> Real Quadric (Real fA, Real fB, Real fC)
template<class Real> Real Spline (Real fX, unsigned int uiKnots, Real *apkKnots, const Real afB[4][4]=CatmullRomBasis)
template<class Real> Real CellNoise (Real fX, Real fY, Real fZ)
template<class Real> Real GradientNoise (Real fX, Real fY, Real fZ)
template<class Real> Real ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4]=CatmullRomBasis)
template<class Real> Real FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real Turbulence (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.25f, Real fLacunarity=2.0345f, Real fOffset=0.7f, Real fGain=1.0f, Real fOctaves=4.0f)
template<class Real> Real RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.9f, Real fLacunarity=2.0345f, Real fThreshold=0.5f, Real fOffset=1.0f, Real fOctaves=4.0f)
template<class Real> Real FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real &rfOX, Real &rfOY, Real &rfOZ)
template<class Real> Real DefaultTurbulence (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultFBM (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultMonoFractal (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultMultiFractal (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ)
template<class Real> Real fBm (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
int p (int iX)
float r (int iX)
template<class Real> int Hash (int iX, int iY, int iZ)
template<class Real> Real Lattice (int iX, int iY, int iZ)
template<class Real> Real Gradient (int iX, int iY, int iZ, Real fX, Real fY, Real fZ)
template<class Real> Real Bias (Real fX, Real fA)
template<class Real> Real Gain (Real fX, Real fA)
template<class Real> Real Cubic (Real fT)
template<class Real> Real Quintic (Real fT)
template<class Real> Real Lerp (Real fT, Real fA, Real fB)
template<class Real> Real BoxStep (Real fX, Real fA, Real fB)
template<class Real> Real SmoothStep (Real fA, Real fB, Real fX)
template<class Real> Real Pulse (Real fX, Real fA, Real fB)
template<class Real> Real BoxPulse (Real fX, Real fA, Real fB)
template<class Real> Real SmoothPulse (Real fX, Real fA, Real fB)
template<class Real> Real FilteredAbs (Real fX, Real fDX)
template<class Real> Real CatmullRomNoise (Real fX, Real fY, Real fZ)
template<class Real> Real HermiteNoise (Real fX, Real fY, Real fZ)
template<class Real> Real CardinalNoise (Real fX, Real fY, Real fZ)
template<class Real> Real BSplineNoise (Real fX, Real fY, Real fZ)
template<class Real> Real FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth)
void SeedRandom (unsigned long seed)
Initializes the random number table.
unsigned int RandomUInt (void)
Generates a random 32bit unsigned int.
float RandomUnitFloat (void)
Generates a random real number on [0,1]-real-interval.
float RandomUnitOpenFloat (void)
Generates a random real number on [0,1)-real-interval.
float RandomSymmetricFloat (void)
Generates a random real number on [-1,1].
float RandomIntervalFloat (float fMin, float fMax)
Generates a random real number on [-min, max].
template<unsigned int N, class Real> SpTuple< N, Real > operator * (Real fScalar, const SpTuple< N, Real > &rkV)
template<unsigned int N, class Real> Real Length (const SpTuple< N, Real > &rkV)
template<unsigned int N, class Real> Real LengthSquared (const SpTuple< N, Real > &rkV)
template<unsigned int N, class Real> Real Dot (const SpTuple< N, Real > &rkA, const SpTuple< N, Real > &rkB)
template<unsigned int N, class Real> SpTuple< N, Real > Normalize (const SpTuple< N, Real > &rkV)
template<unsigned int N, class Real> SpTuple< N, Real > Clamp (const SpTuple< N, Real > &rkV, Real fMin, Real fMax)
template<unsigned int N, class Real> SpTuple< N, Real > Offset (const SpTuple< N, Real > &rkV, Real fOffset)
template<class Real> SpTuple3< Real > Normalize (const SpTuple3< Real > &rkV)
template<class Real> SpTuple3< Real > NormalizedCross (const SpTuple3< Real > &rkV1, const SpTuple3< Real > &rkV2)
template<class Real> SpTuple3< Real > Cross (const SpTuple3< Real > &rkV1, const SpTuple3< Real > &rkV2)
template<class Real> SpTuple4< Real > Normalize (const SpTuple4< Real > &rkV)
template<class Real> SpTuple4< Real > NormalizedCross (const SpTuple4< Real > &rkV1, const SpTuple4< Real > &rkV2)
template<class Real> SpTuple4< Real > Cross (const SpTuple4< Real > &rkV1, const SpTuple4< Real > &rkV2)
Typedef Documentation
typedef SpTuple2<bool> Spark::bvec2
Definition at line 715 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<bool> Spark::bvec3
Definition at line 716 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<bool> Spark::bvec4
Definition at line 717 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple2<float> Spark::float2
Definition at line 719 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<float> Spark::float3
Definition at line 720 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<float> Spark::float4
Definition at line 721 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple2<int> Spark::ivec2
Definition at line 711 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<int> Spark::ivec3
Definition at line 712 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<int> Spark::ivec4
Definition at line 713 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<char> Spark::SpColor3b
Definition at line 727 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<float> Spark::SpColor3f
Definition at line 739 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::values().
typedef SpTuple3<int> Spark::SpColor3i
Definition at line 733 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<unsigned char> Spark::SpColor3ub
Definition at line 730 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<unsigned int> Spark::SpColor3ui
Definition at line 736 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::values().
typedef SpTuple4<char> Spark::SpColor4b
Definition at line 728 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<float> Spark::SpColor4f
Definition at line 740 of file SpTuple.h.
Referenced by Spark::SpWindow::drawFrameRate(), Spark::SpWindow::drawString(), Spark::SpWindow::SpWindow(), and Spark::SpTuple< N, Real >::values().
typedef SpTuple4<int> Spark::SpColor4i
Definition at line 734 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<unsigned char> Spark::SpColor4ub
Definition at line 731 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<unsigned int> Spark::SpColor4ui
Definition at line 737 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::values().
typedef SpReference< SpGpuProgram > Spark::SpGpuProgramPtr
Definition at line 152 of file SpGpuProgram.h.
Referenced by Spark::SpGpuProgram::getSource().
typedef SpReference< SpParameter > Spark::SpParameterPtr
Definition at line 375 of file SpParameter.h.
Referenced by Spark::SpParameter::getName(), and Spark::SpParameterSet::retrieve().
typedef std::vector<SpString> Spark::SpStringArray
Definition at line 49 of file SpString.h.
Referenced by Spark::SpResourcePath::searchpath().
typedef std::string Spark::SpStringBase
Definition at line 44 of file SpString.h.
Referenced by Spark::SpString::SpString().
typedef std::list<SpString> Spark::SpStringList
Definition at line 50 of file SpString.h.
typedef std::pair<SpString, SpString> Spark::SpStringPair
Definition at line 51 of file SpString.h.
typedef std::stringstream Spark::SpStringStreamType
Definition at line 48 of file SpString.h.
typedef SpTuple2<float> Spark::SpVector2f
Definition at line 723 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<float> Spark::SpVector3f
Definition at line 724 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<float> Spark::SpVector4f
Definition at line 725 of file SpTuple.h.
Referenced by Spark::SpVertexNoiseSb::initialize(), and Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple2<float> Spark::vec2
Definition at line 707 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple3<float> Spark::vec3
Definition at line 708 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
typedef SpTuple4<float> Spark::vec4
Definition at line 709 of file SpTuple.h.
Referenced by Spark::SpTuple< N, Real >::SpTuple().
Function Documentation
template<class Real> Real Spark::Abs (Real fValue)
Definition at line 164 of file SpMaths.h.
Referenced by RidgedMultiFractal(), and Turbulence().
template<class T> void Allocate2D (int iCols, int iRows, T **& raatArray)
Definition at line 29 of file SpAllocate.h.
template<class T> void Allocate3D (int iCols, int iRows, int iSlices, T ***& raaatArray)
Definition at line 45 of file SpAllocate.h.
template<class Real> Real Spark::ArcCosine (Real fValue)
Definition at line 275 of file SpMaths.h.
template<class Real> Real Spark::ArcSine (Real fValue)
Definition at line 290 of file SpMaths.h.
template<class Real> Real Spark::ArcTangent (Real fY, Real fX)
Definition at line 310 of file SpMaths.h.
template<class Real> Real Spark::ArcTangent (Real fValue)
Definition at line 305 of file SpMaths.h.
template<class Real> Real Spark::Bias (Real fX, Real fA)
Definition at line 261 of file SpProcedural.h.
template<class Real> Real Spark::BoxPulse (Real fX, Real fA, Real fB)
Definition at line 337 of file SpProcedural.h.
template<class Real> Real Spark::BoxStep (Real fX, Real fA, Real fB)
Definition at line 311 of file SpProcedural.h.
template<class Real> Real Spark::BSplineNoise (Real fX, Real fY, Real fZ)
Definition at line 362 of file SpProcedural.h.
template<class Real> Real Spark::CardinalNoise (Real fX, Real fY, Real fZ)
Definition at line 357 of file SpProcedural.h.
template<class Real> Real Spark::CatmullRomNoise (Real fX, Real fY, Real fZ)
Definition at line 347 of file SpProcedural.h.
template<class Real> Real Spark::Ceil (Real fValue)
Definition at line 169 of file SpMaths.h.
template<class Real> Real Spark::CellNoise (Real fX, Real fY, Real fZ)
Definition at line 51 of file SpProcedural.cpp.
References Floor(), Hash(), and r().
Referenced by VoronoiNoise().
template<unsigned int N, class Real> SpTuple< N, Real > Spark::Clamp (const SpTuple< N, Real > & rkV, Real fMin, Real fMax)
Definition at line 594 of file SpTuple.h.
template<class Real> Real Spark::Clamp (Real fV, Real fMin, Real fMax)
Definition at line 174 of file SpMaths.h.
Referenced by RidgedMultiFractal(), and Spline().
template<class Real> Real Spark::Cosine (Real fValue)
Definition at line 315 of file SpMaths.h.
template<class Real> SpTuple4< Real > Spark::Cross (const SpTuple4< Real > & rkV1, const SpTuple4< Real > & rkV2)
Definition at line 692 of file SpTuple.h.
template<class Real> SpTuple3< Real > Spark::Cross (const SpTuple3< Real > & rkV1, const SpTuple3< Real > & rkV2)
Definition at line 648 of file SpTuple.h.
template<class Real> Real Spark::Cub (Real fValue)
Definition at line 204 of file SpMaths.h.
template<class Real> Real Spark::Cubic (Real fT)
Definition at line 291 of file SpProcedural.h.
Referenced by GradientNoise().
template<class T> void Deallocate2D (T ** aatArray)
Definition at line 38 of file SpAllocate.h.
template<class T> void Deallocate3D (int iRows, int iSlices, T *** aaatArray)
Definition at line 57 of file SpAllocate.h.
template<class Real> Real Spark::DefaultFBM (Real fX, Real fY, Real fZ)
Definition at line 395 of file SpProcedural.h.
template<class Real> Real Spark::DefaultMonoFractal (Real fX, Real fY, Real fZ)
Definition at line 401 of file SpProcedural.h.
template<class Real> Real Spark::DefaultMultiFractal (Real fX, Real fY, Real fZ)
Definition at line 407 of file SpProcedural.h.
template<class Real> Real Spark::DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ)
Definition at line 413 of file SpProcedural.h.
template<class Real> Real Spark::DefaultTurbulence (Real fX, Real fY, Real fZ)
Definition at line 389 of file SpProcedural.h.
template<class Real> Real Degrees (Real fRad)
Definition at line 69 of file SpMaths.h.
template<unsigned int N, class Real> Real Spark::Dot (const SpTuple< N, Real > & rkA, const SpTuple< N, Real > & rkB)
Definition at line 562 of file SpTuple.h.
template<class Real> Real Spark::Erf (Real fX)
Definition at line 270 of file SpMaths.h.
template<class Real> Real Erfc (Real fX)
template<class Real> Real Spark::Exp (Real fValue)
Definition at line 179 of file SpMaths.h.
template<class Real> Real Spark::fBm (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 419 of file SpProcedural.h.
template<class Real> Real Spark::FilteredAbs (Real fX, Real fDX)
Definition at line 367 of file SpProcedural.h.
Referenced by FilteredTurbulence().
template<class Real> Real Spark::FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 188 of file SpProcedural.cpp.
References FilteredGradientNoise().
template<class Real> Real Spark::FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth)
Definition at line 382 of file SpProcedural.h.
Referenced by FilteredFBM(), and FilteredTurbulence().
template<class Real> Real Spark::FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 296 of file SpProcedural.cpp.
References FilteredAbs(), and FilteredGradientNoise().
template<class Real> Real Spark::Floor (Real fValue)
Definition at line 184 of file SpMaths.h.
Referenced by CellNoise(), GradientNoise(), and VoronoiNoise().
template<class Real> Real Spark::Frac (const Real fX)
Definition at line 265 of file SpMaths.h.
template<class Real> Real Spark::FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 143 of file SpProcedural.cpp.
References GradientNoise().
template<class Real> Real Spark::Gain (Real fX, Real fA)
Definition at line 270 of file SpProcedural.h.
template<class Real> Real Spark::Gamma (Real fX)
Definition at line 235 of file SpMaths.h.
template<class Real> Real Spark::Gaussian (Real fX, Real fStdDev)
Definition at line 240 of file SpMaths.h.
template<class Real> Real Spark::Gradient (int iX, int iY, int iZ, Real fX, Real fY, Real fZ)
Definition at line 241 of file SpProcedural.h.
Referenced by GradientNoise().
template<class Real> Real Spark::GradientNoise (Real fX, Real fY, Real fZ)
Definition at line 61 of file SpProcedural.cpp.
References Cubic(), Floor(), Gradient(), and Lerp().
Referenced by FractionalBrownianMotion(), HybridMultiFractal(), MonoFractal(), MultiFractal(), RidgedMultiFractal(), and Turbulence().
template<class Real> int Spark::Hash (int iX, int iY, int iZ)
Definition at line 231 of file SpProcedural.h.
Referenced by CellNoise().
template<class Real> Real Spark::HermiteNoise (Real fX, Real fY, Real fZ)
Definition at line 352 of file SpProcedural.h.
template<class Real> Real Spark::HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.25f, Real fLacunarity = 2.0345f, Real fOffset = 0.7f, Real fGain = 1.0f, Real fOctaves = 4.0f)
Definition at line 456 of file SpProcedural.cpp.
References GradientNoise().
template<class Real> Real Spark::InvSqrt (Real fValue)
Definition at line 189 of file SpMaths.h.
bool Spark::IsPowerOfTwo (int iWidth, int iHeight) [inline]
Definition at line 330 of file SpMaths.h.
template<class Real> Real Spark::Lattice (int iX, int iY, int iZ)
Definition at line 236 of file SpProcedural.h.
Referenced by ValueNoise().
template<unsigned int N, class Real> Real Spark::Length (const SpTuple< N, Real > & rkV)
Definition at line 544 of file SpTuple.h.
template<unsigned int N, class Real> Real Spark::LengthSquared (const SpTuple< N, Real > & rkV)
Definition at line 553 of file SpTuple.h.
template<class Real> Real Spark::Lerp (Real fT, Real fA, Real fB)
Definition at line 301 of file SpProcedural.h.
Referenced by GradientNoise().
template<class Real> Real Spark::Log (Real fValue)
Definition at line 194 of file SpMaths.h.
template<class Real> Real LogGamma (Real fX)
template<class Real> Real Spark::Max (Real fX, Real fA)
Definition at line 260 of file SpMaths.h.
template<class Real> Real Spark::Min (Real fX, Real fA)
Definition at line 255 of file SpMaths.h.
template<class Real> Real Spark::Mod (Real fX, Real fA)
Definition at line 245 of file SpMaths.h.
template<class Real> Real Spark::MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 356 of file SpProcedural.cpp.
References GradientNoise().
template<class Real> Real Spark::MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 407 of file SpProcedural.cpp.
References GradientNoise().
template<class Real> SpTuple4< Real > Spark::Normalize (const SpTuple4< Real > & rkV)
Definition at line 660 of file SpTuple.h.
template<class Real> SpTuple3< Real > Spark::Normalize (const SpTuple3< Real > & rkV)
Definition at line 618 of file SpTuple.h.
template<unsigned int N, class Real> SpTuple< N, Real > Spark::Normalize (const SpTuple< N, Real > & rkV)
Definition at line 571 of file SpTuple.h.
Referenced by Spark::SpVertexNoiseSb::initialize().
template<class Real> SpTuple4< Real > Spark::NormalizedCross (const SpTuple4< Real > & rkV1, const SpTuple4< Real > & rkV2)
Definition at line 679 of file SpTuple.h.
template<class Real> SpTuple3< Real > Spark::NormalizedCross (const SpTuple3< Real > & rkV1, const SpTuple3< Real > & rkV2)
Definition at line 636 of file SpTuple.h.
template<unsigned int N, class Real> SpTuple< N, Real > Spark::Offset (const SpTuple< N, Real > & rkV, Real fOffset)
Definition at line 606 of file SpTuple.h.
template<unsigned int N, class Real> SpTuple< N, Real > Spark::operator * (Real fScalar, const SpTuple< N, Real > & rkV)
Definition at line 475 of file SpTuple.h.
template<unsigned int N, class Real> SpTuple<N,Real> operator * (const SpTuple< N, Real > & rkV, const SpMatrix< N, Real > & rkM)
template<unsigned int N, class Real> SpMatrix<N,Real> operator * (Real fScalar, const SpMatrix< N, Real > & rkM)
int Spark::p (int iX) [inline]
Definition at line 225 of file SpProcedural.h.
template<class Real> Real Spark::Pow (Real fBase, Real fExponent)
Definition at line 199 of file SpMaths.h.
Referenced by Spark::SpTurbulenceOp::initialize().
template<class Real> Real Spark::Pulse (Real fX, Real fA, Real fB)
Definition at line 332 of file SpProcedural.h.
template<class Real> Real Spark::Quadric (Real fA, Real fB, Real fC)
Definition at line 598 of file SpProcedural.cpp.
References Sqrt().
template<class Real> Real Spark::Quintic (Real fT)
Definition at line 296 of file SpProcedural.h.
float Spark::r (int iX) [inline]
Definition at line 219 of file SpProcedural.h.
Referenced by CellNoise().
template<class Real> Real Radians (Real fDeg)
Definition at line 66 of file SpMaths.h.
float RandomIntervalFloat (float fMin, float fMax) [inline]
Generates a random real number on [-min, max].
Definition at line 88 of file SpRandom.h.
References RandomUnitFloat().
float RandomSymmetricFloat (void) [inline]
Generates a random real number on [-1,1].
Definition at line 80 of file SpRandom.h.
References RandomUnitFloat().
Referenced by Spark::SpVertexNoiseSb::initialize().
unsigned int Spark::RandomUInt (void)
Generates a random 32bit unsigned int.
Definition at line 70 of file SpRandom.cpp.
References LOWER_MASK, M, MATRIX_A, N, SeedRandom(), and UPPER_MASK.
Referenced by Spark::SpVertexNoiseSb::initialize(), RandomUnitFloat(), and RandomUnitOpenFloat().
float Spark::RandomUnitFloat (void)
Generates a random real number on [0,1]-real-interval.
Definition at line 112 of file SpRandom.cpp.
References RandomUInt().
Referenced by RandomIntervalFloat(), and RandomSymmetricFloat().
float Spark::RandomUnitOpenFloat (void)
Generates a random real number on [0,1)-real-interval.
Definition at line 119 of file SpRandom.cpp.
References RandomUInt().
template<class Real> Real Spark::RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.9f, Real fLacunarity = 2.0345f, Real fThreshold = 0.5f, Real fOffset = 1.0f, Real fOctaves = 4.0f)
Definition at line 527 of file SpProcedural.cpp.
References Abs(), Clamp(), and GradientNoise().
void Spark::SeedRandom (unsigned long seed)
Initializes the random number table.
Definition at line 51 of file SpRandom.cpp.
References N.
Referenced by Spark::SpVertexNoiseSb::initialize(), and RandomUInt().
template<class Real> Real Spark::Sign (Real fValue)
Definition at line 224 of file SpMaths.h.
template<class Real> Real Spark::Sine (Real fValue)
Definition at line 320 of file SpMaths.h.
template<class Real> Real Spark::SmoothPulse (Real fX, Real fA, Real fB)
Definition at line 342 of file SpProcedural.h.
template<class Real> Real Spark::SmoothStep (Real fA, Real fB, Real fX)
Definition at line 316 of file SpProcedural.h.
template<class Real> Real Spark::Spline (Real fX, unsigned int uiKnots, Real * apkKnots, const Real afB[4][4] = CatmullRomBasis)
Definition at line 28 of file SpProcedural.cpp.
References Clamp().
Referenced by ValueNoise().
template<class Real> Real Spark::Sqr (Real fValue)
Definition at line 214 of file SpMaths.h.
template<class Real> Real Spark::Sqrt (Real fValue)
Definition at line 219 of file SpMaths.h.
Referenced by Quadric(), and VoronoiNoise().
template<class Real> Real Spark::Square (Real fValue)
Definition at line 209 of file SpMaths.h.
template<class Real> Real Spark::Step (Real fX, Real fA)
Definition at line 306 of file SpProcedural.h.
template<class Real> Real Spark::Tangent (Real fValue)
Definition at line 325 of file SpMaths.h.
template<class Real> Real Spark::Turbulence (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 238 of file SpProcedural.cpp.
References Abs(), and GradientNoise().
template<class Real> Real Spark::ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4] = CatmullRomBasis)
Definition at line 111 of file SpProcedural.cpp.
References Lattice(), and Spline().
template<class Real> Real Spark::VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real & rfOX, Real & rfOY, Real & rfOZ)
Definition at line 625 of file SpProcedural.cpp.
References CellNoise(), Floor(), and Sqrt().