SpGlutWindow.cpp File Reference
#include `SpWindow.h`
#include `SpGlHeaders.h`
#include `SpGlutKeyBindings.h`
#include `SpGlutHeaders.h`
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 272 of file SpGlutWindow.cpp.
References Spark::SpWindow::current(), Spark::SpWindow::height(), Spark::SpWindow::id(), Spark::SpWindow::onInitialize(), Spark::SpWindow::onStartup(), Spark::SpWindow::setWindowId(), Spark::SpWindow::title(), and Spark::SpWindow::width().