SpMaths.h File Reference
#include <cmath>
#include `SpMaths.inc`
Namespaces
namespace Spark
Classes
class Spark::SpMaths< Real >
Static utility class for mathematical constants.
Defines
#define INFINITY FLT_MAX
Functions
template<class Real> Real Erfc (Real fX)
template<class Real> Real LogGamma (Real fX)
template<class Real> Real Radians (Real fDeg)
template<class Real> Real Degrees (Real fRad)
template<class Real> Real Abs (Real fValue)
template<class Real> Real Ceil (Real fValue)
template<class Real> Real Clamp (Real fV, Real fMin, Real fMax)
template<class Real> Real Exp (Real fValue)
template<class Real> Real Floor (Real fValue)
template<class Real> Real InvSqrt (Real fValue)
template<class Real> Real Log (Real fValue)
template<class Real> Real Pow (Real fBase, Real fExponent)
template<class Real> Real Cub (Real fValue)
template<class Real> Real Square (Real fValue)
template<class Real> Real Sqr (Real fValue)
template<class Real> Real Sqrt (Real fValue)
template<class Real> Real Sign (Real fValue)
template<class Real> Real Gamma (Real fX)
template<class Real> Real Gaussian (Real fX, Real fStdDev)
template<class Real> Real Min (Real fX, Real fA)
template<class Real> Real Max (Real fX, Real fA)
template<class Real> Real Mod (Real fX, Real fA)
template<class Real> Real Frac (const Real fX)
template<class Real> Real Step (Real fX, Real fA)
template<class Real> Real Erf (Real fX)
template<class Real> Real ArcCosine (Real fValue)
template<class Real> Real ArcSine (Real fValue)
template<class Real> Real ArcTangent (Real fValue)
template<class Real> Real ArcTangent (Real fY, Real fX)
template<class Real> Real Cosine (Real fValue)
template<class Real> Real Sine (Real fValue)
template<class Real> Real Tangent (Real fValue)
bool IsPowerOfTwo (int iWidth, int iHeight)
Define Documentation
#define INFINITY FLT_MAX
Definition at line 30 of file SpMaths.h.
Function Documentation
template<class Real> Real Spark::Abs (Real fValue)
Definition at line 164 of file SpMaths.h.
Referenced by Spark::RidgedMultiFractal(), and Spark::Turbulence().
template<class Real> Real Spark::ArcCosine (Real fValue)
Definition at line 275 of file SpMaths.h.
template<class Real> Real Spark::ArcSine (Real fValue)
Definition at line 290 of file SpMaths.h.
template<class Real> Real Spark::ArcTangent (Real fY, Real fX)
Definition at line 310 of file SpMaths.h.
template<class Real> Real Spark::ArcTangent (Real fValue)
Definition at line 305 of file SpMaths.h.
template<class Real> Real Spark::Ceil (Real fValue)
Definition at line 169 of file SpMaths.h.
template<class Real> Real Spark::Clamp (Real fV, Real fMin, Real fMax)
Definition at line 174 of file SpMaths.h.
Referenced by Spark::RidgedMultiFractal(), and Spark::Spline().
template<class Real> Real Spark::Cosine (Real fValue)
Definition at line 315 of file SpMaths.h.
template<class Real> Real Spark::Cub (Real fValue)
Definition at line 204 of file SpMaths.h.
template<class Real> Real Degrees (Real fRad)
Definition at line 69 of file SpMaths.h.
template<class Real> Real Spark::Erf (Real fX)
Definition at line 270 of file SpMaths.h.
template<class Real> Real Erfc (Real fX)
template<class Real> Real Spark::Exp (Real fValue)
Definition at line 179 of file SpMaths.h.
template<class Real> Real Spark::Floor (Real fValue)
Definition at line 184 of file SpMaths.h.
Referenced by Spark::CellNoise(), Spark::GradientNoise(), and Spark::VoronoiNoise().
template<class Real> Real Spark::Frac (const Real fX)
Definition at line 265 of file SpMaths.h.
template<class Real> Real Spark::Gamma (Real fX)
Definition at line 235 of file SpMaths.h.
template<class Real> Real Spark::Gaussian (Real fX, Real fStdDev)
Definition at line 240 of file SpMaths.h.
template<class Real> Real Spark::InvSqrt (Real fValue)
Definition at line 189 of file SpMaths.h.
bool Spark::IsPowerOfTwo (int iWidth, int iHeight) [inline]
Definition at line 330 of file SpMaths.h.
template<class Real> Real Spark::Log (Real fValue)
Definition at line 194 of file SpMaths.h.
template<class Real> Real LogGamma (Real fX)
template<class Real> Real Spark::Max (Real fX, Real fA)
Definition at line 260 of file SpMaths.h.
template<class Real> Real Spark::Min (Real fX, Real fA)
Definition at line 255 of file SpMaths.h.
template<class Real> Real Spark::Mod (Real fX, Real fA)
Definition at line 245 of file SpMaths.h.
template<class Real> Real Spark::Pow (Real fBase, Real fExponent)
Definition at line 199 of file SpMaths.h.
Referenced by Spark::SpTurbulenceOp::initialize().
template<class Real> Real Radians (Real fDeg)
Definition at line 66 of file SpMaths.h.
template<class Real> Real Spark::Sign (Real fValue)
Definition at line 224 of file SpMaths.h.
template<class Real> Real Spark::Sine (Real fValue)
Definition at line 320 of file SpMaths.h.
template<class Real> Real Spark::Sqr (Real fValue)
Definition at line 214 of file SpMaths.h.
template<class Real> Real Spark::Sqrt (Real fValue)
Definition at line 219 of file SpMaths.h.
Referenced by Spark::Quadric(), and Spark::VoronoiNoise().
template<class Real> Real Spark::Square (Real fValue)
Definition at line 209 of file SpMaths.h.
template<class Real> Real Spark::Step (Real fX, Real fA)
Definition at line 306 of file SpProcedural.h.
template<class Real> Real Spark::Tangent (Real fValue)
Definition at line 325 of file SpMaths.h.