SpProcedural.h File Reference
#include `SpRandom.h`
#include `SpMaths.h`
#include `SpProcedural.inc`
Namespaces
namespace Spark
Functions
template<class Real> Real Quadric (Real fA, Real fB, Real fC)
template<class Real> Real Spline (Real fX, unsigned int uiKnots, Real *apkKnots, const Real afB[4][4]=CatmullRomBasis)
template<class Real> Real CellNoise (Real fX, Real fY, Real fZ)
template<class Real> Real GradientNoise (Real fX, Real fY, Real fZ)
template<class Real> Real ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4]=CatmullRomBasis)
template<class Real> Real FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real Turbulence (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.25f, Real fLacunarity=2.0345f, Real fOffset=0.7f, Real fGain=1.0f, Real fOctaves=4.0f)
template<class Real> Real RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.9f, Real fLacunarity=2.0345f, Real fThreshold=0.5f, Real fOffset=1.0f, Real fOctaves=4.0f)
template<class Real> Real FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
template<class Real> Real VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real &rfOX, Real &rfOY, Real &rfOZ)
template<class Real> Real DefaultTurbulence (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultFBM (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultMonoFractal (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultMultiFractal (Real fX, Real fY, Real fZ)
template<class Real> Real DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ)
template<class Real> Real fBm (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
int p (int iX)
float r (int iX)
template<class Real> int Hash (int iX, int iY, int iZ)
template<class Real> Real Lattice (int iX, int iY, int iZ)
template<class Real> Real Gradient (int iX, int iY, int iZ, Real fX, Real fY, Real fZ)
template<class Real> Real Bias (Real fX, Real fA)
template<class Real> Real Gain (Real fX, Real fA)
template<class Real> Real Cubic (Real fT)
template<class Real> Real Quintic (Real fT)
template<class Real> Real Lerp (Real fT, Real fA, Real fB)
template<class Real> Real BoxStep (Real fX, Real fA, Real fB)
template<class Real> Real SmoothStep (Real fA, Real fB, Real fX)
template<class Real> Real Pulse (Real fX, Real fA, Real fB)
template<class Real> Real BoxPulse (Real fX, Real fA, Real fB)
template<class Real> Real SmoothPulse (Real fX, Real fA, Real fB)
template<class Real> Real FilteredAbs (Real fX, Real fDX)
template<class Real> Real CatmullRomNoise (Real fX, Real fY, Real fZ)
template<class Real> Real HermiteNoise (Real fX, Real fY, Real fZ)
template<class Real> Real CardinalNoise (Real fX, Real fY, Real fZ)
template<class Real> Real BSplineNoise (Real fX, Real fY, Real fZ)
template<class Real> Real FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth)
Function Documentation
template<class Real> Real Spark::Bias (Real fX, Real fA)
Definition at line 261 of file SpProcedural.h.
template<class Real> Real Spark::BoxPulse (Real fX, Real fA, Real fB)
Definition at line 337 of file SpProcedural.h.
template<class Real> Real Spark::BoxStep (Real fX, Real fA, Real fB)
Definition at line 311 of file SpProcedural.h.
template<class Real> Real Spark::BSplineNoise (Real fX, Real fY, Real fZ)
Definition at line 362 of file SpProcedural.h.
template<class Real> Real Spark::CardinalNoise (Real fX, Real fY, Real fZ)
Definition at line 357 of file SpProcedural.h.
template<class Real> Real Spark::CatmullRomNoise (Real fX, Real fY, Real fZ)
Definition at line 347 of file SpProcedural.h.
template<class Real> Real Spark::CellNoise (Real fX, Real fY, Real fZ)
Definition at line 51 of file SpProcedural.cpp.
References Spark::Floor(), Spark::Hash(), and Spark::r().
Referenced by Spark::VoronoiNoise().
template<class Real> Real Spark::Cubic (Real fT)
Definition at line 291 of file SpProcedural.h.
Referenced by Spark::GradientNoise().
template<class Real> Real Spark::DefaultFBM (Real fX, Real fY, Real fZ)
Definition at line 395 of file SpProcedural.h.
template<class Real> Real Spark::DefaultMonoFractal (Real fX, Real fY, Real fZ)
Definition at line 401 of file SpProcedural.h.
template<class Real> Real Spark::DefaultMultiFractal (Real fX, Real fY, Real fZ)
Definition at line 407 of file SpProcedural.h.
template<class Real> Real Spark::DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ)
Definition at line 413 of file SpProcedural.h.
template<class Real> Real Spark::DefaultTurbulence (Real fX, Real fY, Real fZ)
Definition at line 389 of file SpProcedural.h.
template<class Real> Real Spark::fBm (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 419 of file SpProcedural.h.
template<class Real> Real Spark::FilteredAbs (Real fX, Real fDX)
Definition at line 367 of file SpProcedural.h.
Referenced by Spark::FilteredTurbulence().
template<class Real> Real Spark::FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 188 of file SpProcedural.cpp.
References Spark::FilteredGradientNoise().
template<class Real> Real Spark::FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth)
Definition at line 382 of file SpProcedural.h.
Referenced by Spark::FilteredFBM(), and Spark::FilteredTurbulence().
template<class Real> Real Spark::FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 296 of file SpProcedural.cpp.
References Spark::FilteredAbs(), and Spark::FilteredGradientNoise().
template<class Real> Real Spark::FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 143 of file SpProcedural.cpp.
References Spark::GradientNoise().
template<class Real> Real Spark::Gain (Real fX, Real fA)
Definition at line 270 of file SpProcedural.h.
template<class Real> Real Spark::Gradient (int iX, int iY, int iZ, Real fX, Real fY, Real fZ)
Definition at line 241 of file SpProcedural.h.
Referenced by Spark::GradientNoise().
template<class Real> Real Spark::GradientNoise (Real fX, Real fY, Real fZ)
Definition at line 61 of file SpProcedural.cpp.
References Spark::Cubic(), Spark::Floor(), Spark::Gradient(), and Spark::Lerp().
Referenced by Spark::FractionalBrownianMotion(), Spark::HybridMultiFractal(), Spark::MonoFractal(), Spark::MultiFractal(), Spark::RidgedMultiFractal(), and Spark::Turbulence().
template<class Real> int Spark::Hash (int iX, int iY, int iZ)
Definition at line 231 of file SpProcedural.h.
Referenced by Spark::CellNoise().
template<class Real> Real Spark::HermiteNoise (Real fX, Real fY, Real fZ)
Definition at line 352 of file SpProcedural.h.
template<class Real> Real Spark::HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.25f, Real fLacunarity = 2.0345f, Real fOffset = 0.7f, Real fGain = 1.0f, Real fOctaves = 4.0f)
Definition at line 456 of file SpProcedural.cpp.
References Spark::GradientNoise().
template<class Real> Real Spark::Lattice (int iX, int iY, int iZ)
Definition at line 236 of file SpProcedural.h.
Referenced by Spark::ValueNoise().
template<class Real> Real Spark::Lerp (Real fT, Real fA, Real fB)
Definition at line 301 of file SpProcedural.h.
Referenced by Spark::GradientNoise().
template<class Real> Real Spark::MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 356 of file SpProcedural.cpp.
References Spark::GradientNoise().
template<class Real> Real Spark::MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 407 of file SpProcedural.cpp.
References Spark::GradientNoise().
int Spark::p (int iX) [inline]
Definition at line 225 of file SpProcedural.h.
template<class Real> Real Spark::Pulse (Real fX, Real fA, Real fB)
Definition at line 332 of file SpProcedural.h.
template<class Real> Real Spark::Quadric (Real fA, Real fB, Real fC)
Definition at line 598 of file SpProcedural.cpp.
References Spark::Sqrt().
template<class Real> Real Spark::Quintic (Real fT)
Definition at line 296 of file SpProcedural.h.
float Spark::r (int iX) [inline]
Definition at line 219 of file SpProcedural.h.
Referenced by Spark::CellNoise().
template<class Real> Real Spark::RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.9f, Real fLacunarity = 2.0345f, Real fThreshold = 0.5f, Real fOffset = 1.0f, Real fOctaves = 4.0f)
Definition at line 527 of file SpProcedural.cpp.
References Spark::Abs(), Spark::Clamp(), and Spark::GradientNoise().
template<class Real> Real Spark::SmoothPulse (Real fX, Real fA, Real fB)
Definition at line 342 of file SpProcedural.h.
template<class Real> Real Spark::SmoothStep (Real fA, Real fB, Real fX)
Definition at line 316 of file SpProcedural.h.
template<class Real> Real Spark::Spline (Real fX, unsigned int uiKnots, Real * apkKnots, const Real afB[4][4] = CatmullRomBasis)
Definition at line 28 of file SpProcedural.cpp.
References Spark::Clamp().
Referenced by Spark::ValueNoise().
template<class Real> Real Spark::Turbulence (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 238 of file SpProcedural.cpp.
References Spark::Abs(), and Spark::GradientNoise().
template<class Real> Real Spark::ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4] = CatmullRomBasis)
Definition at line 111 of file SpProcedural.cpp.
References Spark::Lattice(), and Spark::Spline().
template<class Real> Real Spark::VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real & rfOX, Real & rfOY, Real & rfOZ)
Definition at line 625 of file SpProcedural.cpp.
References Spark::CellNoise(), Spark::Floor(), and Spark::Sqrt().