SpRandom.h File Reference
Namespaces
namespace Spark
Functions
void SeedRandom (unsigned long seed)
Initializes the random number table.
unsigned int RandomUInt (void)
Generates a random 32bit unsigned int.
float RandomUnitFloat (void)
Generates a random real number on [0,1]-real-interval.
float RandomUnitOpenFloat (void)
Generates a random real number on [0,1)-real-interval.
float RandomSymmetricFloat (void)
Generates a random real number on [-1,1].
float RandomIntervalFloat (float fMin, float fMax)
Generates a random real number on [-min, max].
Function Documentation
float RandomIntervalFloat (float fMin, float fMax) [inline]
Generates a random real number on [-min, max].
Definition at line 88 of file SpRandom.h.
References Spark::RandomUnitFloat().
float RandomSymmetricFloat (void) [inline]
Generates a random real number on [-1,1].
Definition at line 80 of file SpRandom.h.
References Spark::RandomUnitFloat().
Referenced by Spark::SpVertexNoiseSb::initialize().
unsigned int Spark::RandomUInt (void)
Generates a random 32bit unsigned int.
Definition at line 70 of file SpRandom.cpp.
References LOWER_MASK, M, MATRIX_A, N, Spark::SeedRandom(), and UPPER_MASK.
Referenced by Spark::SpVertexNoiseSb::initialize(), Spark::RandomUnitFloat(), and Spark::RandomUnitOpenFloat().
float Spark::RandomUnitFloat (void)
Generates a random real number on [0,1]-real-interval.
Definition at line 112 of file SpRandom.cpp.
References Spark::RandomUInt().
Referenced by Spark::RandomIntervalFloat(), and Spark::RandomSymmetricFloat().
float Spark::RandomUnitOpenFloat (void)
Generates a random real number on [0,1)-real-interval.
Definition at line 119 of file SpRandom.cpp.
References Spark::RandomUInt().
void Spark::SeedRandom (unsigned long seed)
Initializes the random number table.
Definition at line 51 of file SpRandom.cpp.
References N.
Referenced by Spark::SpVertexNoiseSb::initialize(), and Spark::RandomUInt().