dg::Matrix Class Reference
#include <Matrix.h>
Public Methods
Matrix ()
Matrix (Real fV00, Real fV01, Real fV02, Real fV03, Real fV10, Real fV11, Real fV12, Real fV13, Real fV20, Real fV21, Real fV22, Real fV23, Real fV30, Real fV31, Real fV32, Real fV33)
Matrix (const Real afV[4][4])
Matrix::Matrix (Real afV[16])
Matrix (const Vector &rkW, const Vector &rkV, const Vector &rkU)
operator Real ** ()
const Real * values () const
Real * values ()
void setValues (const Real **afV)
void setValues (const Real afV[16])
void setBase (const Vector &rkW, const Vector &rkV, const Vector &rkU)
void getBase (Vector &rkW, Vector &rkV, Vector &rkU) const
void getRow (UInt uiRow, Vector &rkV) const
void getColumn (UInt uiCol, Vector &rkV) const
void getTranspose (Matrix &rkM) const
Matrix operator+ (const Matrix &rkM) const
Matrix operator- (const Matrix &rkM) const
Matrix operator * (const Matrix &rkM) const
Matrix operator * (Real fScalar) const
Matrix operator/ (Real fScalar) const
Matrix operator- () const
Matrix & operator+= (const Matrix &rkM)
Matrix & operator-= (const Matrix &rkM)
Matrix & operator *= (const Matrix &rkM)
Matrix & operator *= (Real fScalar)
Matrix & operator/= (Real fScalar)
Vector operator * (const Vector &rkV) const
void transpose ()
void identity ()
void zero ()
Matrix inverse () const
Static Public Methods
Matrix buildIdentity ()
Matrix buildScale (const Vector &rkS)
Matrix buildRotation (Real fA, Vector &rkDir)
Matrix buildRotation (Real fX, Real fY, Real fZ)
Matrix buildRotation (const Vector &rkFrom, const Vector &rkTo)
Matrix buildRotation (const Vector &rkA)
Matrix buildRotation (Real dA, UInt eAxis)
Matrix buildTranslation (const Vector &rkT)
Matrix buildTransform (const Vector &rkT, const Matrix &rkR, const Vector &rkS)
Matrix fromAxisToAngle (const Vector &rkAxis, const Real dAngle)
Static Public Attributes
const Matrix ZERO
const Matrix IDENTITY
Constructor & Destructor Documentation
Matrix::Matrix ()
Definition at line 26 of file Matrix.cpp.
Referenced by inverse().
Matrix::Matrix (Real fV00, Real fV01, Real fV02, Real fV03, Real fV10, Real fV11, Real fV12, Real fV13, Real fV20, Real fV21, Real fV22, Real fV23, Real fV30, Real fV31, Real fV32, Real fV33)
Definition at line 55 of file Matrix.cpp.
References dg::Real.
Matrix::Matrix (const Real afV[4][4])
Definition at line 79 of file Matrix.cpp.
References dg::Real.
Matrix::Matrix (const Vector & rkW, const Vector & rkV, const Vector & rkU)
Definition at line 99 of file Matrix.cpp.
References dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Member Function Documentation
Matrix Matrix::buildIdentity () [static]
Definition at line 474 of file Matrix.cpp.
Matrix Matrix::buildRotation (Real dA, UInt eAxis) [static]
Definition at line 558 of file Matrix.cpp.
References dg::Cosine(), m_afV, dg::Radians(), dg::Real, dg::Sine(), and dg::UInt.
Matrix Matrix::buildRotation (const Vector & rkA) [static]
Definition at line 511 of file Matrix.cpp.
References buildRotation(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::buildRotation (const Vector & rkFrom, const Vector & rkTo) [static]
Definition at line 402 of file Matrix.cpp.
References dg::Abs(), dg::ArcCosine(), buildRotation(), dg::Vector::cross(), dg::Vector::dot(), dg::Vector::normalize(), dg::Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::buildRotation (Real fX, Real fY, Real fZ) [static]
Definition at line 502 of file Matrix.cpp.
References buildRotation(), and dg::Real.
Matrix Matrix::buildRotation (Real fA, Vector & rkDir) [static]
Definition at line 520 of file Matrix.cpp.
References dg::Cosine(), m_afV, dg::Vector::normalize(), dg::Radians(), dg::Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by buildRotation().
Matrix Matrix::buildScale (const Vector & rkS) [static]
Definition at line 484 of file Matrix.cpp.
References m_afV, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::buildTransform (const Vector & rkT, const Matrix & rkR, const Vector & rkS) [static]
Definition at line 460 of file Matrix.cpp.
References m_afV, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::buildTranslation (const Vector & rkT) [static]
Definition at line 493 of file Matrix.cpp.
References m_afV, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::fromAxisToAngle (const Vector & rkAxis, const Real dAngle) [static]
Definition at line 684 of file Matrix.cpp.
References dg::Cosine(), m_afV, dg::Radians(), dg::Real, dg::Sine(), dg::Sqr(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
void dg::Matrix::getBase (Vector & rkW, Vector & rkV, Vector & rkU) const [inline]
Definition at line 193 of file Matrix.h.
void Matrix::getColumn (UInt uiCol, Vector & rkV) const
Definition at line 140 of file Matrix.cpp.
References dg::UInt.
void Matrix::getRow (UInt uiRow, Vector & rkV) const
Definition at line 132 of file Matrix.cpp.
References dg::UInt.
void Matrix::getTranspose (Matrix & rkM) const
Definition at line 148 of file Matrix.cpp.
References m_afV, and dg::UInt.
void dg::Matrix::identity () [inline]
Definition at line 133 of file Matrix.h.
Matrix Matrix::inverse ()
Definition at line 162 of file Matrix.cpp.
References dg::Abs(), dg::Int, Matrix(), dg::Real, and dg::UInt.
dg::Matrix::Matrix::Matrix (Real afV[16])
Vector Matrix::operator * (const Vector & rkV) const
Definition at line 380 of file Matrix.cpp.
References dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Matrix Matrix::operator * (Real fScalar) const
Definition at line 342 of file Matrix.cpp.
References m_afV, dg::Real, and dg::UInt.
Matrix Matrix::operator * (const Matrix & rkM) const
Definition at line 295 of file Matrix.cpp.
References m_afV, and dg::UInt.
Matrix& dg::Matrix::operator *= (Real fScalar)
Matrix & Matrix::operator *= (const Matrix & rkM)
Definition at line 246 of file Matrix.cpp.
References m_afV, and dg::UInt.
dg::Matrix::operator Real ** () [inline]
Definition at line 50 of file Matrix.h.
References dg::Real.
Matrix Matrix::operator+ (const Matrix & rkM) const
Definition at line 265 of file Matrix.cpp.
References m_afV, and dg::UInt.
Matrix & Matrix::operator+= (const Matrix & rkM)
Definition at line 316 of file Matrix.cpp.
References m_afV, and dg::UInt.
Matrix dg::Matrix::operator- ()
Matrix Matrix::operator- (const Matrix & rkM) const
Definition at line 280 of file Matrix.cpp.
References m_afV, and dg::UInt.
Matrix & Matrix::operator-= (const Matrix & rkM)
Definition at line 329 of file Matrix.cpp.
References m_afV, and dg::UInt.
Matrix Matrix::operator/ (Real fScalar) const
Definition at line 354 of file Matrix.cpp.
References m_afV, dg::Real, and dg::UInt.
Matrix& dg::Matrix::operator/= (Real fScalar)
void dg::Matrix::setBase (const Vector & rkW, const Vector & rkV, const Vector & rkU) [inline]
Definition at line 182 of file Matrix.h.
void dg::Matrix::setValues (const Real afV[16]) [inline]
Definition at line 162 of file Matrix.h.
void dg::Matrix::setValues (const Real ** afV) [inline]
Definition at line 142 of file Matrix.h.
void Matrix::transpose ()
Definition at line 155 of file Matrix.cpp.
References dg::UInt.
Real * dg::Matrix::values () [inline]
Definition at line 128 of file Matrix.h.
const Real * dg::Matrix::values () [inline]
Definition at line 123 of file Matrix.h.
void dg::Matrix::zero () [inline]
Definition at line 200 of file Matrix.h.
Member Data Documentation
const Matrix Matrix::IDENTITY [static]
Initial value:
    Matrix(
        1.0f, 0.0f, 0.0f, 0.0f,
        0.0f, 1.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 1.0f, 0.0f,
        0.0f, 0.0f, 0.0f, 1.0f
    )
Definition at line 742 of file Matrix.cpp.
const Matrix Matrix::ZERO [static]
Initial value:
    Matrix(
        0.0f, 0.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 0.0f, 0.0f
    )
Definition at line 734 of file Matrix.cpp.
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp