dg::Vector Class Reference
#include <Vector.h>
Detailed Description
Vector (p.) - Generic 3D mathematical Vector (p.) class.
Definition at line 25 of file Vector.h.
Public Methods
Vector (Real x=0.0f, Real y=0.0f, Real z=0.0f)
Vector (const Vector &rkV)
Real x () const
Real y () const
Real z () const
Real & x ()
Real & y ()
Real & z ()
operator const Real * () const
operator Real * ()
const Real * values () const
const Vector & value () const
Real operator[] (int i) const
Real & operator[] (int i)
Vector operator+ (const Vector &rkVector) const
void operator+= (const Vector &rkVector)
void operator++ (void)
Vector operator- () const
Vector operator- (const Vector &rkVector) const
void operator-= (const Vector &rkVector)
void operator-- (void)
Vector operator * (const Vector &rkVector) const
void operator *= (const Vector &rkVector)
Vector operator * (const int scalar) const
void operator *= (const int scalar)
Vector operator * (const Real scalar) const
void operator *= (const Real scalar)
void operator= (const Vector &rkVector)
bool operator== (const Vector &rkVector) const
bool operator!= (const Vector &Value) const
void zero ()
void negate ()
Real length () const
Real lengthSquared () const
void normalize ()
Real dot (const Vector &rkVector) const
Vector cross (const Vector &rkVector) const
void cross (const Vector &rkLHS, const Vector &rkRHS)
Real angle (const Vector rkVector) const
Static Public Attributes
const Vector ZERO = Vector(0.0f, 0.0f, 0.0f)
Constructor & Destructor Documentation
Vector::Vector (Real x = 0.0f, Real y = 0.0f, Real z = 0.0f)
Definition at line 24 of file Vector.cpp.
References dg::Real, x(), y(), and z().
Referenced by cross(), operator *(), operator+(), and operator-().
Vector::Vector (const Vector & rkV)
Definition at line 31 of file Vector.cpp.
References x(), y(), and z().
Member Function Documentation
Real Vector::angle (const Vector rkVector) const
Definition at line 205 of file Vector.cpp.
References dot(), length(), and dg::Real.
void Vector::cross (const Vector & rkLHS, const Vector & rkRHS)
Definition at line 198 of file Vector.cpp.
References x(), y(), and z().
Vector Vector::cross (const Vector & rkVector) const
Definition at line 190 of file Vector.cpp.
References Vector(), x(), y(), and z().
Referenced by dg::Matrix::buildRotation().
Real Vector::dot (const Vector & rkVector) const
Definition at line 182 of file Vector.cpp.
References m_adC, and dg::Real.
Referenced by angle(), and dg::Matrix::buildRotation().
Real Vector::length ()
Definition at line 158 of file Vector.cpp.
References dg::Real, x(), y(), and z().
Referenced by angle(), and dg::Visualizer::setupCamera().
Real Vector::lengthSquared ()
Definition at line 163 of file Vector.cpp.
References dg::Real, x(), y(), and z().
Referenced by dg::Normalize().
void Vector::negate ()
Definition at line 138 of file Vector.cpp.
void Vector::normalize ()
Definition at line 168 of file Vector.cpp.
References dg::Real, x(), y(), and z().
Referenced by dg::Matrix::buildRotation(), dg::Polygonizer::getNormal(), and dg::Camera::getRayDir().
Vector Vector::operator * (const Real scalar) const
Definition at line 114 of file Vector.cpp.
References dg::Real, and Vector().
Vector Vector::operator * (const int scalar) const
Definition at line 102 of file Vector.cpp.
References Vector().
Vector Vector::operator * (const Vector & rkVector) const
Definition at line 87 of file Vector.cpp.
References m_adC, and Vector().
void Vector::operator *= (const Real scalar)
Definition at line 119 of file Vector.cpp.
References dg::Real.
void Vector::operator *= (const int scalar)
Definition at line 107 of file Vector.cpp.
void Vector::operator *= (const Vector & rkVector)
Definition at line 95 of file Vector.cpp.
References m_adC.
dg::Vector::operator const Real * () [inline]
Definition at line 127 of file Vector.h.
dg::Vector::operator Real * () [inline]
Definition at line 132 of file Vector.h.
bool Vector::operator!= (const Vector & Value) const
Definition at line 153 of file Vector.cpp.
Vector Vector::operator+ (const Vector & rkVector) const
Definition at line 38 of file Vector.cpp.
References m_adC, and Vector().
void Vector::operator++ (void)
Definition at line 53 of file Vector.cpp.
void Vector::operator+= (const Vector & rkVector)
Definition at line 46 of file Vector.cpp.
References m_adC.
Vector Vector::operator- (const Vector & rkVector) const
Definition at line 65 of file Vector.cpp.
References m_adC, and Vector().
Vector Vector::operator- ()
Definition at line 60 of file Vector.cpp.
References Vector().
void Vector::operator-- (void)
Definition at line 80 of file Vector.cpp.
void Vector::operator-= (const Vector & rkVector)
Definition at line 73 of file Vector.cpp.
References m_adC.
void Vector::operator= (const Vector & rkVector)
Definition at line 126 of file Vector.cpp.
References m_adC.
bool Vector::operator== (const Vector & rkVector) const
Definition at line 145 of file Vector.cpp.
References m_adC.
Real & dg::Vector::operator[] (int i) [inline]
Definition at line 152 of file Vector.h.
Real dg::Vector::operator[] (int i) const [inline]
Definition at line 147 of file Vector.h.
const Vector & dg::Vector::value () [inline]
Definition at line 142 of file Vector.h.
const Real * dg::Vector::values () [inline]
Definition at line 137 of file Vector.h.
Real & dg::Vector::x () [inline]
Definition at line 112 of file Vector.h.
Real dg::Vector::x () [inline]
Definition at line 97 of file Vector.h.
References dg::Real.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::buildScale(), dg::Matrix::buildTransform(), dg::Matrix::buildTranslation(), dg::Cross(), cross(), dg::Dot(), dg::Visualizer::drawPolygons(), dg::Matrix::fromAxisToAngle(), dg::Polygonizer::getNormal(), dg::Camera::getRayDir(), length(), lengthSquared(), dg::Polygonizer::marchCube(), dg::Polygonizer::marchTetra(), dg::Polygonizer::marchTetraCube(), dg::Matrix::Matrix(), dg::Max(), dg::Min(), dg::Normalize(), normalize(), dg::operator *(), dg::Matrix::operator *(), dg::Camera::setup(), and Vector().
Real & dg::Vector::y () [inline]
Definition at line 117 of file Vector.h.
Real dg::Vector::y () [inline]
Definition at line 102 of file Vector.h.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::buildScale(), dg::Matrix::buildTransform(), dg::Matrix::buildTranslation(), dg::Cross(), cross(), dg::Dot(), dg::Visualizer::drawPolygons(), dg::Matrix::fromAxisToAngle(), dg::Polygonizer::getNormal(), dg::Camera::getRayDir(), length(), lengthSquared(), dg::Polygonizer::marchCube(), dg::Polygonizer::marchTetra(), dg::Polygonizer::marchTetraCube(), dg::Matrix::Matrix(), dg::Max(), dg::Min(), dg::Normalize(), normalize(), dg::operator *(), dg::Matrix::operator *(), dg::Camera::setup(), and Vector().
Real & dg::Vector::z () [inline]
Definition at line 122 of file Vector.h.
Real dg::Vector::z () [inline]
Definition at line 107 of file Vector.h.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::buildScale(), dg::Matrix::buildTransform(), dg::Matrix::buildTranslation(), dg::Cross(), cross(), dg::Dot(), dg::Visualizer::drawPolygons(), dg::Matrix::fromAxisToAngle(), dg::Polygonizer::getNormal(), dg::Camera::getRayDir(), length(), lengthSquared(), dg::Polygonizer::marchCube(), dg::Polygonizer::marchTetra(), dg::Polygonizer::marchTetraCube(), dg::Matrix::Matrix(), dg::Max(), dg::Min(), dg::Normalize(), normalize(), dg::operator *(), dg::Matrix::operator *(), dg::Camera::setup(), and Vector().
void Vector::zero ()
Definition at line 133 of file Vector.cpp.
Member Data Documentation
const Vector Vector::ZERO = Vector(0.0f, 0.0f, 0.0f) [static]
Definition at line 283 of file Vector.cpp.
The documentation for this class was generated from the following files:
Vector.h
Vector.cpp