dg::Camera Class Reference
#include <Camera.h>
Public Methods
Camera (const Vector &rkPos=Vector(0.0f, 0.0f, 0.0f), const Vector &rkDir=Vector(0.0f, 0.0f, 1.0f), const Vector &rkUp=Vector(0.0f, 1.0f, 0.0f), const Vector &rkRight=Vector(1.0f, 0.0f, 0.0f), Real fNear=0.1f, Real fFar=10.0f, Real fHalfWidth=0.5f, Real fHalfHeight=0.5f, Image *pkImage=NULL)
~Camera ()
void setup ()
Vector getPosition () const
void setPosition (const Vector &rkPosition)
Vector getDirection () const
void setDirection (const Vector &rkDirection)
Vector getUp () const
void setUp (const Vector &rkUp)
Vector getRight () const
void setRight (const Vector &rkRight)
void setNear (Real fNear)
Real getNear () const
void setFar (Real fFar)
Real getFar () const
void setHalfWidth (Real fHalfWidth)
Real getHalfWidth () const
void setHorizontalFov (Real fHorizFov)
Real getHorizontalFov () const
void setHalfHeight (Real fHalfHeight)
Real getHalfHeight () const
void setVerticalFov (Real fVertFov)
Real getVerticalFov () const
void setBackground (const Color &rkColor)
Color getBackground () const
Vector getRayDir (UInt uiX, UInt uiY) const
Vector getStartRayDir () const
void setImage (Image *pkImage)
const Image * getImage () const
Image * getImage ()
UInt getImageWidth () const
UInt getImageHeight () const
UInt getImageChannels () const
Real getPixelWidth () const
Real getPixelHeight () const
Constructor & Destructor Documentation
Camera::Camera (const Vector & rkPos = Vector(0.0f, 0.0f, 0.0f), const Vector & rkDir = Vector(0.0f, 0.0f, 1.0f), const Vector & rkUp = Vector(0.0f, 1.0f, 0.0f), const Vector & rkRight = Vector(1.0f, 0.0f, 0.0f), Real fNear = 0.1f, Real fFar = 10.0f, Real fHalfWidth = 0.5f, Real fHalfHeight = 0.5f, Image * pkImage = NULL)
Definition at line 7 of file Camera.cpp.
References dg::Real.
Camera::~Camera ()
Definition at line 25 of file Camera.cpp.
Member Function Documentation
Color dg::Camera::getBackground () [inline]
Definition at line 257 of file Camera.h.
Vector dg::Camera::getDirection () [inline]
Definition at line 143 of file Camera.h.
Referenced by dg::Visualizer::drawPolygons(), dg::Visualizer::onStartup(), dg::RayTracer::render(), dg::Hypertexture::render(), dg::Visualizer::setupCamera(), and dg::Visualizer::setupRayTracer().
Real dg::Camera::getFar () [inline]
Definition at line 183 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
Real dg::Camera::getHalfHeight () [inline]
Definition at line 203 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
Real dg::Camera::getHalfWidth () [inline]
Definition at line 193 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
Real Camera::getHorizontalFov () [inline]
Definition at line 35 of file Camera.cpp.
References dg::ArcTangent(), dg::Degrees(), and dg::Real.
Image * dg::Camera::getImage () [inline]
Definition at line 247 of file Camera.h.
const Image * dg::Camera::getImage () [inline]
Definition at line 242 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
UInt dg::Camera::getImageChannels () [inline]
Definition at line 229 of file Camera.h.
UInt dg::Camera::getImageHeight () [inline]
Definition at line 221 of file Camera.h.
UInt dg::Camera::getImageWidth () [inline]
Definition at line 213 of file Camera.h.
Real dg::Camera::getNear () [inline]
Definition at line 173 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
Real dg::Camera::getPixelHeight () [inline]
Definition at line 272 of file Camera.h.
Real dg::Camera::getPixelWidth () [inline]
Definition at line 267 of file Camera.h.
Vector dg::Camera::getPosition () [inline]
Definition at line 133 of file Camera.h.
Referenced by dg::Visualizer::drawPolygons(), dg::RayTracer::render(), and dg::Visualizer::setupCamera().
Vector Camera::getRayDir (UInt uiX, UInt uiY) const
Definition at line 50 of file Camera.cpp.
References dg::Vector::normalize(), dg::UInt, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Vector dg::Camera::getRight () [inline]
Definition at line 163 of file Camera.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
Vector dg::Camera::getStartRayDir () [inline]
Definition at line 262 of file Camera.h.
Vector dg::Camera::getUp () [inline]
Definition at line 153 of file Camera.h.
Referenced by dg::Visualizer::drawPolygons(), dg::RayTracer::render(), dg::Hypertexture::render(), and dg::Visualizer::setupCamera().
Real Camera::getVerticalFov () [inline]
Definition at line 45 of file Camera.cpp.
References dg::ArcTangent(), dg::Degrees(), and dg::Real.
void dg::Camera::setBackground (const Color & rkColor) [inline]
Definition at line 252 of file Camera.h.
void dg::Camera::setDirection (const Vector & rkDirection) [inline]
Definition at line 148 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setFar (Real fFar) [inline]
Definition at line 188 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setHalfHeight (Real fHalfHeight) [inline]
Definition at line 208 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setHalfWidth (Real fHalfWidth) [inline]
Definition at line 198 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void Camera::setHorizontalFov (Real fHorizFov) [inline]
Definition at line 30 of file Camera.cpp.
References dg::Radians(), dg::Real, and dg::Tangent().
void dg::Camera::setImage (Image * pkImage) [inline]
Definition at line 237 of file Camera.h.
Referenced by dg::Visualizer::setupHypertexture(), and dg::Visualizer::setupRayTracer().
void dg::Camera::setNear (Real fNear) [inline]
Definition at line 178 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setPosition (const Vector & rkPosition) [inline]
Definition at line 138 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setRight (const Vector & rkRight) [inline]
Definition at line 168 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void dg::Camera::setUp (const Vector & rkUp) [inline]
Definition at line 158 of file Camera.h.
Referenced by dg::Visualizer::setupCamera().
void Camera::setup ()
Definition at line 96 of file Camera.cpp.
References dg::Image::height(), dg::Real, dg::Image::width(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
void Camera::setVerticalFov (Real fVertFov) [inline]
Definition at line 40 of file Camera.cpp.
References dg::Radians(), dg::Real, and dg::Tangent().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp