dg::Color Class Reference
#include <Color.h>
Public Methods
Color ()
Color (Real dR, Real dG, Real dB, Real dA=1.0)
Color (const Color &rkColor)
Real r () const
Real g () const
Real b () const
Real a () const
Real & r ()
Real & g ()
Real & b ()
Real & a ()
Real operator() (UInt uiC) const
Real operator[] (UInt uiC) const
Real & operator() (UInt uiC)
Real & operator[] (UInt uiC)
Real getComponent (UInt uiC) const
const Color & value ()
Real * values ()
void set (const Color &v)
void set (Real r, Real g, Real b, Real a=1.0)
void setRed (Real r)
void setGreen (Real g)
void setBlue (Real b)
void setAlpha (Real a)
void setComponent (Real n, UInt c)
void operator= (const Color &rkColor)
Bool operator== (const Color &rkColor) const
Bool operator!= (const Color &rkColor) const
Color operator+ (const Color &rkColor) const
void operator++ (void)
void operator+= (const Color &rkColor)
Color operator- () const
Color operator- (const Color &rkColor) const
void operator-- (void)
void operator-= (const Color &rkColor)
Color operator * (const Color &rkColor) const
void operator *= (const Color &rkColor)
Color operator * (const Int scalar) const
void operator *= (const Int scalar)
Color operator * (const Real scalar) const
void operator *= (const Real scalar)
void zero ()
void negate ()
Static Public Attributes
const Color BLACK = Color(0.0f, 0.0f, 0.0f)
const Color GRAY = Color(0.5f, 0.5f, 0.5f)
const Color WHITE = Color(1.0f, 1.0f, 1.0f)
Constructor & Destructor Documentation
Color::Color ()
Definition at line 20 of file Color.cpp.
Color::Color (Real dR, Real dG, Real dB, Real dA = 1.0)
Definition at line 28 of file Color.cpp.
References dg::Real.
Color::Color (const Color & rkColor)
Definition at line 36 of file Color.cpp.
References m_adC.
Member Function Documentation
Real & dg::Color::a () [inline]
Definition at line 134 of file Color.h.
Real dg::Color::a () [inline]
Definition at line 114 of file Color.h.
Referenced by dg::Window::drawString(), and dg::Visualizer::drawText().
Real & dg::Color::b () [inline]
Definition at line 129 of file Color.h.
Real dg::Color::b () [inline]
Definition at line 109 of file Color.h.
Referenced by dg::Clamp(), dg::Window::drawString(), dg::Visualizer::drawText(), and dg::operator *().
Real & dg::Color::g () [inline]
Definition at line 124 of file Color.h.
Real dg::Color::g () [inline]
Definition at line 104 of file Color.h.
Referenced by dg::Clamp(), dg::Window::drawString(), dg::Visualizer::drawText(), and dg::operator *().
Real dg::Color::getComponent (UInt uiC) const [inline]
Definition at line 171 of file Color.h.
void dg::Color::negate () [inline]
Definition at line 239 of file Color.h.
Color Color::operator * (const Real scalar) const
Definition at line 142 of file Color.cpp.
References dg::Real.
Color Color::operator * (const Int scalar) const
Definition at line 124 of file Color.cpp.
References dg::Int.
Color Color::operator * (const Color & rkColor) const
Definition at line 106 of file Color.cpp.
References m_adC.
void Color::operator *= (const Real scalar)
Definition at line 152 of file Color.cpp.
References dg::Real.
void Color::operator *= (const Int scalar)
Definition at line 134 of file Color.cpp.
References dg::Int.
void Color::operator *= (const Color & rkColor)
Definition at line 116 of file Color.cpp.
References m_adC.
Bool Color::operator!= (const Color & rkColor) const
Definition at line 178 of file Color.cpp.
References dg::Bool.
Real & dg::Color::operator() (UInt uiC) [inline]
Definition at line 163 of file Color.h.
Real dg::Color::operator() (UInt uiC) const [inline]
Definition at line 147 of file Color.h.
Color Color::operator+ (const Color & rkColor) const
Definition at line 44 of file Color.cpp.
References m_adC.
void Color::operator++ (void)
Definition at line 54 of file Color.cpp.
void Color::operator+= (const Color & rkColor)
Definition at line 62 of file Color.cpp.
References m_adC.
Color Color::operator- (const Color & rkColor) const
Definition at line 80 of file Color.cpp.
References m_adC.
Color Color::operator- ()
Definition at line 70 of file Color.cpp.
void Color::operator-- (void)
Definition at line 90 of file Color.cpp.
void Color::operator-= (const Color & rkColor)
Definition at line 98 of file Color.cpp.
References m_adC.
void Color::operator= (const Color & rkColor)
Definition at line 160 of file Color.cpp.
References m_adC.
Bool Color::operator== (const Color & rkColor) const
Definition at line 168 of file Color.cpp.
References dg::Bool, and m_adC.
Real & dg::Color::operator[] (UInt uiC) [inline]
Definition at line 155 of file Color.h.
Real dg::Color::operator[] (UInt uiC) const [inline]
Definition at line 139 of file Color.h.
Real & dg::Color::r () [inline]
Definition at line 119 of file Color.h.
Real dg::Color::r () [inline]
Definition at line 99 of file Color.h.
Referenced by dg::Clamp(), dg::Window::drawString(), dg::Visualizer::drawText(), and dg::operator *().
void dg::Color::set (Real r, Real g, Real b, Real a = 1.0) [inline]
Definition at line 197 of file Color.h.
void dg::Color::set (const Color & v) [inline]
Definition at line 189 of file Color.h.
void dg::Color::setAlpha (Real a) [inline]
Definition at line 220 of file Color.h.
void dg::Color::setBlue (Real b) [inline]
Definition at line 215 of file Color.h.
void dg::Color::setComponent (Real n, UInt c) [inline]
Definition at line 225 of file Color.h.
void dg::Color::setGreen (Real g) [inline]
Definition at line 210 of file Color.h.
void dg::Color::setRed (Real r) [inline]
Definition at line 205 of file Color.h.
const Color & dg::Color::value () [inline]
Definition at line 179 of file Color.h.
Real * dg::Color::values () [inline]
Definition at line 184 of file Color.h.
void dg::Color::zero () [inline]
Definition at line 231 of file Color.h.
Member Data Documentation
const Color Color::BLACK = Color(0.0f, 0.0f, 0.0f) [static]
Definition at line 201 of file Color.cpp.
const Color Color::GRAY = Color(0.5f, 0.5f, 0.5f) [static]
Definition at line 202 of file Color.cpp.
const Color Color::WHITE = Color(1.0f, 1.0f, 1.0f) [static]
Definition at line 203 of file Color.cpp.
The documentation for this class was generated from the following files:
Color.h
Color.cpp