dg::Hypertexture Class Reference
#include <Hypertexture.h>
Public Types
typedef Real(* DensityFn)(Real fX, Real fY, Real fZ)
typedef Real(* FilteredDensityFn)(Real fX, Real fY, Real fZ, Real fDT)
typedef Color(* ColorFn)(Real fX, Real fY, Real fZ)
typedef Color(* FilteredColorFn)(Real fX, Real fY, Real fZ, Real fDT)
typedef Color(* ShadeFn)(const Vector &rkSurfaceNormal, const Vector &rkViewDir, const Vector &rkLightDir, const Color &rkLightColor, const Color &rkBaseColor, Real fAmbient, Real fDiffuse, Real fSpecular, Real fRoughness)
Public Methods
Hypertexture::Hypertexture (DensityFn pvDensityFn=NULL, ColorFn pvColorFn=NULL, ShadeFn pvShadeFn=NULL, Camera *pkCamera=NULL)
~Hypertexture ()
void setDensityFunction (DensityFn pvDensityFn)
void setColorFunction (ColorFn pvColorFn)
void setShadingFunction (ShadeFn pvShadeFn)
void setFilteredDensityFunction (FilteredDensityFn pvDensityFn)
void setFilteredColorFunction (FilteredColorFn pvColorFn)
void setCamera (Camera *pkCamera)
const Camera * getCamera () const
Vector getLightDirection () const
void setLightDirection (const Vector &rkLight)
Color getLightColor () const
void setLightColor (const Color &rkLight)
void setScale (Real fScale)
Real getScale ()
Real getAmbient () const
void setAmbient (Real fAmbient)
Real getDiffuse () const
void setDiffuse (Real fDiffuse)
Real getSpecular () const
void setSpecular (Real fSpecular)
Real getRoughness () const
void setRoughness (Real fRoughness)
void setRayEpsilon (Real fEpsilon)
Real getRayEpsilon () const
Real getDensityScale () const
void setDensityScale (Real fDensityScale)
Real getDensityThreshold () const
void setDensityThreshold (Real fDensityThreshold)
Real getOpacityThreshold () const
void setOpacityThreshold (Real fOpacityThreshold)
Real getShadowFarClip () const
void setShadowFarClip (Real fShadowFarClip)
Real getShadowDepthThreshold () const
void setShadowDepthThreshold (Real fShadowDepthThreshold)
Real getShadowStepScale () const
void setShadowStepScale (Real fShadowStepScale)
Real getStepSize () const
void setStepSize (Real fStepSize)
void setMaxSamples (UInt uiMax)
UInt getMaxSamples () const
UInt getRayHits () const
UInt getSamples () const
void setBackground (const Color &rkColor)
Color getBackground () const
void setKeepInView (bool bKeepInView)
bool getKeepInView ()
void setFadeOut (bool bFadeOut)
bool getFadeOut ()
void render ()
void render (UInt uiStartLine, UInt uiEndLine)
Member Typedef Documentation
typedef Color(* dg::Hypertexture::ColorFn)(Real fX, Real fY, Real fZ)
Definition at line 22 of file Hypertexture.h.
typedef Real(* dg::Hypertexture::DensityFn)(Real fX, Real fY, Real fZ)
Definition at line 19 of file Hypertexture.h.
typedef Color(* dg::Hypertexture::FilteredColorFn)(Real fX, Real fY, Real fZ, Real fDT)
Definition at line 23 of file Hypertexture.h.
typedef Real(* dg::Hypertexture::FilteredDensityFn)(Real fX, Real fY, Real fZ, Real fDT)
Definition at line 20 of file Hypertexture.h.
typedef Color(* dg::Hypertexture::ShadeFn)(const Vector& rkSurfaceNormal, const Vector& rkViewDir, const Vector& rkLightDir, const Color& rkLightColor, const Color& rkBaseColor, Real fAmbient, Real fDiffuse, Real fSpecular, Real fRoughness)
Definition at line 25 of file Hypertexture.h.
Constructor & Destructor Documentation
Hypertexture::~Hypertexture ()
Definition at line 63 of file Hypertexture.cpp.
Member Function Documentation
Real dg::Hypertexture::getAmbient () [inline]
Definition at line 403 of file Hypertexture.h.
Color dg::Hypertexture::getBackground () [inline]
Definition at line 299 of file Hypertexture.h.
const Camera * dg::Hypertexture::getCamera () [inline]
Definition at line 309 of file Hypertexture.h.
Real dg::Hypertexture::getDensityScale () [inline]
Definition at line 254 of file Hypertexture.h.
Real dg::Hypertexture::getDensityThreshold () [inline]
Definition at line 264 of file Hypertexture.h.
Real dg::Hypertexture::getDiffuse () [inline]
Definition at line 413 of file Hypertexture.h.
bool dg::Hypertexture::getFadeOut () [inline]
Definition at line 458 of file Hypertexture.h.
bool dg::Hypertexture::getKeepInView () [inline]
Definition at line 448 of file Hypertexture.h.
Color dg::Hypertexture::getLightColor () [inline]
Definition at line 244 of file Hypertexture.h.
Vector dg::Hypertexture::getLightDirection () [inline]
Definition at line 234 of file Hypertexture.h.
UInt dg::Hypertexture::getMaxSamples () [inline]
Definition at line 343 of file Hypertexture.h.
Real dg::Hypertexture::getOpacityThreshold () [inline]
Definition at line 274 of file Hypertexture.h.
Real dg::Hypertexture::getRayEpsilon () [inline]
Definition at line 353 of file Hypertexture.h.
UInt dg::Hypertexture::getRayHits () [inline]
Definition at line 284 of file Hypertexture.h.
Referenced by dg::Visualizer::drawText().
Real dg::Hypertexture::getRoughness () [inline]
Definition at line 433 of file Hypertexture.h.
UInt dg::Hypertexture::getSamples () [inline]
Definition at line 289 of file Hypertexture.h.
Referenced by dg::Visualizer::drawText().
Real dg::Hypertexture::getScale () [inline]
Definition at line 468 of file Hypertexture.h.
Real dg::Hypertexture::getShadowDepthThreshold () [inline]
Definition at line 373 of file Hypertexture.h.
Real dg::Hypertexture::getShadowFarClip () [inline]
Definition at line 363 of file Hypertexture.h.
Real dg::Hypertexture::getShadowStepScale () [inline]
Definition at line 383 of file Hypertexture.h.
Real dg::Hypertexture::getSpecular () [inline]
Definition at line 423 of file Hypertexture.h.
Real dg::Hypertexture::getStepSize () [inline]
Definition at line 393 of file Hypertexture.h.
Referenced by dg::Visualizer::drawText().
dg::Hypertexture::Hypertexture::Hypertexture (DensityFn pvDensityFn = NULL, ColorFn pvColorFn = NULL, ShadeFn pvShadeFn = NULL, Camera * pkCamera = NULL)
void Hypertexture::render (UInt uiStartLine, UInt uiEndLine)
Definition at line 84 of file Hypertexture.cpp.
References dg::Camera::getDirection(), dg::Camera::getFar(), dg::Camera::getHalfHeight(), dg::Camera::getHalfWidth(), dg::Camera::getImage(), dg::Camera::getNear(), dg::Camera::getRight(), dg::Camera::getUp(), dg::Image::height(), dg::Normalize(), dg::Real, dg::Image::setColor(), dg::UInt, and dg::Image::width().
void Hypertexture::render ()
Definition at line 68 of file Hypertexture.cpp.
References dg::Camera::getImage(), and dg::Image::height().
Referenced by dg::Visualizer::drawHypertexture().
void dg::Hypertexture::setAmbient (Real fAmbient) [inline]
Definition at line 408 of file Hypertexture.h.
void dg::Hypertexture::setBackground (const Color & rkColor) [inline]
Definition at line 294 of file Hypertexture.h.
void dg::Hypertexture::setCamera (Camera * pkCamera) [inline]
Definition at line 304 of file Hypertexture.h.
Referenced by dg::Visualizer::onStartup().
void dg::Hypertexture::setColorFunction (ColorFn pvColorFn) [inline]
Definition at line 320 of file Hypertexture.h.
void dg::Hypertexture::setDensityFunction (DensityFn pvDensityFn) [inline]
Definition at line 314 of file Hypertexture.h.
Referenced by dg::Visualizer::onStartup(), and dg::Visualizer::setupHypertexture().
void dg::Hypertexture::setDensityScale (Real fDensityScale) [inline]
Definition at line 259 of file Hypertexture.h.
void dg::Hypertexture::setDensityThreshold (Real fDensityThreshold) [inline]
Definition at line 269 of file Hypertexture.h.
void dg::Hypertexture::setDiffuse (Real fDiffuse) [inline]
Definition at line 418 of file Hypertexture.h.
void dg::Hypertexture::setFadeOut (bool bFadeOut) [inline]
Definition at line 453 of file Hypertexture.h.
Referenced by dg::Visualizer::setupHypertexture().
void dg::Hypertexture::setFilteredColorFunction (FilteredColorFn pvColorFn) [inline]
Definition at line 337 of file Hypertexture.h.
Referenced by dg::Visualizer::setupHypertexture().
void dg::Hypertexture::setFilteredDensityFunction (FilteredDensityFn pvDensityFn) [inline]
Definition at line 331 of file Hypertexture.h.
void dg::Hypertexture::setKeepInView (bool bKeepInView) [inline]
Definition at line 443 of file Hypertexture.h.
Referenced by dg::Visualizer::setupHypertexture().
void dg::Hypertexture::setLightColor (const Color & rkLight) [inline]
Definition at line 249 of file Hypertexture.h.
void dg::Hypertexture::setLightDirection (const Vector & rkLight) [inline]
Definition at line 239 of file Hypertexture.h.
Referenced by dg::Visualizer::onStartup().
void dg::Hypertexture::setMaxSamples (UInt uiMax) [inline]
Definition at line 348 of file Hypertexture.h.
void dg::Hypertexture::setOpacityThreshold (Real fOpacityThreshold) [inline]
Definition at line 279 of file Hypertexture.h.
void dg::Hypertexture::setRayEpsilon (Real fEpsilon) [inline]
Definition at line 358 of file Hypertexture.h.
void dg::Hypertexture::setRoughness (Real fRoughness) [inline]
Definition at line 438 of file Hypertexture.h.
void dg::Hypertexture::setScale (Real fScale) [inline]
Definition at line 463 of file Hypertexture.h.
Referenced by dg::Visualizer::setupHypertexture().
void dg::Hypertexture::setShadingFunction (ShadeFn pvShadeFn) [inline]
Definition at line 326 of file Hypertexture.h.
void dg::Hypertexture::setShadowDepthThreshold (Real fShadowDepthThreshold) [inline]
Definition at line 378 of file Hypertexture.h.
void dg::Hypertexture::setShadowFarClip (Real fShadowFarClip) [inline]
Definition at line 368 of file Hypertexture.h.
void dg::Hypertexture::setShadowStepScale (Real fShadowStepScale) [inline]
Definition at line 388 of file Hypertexture.h.
void dg::Hypertexture::setSpecular (Real fSpecular) [inline]
Definition at line 428 of file Hypertexture.h.
void dg::Hypertexture::setStepSize (Real fStepSize) [inline]
Definition at line 398 of file Hypertexture.h.
Referenced by dg::Visualizer::setupHypertexture().
The documentation for this class was generated from the following files:
Hypertexture.h
Hypertexture.cpp