dg::Visualizer Class Reference
#include <Visualizer.h>
Public Types
enum VisualizerMode { VM_MARCHING_CUBES,
VM_MARCHING_TETRA,
VM_RAYTRACE,
VM_HYPERTEXTURE,
VM_COUNT
 }
Public Methods
Visualizer ()
virtual ~Visualizer ()
virtual Bool onStartup ()
virtual Bool onInitialize ()
virtual void onReshape (Int iWidth, Int iHeight)
virtual void onDisplay ()
virtual void onIdle ()
virtual void onKeyDown (UChar ucKey, Int iX, Int iY)
virtual void onSpecialKeyDown (Int iKey, Int iX, Int iY)
virtual void onMouseMotion (Int iX, Int iY, UInt uiModifiers)
virtual void onMouseClick (Int iButton, Int iState, Int iX, Int iY, UInt uiModifiers)
void drawText ()
void drawPolygons ()
void drawRaytraced ()
void drawHypertexture ()
Protected Methods
void setupPolygonizer ()
void setupRayTracer ()
void setupHypertexture ()
void setupCamera (Camera &rkCamera)
void setupFrustum (Int iWidth, Int iHeight, bool bPerspective)
void setBackground ()
void setLights ()
void setMaterials ()
void startCalcTimer ()
void updateCalcTimer ()
void stopCalcTimer ()
void update (Real fTime)
Protected Attributes
Real m_fLastCalcTime
UInt m_uiHours
UInt m_uiMinutes
UInt m_uiSeconds
UInt m_uiMilliSecs
bool m_bUsePerspective
bool m_bShowInfo
bool m_bUpdate
bool m_bRotate
bool m_bShowBounds
bool m_bSpin
bool m_bMove
bool m_bLight
bool m_bRendering
bool m_bRayTraced
bool m_bHyperTraced
bool m_bPolygonized
bool m_bKeepInView
bool m_bFadeOut
Int m_iSpinX
Int m_iSpinY
Int m_iOrigX
Int m_iOrigY
Int m_iCellCount
Real m_fScale
Real m_fIsoLevel
Real m_fUpdateOffset
Real m_fTime
Polygonizer::MarchMethod m_eMarchMode
Real m_fTransparency
Real m_fOffsetX
Real m_fOffsetY
Real m_fOffsetZ
Real m_fCameraX
Real m_fCameraY
Real m_fCameraZ
Real m_fFrustumLeft
Real m_fFrustumRight
Real m_fFrustumBottom
Real m_fFrustumTop
Real m_fFrustumNear
Real m_fFrustumFar
Int m_ePolyMode
Polygonizer m_kPolygonizer
Camera m_kPolyCam
RayTracer m_kRayTracer
Camera m_kRayTracerCam
Image m_kRayTracerImage
Hypertexture m_kHyper
Camera m_kHyperCam
Image m_kHyperImage
UInt m_uiFuncIndex
const char * m_aucFuncName
Operator m_pvFunction
VisualizerMode m_eVisMode
Static Protected Attributes
const Real ms_fCellToRayScale = 2
const Real ms_fCellToHyperStepScale = 0.4
Member Enumeration Documentation
enum dg::Visualizer::VisualizerMode
Enumeration values:
VM_MARCHING_CUBES
VM_MARCHING_TETRA
VM_RAYTRACE
VM_HYPERTEXTURE
VM_COUNT
Definition at line 22 of file Visualizer.h.
Constructor & Destructor Documentation
Visualizer::Visualizer ()
Definition at line 16 of file Visualizer.cpp.
Visualizer::~Visualizer () [virtual]
Definition at line 23 of file Visualizer.cpp.
Member Function Documentation
void Visualizer::drawHypertexture ()
Definition at line 210 of file Visualizer.cpp.
References dg::Window::drawImage(), drawText(), dg::Image::height(), m_bHyperTraced, m_bRendering, m_bUpdate, m_kHyper, m_kHyperImage, dg::Image::pixels(), dg::Window::postRedisplay(), dg::Hypertexture::render(), setBackground(), startCalcTimer(), stopCalcTimer(), dg::Window::swapBuffers(), dg::UInt, updateCalcTimer(), and dg::Image::width().
Referenced by onDisplay().
void Visualizer::drawPolygons ()
Definition at line 269 of file Visualizer.cpp.
References dg::Polygonizer::evaluate(), dg::Polygonizer::getColors(), dg::Camera::getDirection(), dg::Polygonizer::getNormals(), dg::Camera::getPosition(), dg::Camera::getUp(), dg::Polygonizer::getVertices(), m_bLight, m_bPolygonized, m_bUpdate, m_eMarchMode, m_kPolyCam, m_kPolygonizer, setupCamera(), startCalcTimer(), stopCalcTimer(), dg::UInt, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by onDisplay().
void Visualizer::drawRaytraced ()
Definition at line 151 of file Visualizer.cpp.
References dg::Window::drawImage(), drawText(), dg::Image::height(), m_bRayTraced, m_bRendering, m_bUpdate, m_kRayTracer, m_kRayTracerImage, dg::Image::pixels(), dg::Window::postRedisplay(), dg::RayTracer::render(), setBackground(), startCalcTimer(), stopCalcTimer(), dg::Window::swapBuffers(), dg::UInt, updateCalcTimer(), and dg::Image::width().
Referenced by onDisplay().
void Visualizer::drawText ()
Definition at line 336 of file Visualizer.cpp.
References dg::Color::a(), dg::Color::b(), dg::Char, dg::Window::drawString(), dg::Color::g(), dg::Hypertexture::getRayHits(), dg::RayTracer::getRayHits(), dg::Hypertexture::getSamples(), dg::Hypertexture::getStepSize(), dg::Polygonizer::getVertices(), dg::Window::height(), dg::Int, m_aucFuncName, m_eVisMode, m_fIsoLevel, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fScale, m_iCellCount, m_iSpinX, m_iSpinY, m_kHyper, m_kPolygonizer, m_kRayTracer, m_uiHours, m_uiMilliSecs, m_uiMinutes, m_uiSeconds, ms_fCellToRayScale, dg::Color::r(), dg::UInt, VM_HYPERTEXTURE, VM_MARCHING_CUBES, VM_MARCHING_TETRA, VM_RAYTRACE, and dg::Window::width().
Referenced by drawHypertexture(), drawRaytraced(), and onDisplay().
void Visualizer::onDisplay () [virtual]
Reimplemented from dg::Window (p.).
Definition at line 125 of file Visualizer.cpp.
References drawHypertexture(), drawPolygons(), drawRaytraced(), drawText(), m_bUpdate, m_eVisMode, m_fTime, dg::Window::swapBuffers(), update(), dg::Window::updateClicks(), VM_HYPERTEXTURE, VM_MARCHING_CUBES, VM_MARCHING_TETRA, and VM_RAYTRACE.
Referenced by onIdle().
virtual void dg::Visualizer::onIdle () [inline, virtual]
Reimplemented from dg::Window (p.).
Definition at line 41 of file Visualizer.h.
References onDisplay().
Bool Visualizer::onInitialize () [virtual]
Reimplemented from dg::Window (p.).
Definition at line 85 of file Visualizer.cpp.
References dg::Bool, dg::Window::height(), onReshape(), setBackground(), setLights(), setMaterials(), setupPolygonizer(), and dg::Window::width().
void Visualizer::onKeyDown (UChar ucKey, Int iX, Int iY) [virtual]
Reimplemented from dg::Window (p.).
Definition at line 504 of file Visualizer.cpp.
References dg::Window::height(), dg::Int, m_bFadeOut, m_bHyperTraced, m_bKeepInView, m_bLight, m_bMove, m_bPolygonized, m_bRayTraced, m_bShowBounds, m_bShowInfo, m_bUpdate, m_bUsePerspective, m_eMarchMode, m_ePolyMode, m_eVisMode, m_fCameraZ, m_fFrustumFar, m_fScale, m_fTransparency, m_iCellCount, m_kPolygonizer, m_uiFuncIndex, onReshape(), dg::RandomInt(), dg::Polygonizer::setCellCount(), setMaterials(), dg::Polygonizer::setScale(), setupHypertexture(), setupPolygonizer(), setupRayTracer(), dg::UChar, dg::UInt, VM_HYPERTEXTURE, VM_MARCHING_CUBES, VM_MARCHING_TETRA, VM_RAYTRACE, and dg::Window::width().
void Visualizer::onMouseClick (Int iButton, Int iState, Int iX, Int iY, UInt uiModifiers) [virtual]
Reimplemented from dg::Window (p.).
Definition at line 483 of file Visualizer.cpp.
References dg::Int, dg::Window::m_bLeftMousePressed, dg::Window::m_bMiddleMousePressed, dg::Window::m_bRightMousePressed, m_bRotate, m_eVisMode, m_iOrigX, m_iOrigY, dg::UInt, VM_HYPERTEXTURE, VM_MARCHING_TETRA, and VM_RAYTRACE.
void Visualizer::onMouseMotion (Int iX, Int iY, UInt uiModifiers) [virtual]
Reimplemented from dg::Window (p.).
Definition at line 471 of file Visualizer.cpp.
References dg::Int, m_iOrigX, m_iOrigY, m_iSpinX, m_iSpinY, and dg::UInt.
void Visualizer::onReshape (Int iWidth, Int iHeight) [virtual]
Reimplemented from dg::Window (p.).
Definition at line 98 of file Visualizer.cpp.
References dg::Int, m_bUsePerspective, m_fFrustumBottom, m_fFrustumFar, m_fFrustumLeft, m_fFrustumNear, m_fFrustumRight, m_fFrustumTop, and setupFrustum().
Referenced by onInitialize(), and onKeyDown().
void Visualizer::onSpecialKeyDown (Int iKey, Int iX, Int iY) [virtual]
Reimplemented from dg::Window (p.).
Definition at line 669 of file Visualizer.cpp.
References dg::Int, m_fIsoLevel, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_kPolygonizer, dg::Polygonizer::setIsoLevel(), dg::Polygonizer::setOffset(), and setupPolygonizer().
Bool Visualizer::onStartup () [virtual]
Reimplemented from dg::Window (p.).
Definition at line 28 of file Visualizer.cpp.
References dg::Bool, dg::Camera::getDirection(), m_aucFuncName, m_bFadeOut, m_bHyperTraced, m_bKeepInView, m_bLight, m_bMove, m_bPolygonized, m_bRayTraced, m_bRotate, m_bShowBounds, m_bShowInfo, m_bSpin, m_bUpdate, m_bUsePerspective, m_eMarchMode, m_ePolyMode, m_fCameraX, m_fCameraY, m_fCameraZ, m_fIsoLevel, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fScale, m_fTime, m_fTransparency, m_iCellCount, m_iOrigX, m_iOrigY, m_iSpinX, m_iSpinY, m_kHyper, m_kHyperCam, m_kRayTracer, m_kRayTracerCam, m_pvFunction, m_uiFuncIndex, dg::Hypertexture::setCamera(), dg::RayTracer::setCamera(), dg::Hypertexture::setDensityFunction(), dg::RayTracer::setFunction(), dg::Hypertexture::setLightDirection(), and dg::RayTracer::setLightDirection().
void Visualizer::setBackground () [protected]
Definition at line 836 of file Visualizer.cpp.
References dg::Real.
Referenced by drawHypertexture(), drawRaytraced(), and onInitialize().
void Visualizer::setLights () [protected]
Definition at line 851 of file Visualizer.cpp.
References m_ePolyMode, and dg::Real.
Referenced by onInitialize().
void Visualizer::setMaterials () [protected]
Definition at line 869 of file Visualizer.cpp.
References m_fTransparency, and dg::Real.
Referenced by onInitialize(), and onKeyDown().
void Visualizer::setupCamera (Camera & rkCamera) [protected]
Definition at line 894 of file Visualizer.cpp.
References dg::Camera::getDirection(), dg::Camera::getPosition(), dg::Camera::getUp(), dg::Window::height(), dg::Vector::length(), m_bUsePerspective, m_fCameraX, m_fCameraY, m_fCameraZ, m_fFrustumBottom, m_fFrustumFar, m_fFrustumLeft, m_fFrustumNear, m_fFrustumRight, m_fFrustumTop, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fScale, m_iSpinX, m_iSpinY, m_kPolyCam, dg::Real, dg::Camera::setDirection(), dg::Camera::setFar(), dg::Camera::setHalfHeight(), dg::Camera::setHalfWidth(), dg::Camera::setNear(), dg::Camera::setPosition(), dg::Camera::setRight(), dg::Camera::setUp(), setupFrustum(), and dg::Window::width().
Referenced by drawPolygons(), setupHypertexture(), and setupRayTracer().
void Visualizer::setupFrustum (Int iWidth, Int iHeight, bool bPerspective) [protected]
Definition at line 958 of file Visualizer.cpp.
References dg::Int, m_fFrustumBottom, m_fFrustumFar, m_fFrustumLeft, m_fFrustumNear, m_fFrustumRight, m_fFrustumTop, and dg::Real.
Referenced by onReshape(), and setupCamera().
void Visualizer::setupHypertexture () [protected]
Definition at line 798 of file Visualizer.cpp.
References dg::FilteredClownColorVolume(), dg::Window::height(), m_aucFuncName, m_bFadeOut, m_bHyperTraced, m_bKeepInView, m_bUpdate, m_fScale, m_iCellCount, m_kHyper, m_kHyperCam, m_kHyperImage, m_pvFunction, m_uiFuncIndex, ms_fCellToHyperStepScale, dg::Window::postRedisplay(), dg::Image::resize(), dg::Hypertexture::setDensityFunction(), dg::Hypertexture::setFadeOut(), dg::Hypertexture::setFilteredColorFunction(), dg::Camera::setImage(), dg::Hypertexture::setKeepInView(), dg::Hypertexture::setScale(), dg::Hypertexture::setStepSize(), setupCamera(), and dg::Window::width().
Referenced by onKeyDown(), and update().
void Visualizer::setupPolygonizer () [protected]
Definition at line 739 of file Visualizer.cpp.
References m_aucFuncName, m_bPolygonized, m_bUpdate, m_fIsoLevel, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fScale, m_iCellCount, m_kPolygonizer, m_pvFunction, m_uiFuncIndex, dg::Window::postRedisplay(), dg::Polygonizer::setCellCount(), dg::Polygonizer::setFunction(), dg::Polygonizer::setIsoLevel(), dg::Polygonizer::setOffset(), and dg::Polygonizer::setScale().
Referenced by onInitialize(), onKeyDown(), onSpecialKeyDown(), and update().
void Visualizer::setupRayTracer () [protected]
Definition at line 758 of file Visualizer.cpp.
References dg::Window::bg(), dg::Camera::getDirection(), dg::Window::height(), m_aucFuncName, m_bRayTraced, m_bUpdate, m_fIsoLevel, m_iCellCount, m_kRayTracer, m_kRayTracerCam, m_kRayTracerImage, m_pvFunction, m_uiFuncIndex, ms_fCellToRayScale, dg::Window::postRedisplay(), dg::Image::resize(), dg::RayTracer::setBaseColor(), dg::RayTracer::setBlur(), dg::Image::setClearColor(), dg::RayTracer::setFunction(), dg::Camera::setImage(), dg::RayTracer::setIsoLevel(), dg::RayTracer::setLightDirection(), dg::RayTracer::setSamples(), setupCamera(), dg::UInt, and dg::Window::width().
Referenced by onKeyDown(), and update().
void Visualizer::startCalcTimer () [protected]
Definition at line 997 of file Visualizer.cpp.
References dg::Window::m_kTimer, m_uiHours, m_uiMilliSecs, m_uiMinutes, m_uiSeconds, dg::Timer::reset(), and dg::Timer::start().
Referenced by drawHypertexture(), drawPolygons(), and drawRaytraced().
void Visualizer::stopCalcTimer () [protected]
Definition at line 1008 of file Visualizer.cpp.
References updateCalcTimer().
Referenced by drawHypertexture(), drawPolygons(), and drawRaytraced().
void Visualizer::update (Real fTime) [protected]
Definition at line 1022 of file Visualizer.cpp.
References m_eVisMode, m_fOffsetX, m_fOffsetY, m_fOffsetZ, m_fTime, m_fUpdateOffset, dg::Real, setupHypertexture(), setupPolygonizer(), setupRayTracer(), dg::Sine(), VM_HYPERTEXTURE, VM_MARCHING_CUBES, VM_MARCHING_TETRA, and VM_RAYTRACE.
Referenced by onDisplay().
void Visualizer::updateCalcTimer () [protected]
Definition at line 1014 of file Visualizer.cpp.
References dg::Timer::elapsedHours(), dg::Timer::elapsedMilliseconds(), dg::Timer::elapsedMinutes(), dg::Timer::elapsedSeconds(), dg::Window::m_kTimer, m_uiHours, m_uiMilliSecs, m_uiMinutes, and m_uiSeconds.
Referenced by drawHypertexture(), drawRaytraced(), and stopCalcTimer().
Member Data Documentation
const char* dg::Visualizer::m_aucFuncName [protected]
Definition at line 172 of file Visualizer.h.
Referenced by drawText(), onStartup(), setupHypertexture(), setupPolygonizer(), and setupRayTracer().
bool dg::Visualizer::m_bFadeOut [protected]
Definition at line 116 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), and setupHypertexture().
bool dg::Visualizer::m_bHyperTraced [protected]
Definition at line 113 of file Visualizer.h.
Referenced by drawHypertexture(), onKeyDown(), onStartup(), and setupHypertexture().
bool dg::Visualizer::m_bKeepInView [protected]
Definition at line 115 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), and setupHypertexture().
bool dg::Visualizer::m_bLight [protected]
Definition at line 108 of file Visualizer.h.
Referenced by drawPolygons(), onKeyDown(), and onStartup().
bool dg::Visualizer::m_bMove [protected]
Definition at line 105 of file Visualizer.h.
Referenced by onKeyDown(), and onStartup().
bool dg::Visualizer::m_bPolygonized [protected]
Definition at line 114 of file Visualizer.h.
Referenced by drawPolygons(), onKeyDown(), onStartup(), and setupPolygonizer().
bool dg::Visualizer::m_bRayTraced [protected]
Definition at line 112 of file Visualizer.h.
Referenced by drawRaytraced(), onKeyDown(), onStartup(), and setupRayTracer().
bool dg::Visualizer::m_bRendering [protected]
Definition at line 111 of file Visualizer.h.
Referenced by drawHypertexture(), and drawRaytraced().
bool dg::Visualizer::m_bRotate [protected]
Definition at line 96 of file Visualizer.h.
Referenced by onMouseClick(), and onStartup().
bool dg::Visualizer::m_bShowBounds [protected]
Definition at line 99 of file Visualizer.h.
Referenced by onKeyDown(), and onStartup().
bool dg::Visualizer::m_bShowInfo [protected]
Definition at line 90 of file Visualizer.h.
Referenced by onKeyDown(), and onStartup().
bool dg::Visualizer::m_bSpin [protected]
Definition at line 102 of file Visualizer.h.
Referenced by onStartup().
bool dg::Visualizer::m_bUpdate [protected]
Definition at line 93 of file Visualizer.h.
Referenced by drawHypertexture(), drawPolygons(), drawRaytraced(), onDisplay(), onKeyDown(), onStartup(), setupHypertexture(), setupPolygonizer(), and setupRayTracer().
bool dg::Visualizer::m_bUsePerspective [protected]
Definition at line 87 of file Visualizer.h.
Referenced by onKeyDown(), onReshape(), onStartup(), and setupCamera().
Polygonizer::MarchMethod dg::Visualizer::m_eMarchMode [protected]
Definition at line 130 of file Visualizer.h.
Referenced by drawPolygons(), onKeyDown(), and onStartup().
Int dg::Visualizer::m_ePolyMode [protected]
Definition at line 154 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), and setLights().
VisualizerMode dg::Visualizer::m_eVisMode [protected]
Definition at line 176 of file Visualizer.h.
Referenced by drawText(), onDisplay(), onKeyDown(), onMouseClick(), and update().
Real dg::Visualizer::m_fCameraX [protected]
Definition at line 141 of file Visualizer.h.
Referenced by onStartup(), and setupCamera().
Real dg::Visualizer::m_fCameraY [protected]
Definition at line 142 of file Visualizer.h.
Referenced by onStartup(), and setupCamera().
Real dg::Visualizer::m_fCameraZ [protected]
Definition at line 143 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), and setupCamera().
Real dg::Visualizer::m_fFrustumBottom [protected]
Definition at line 148 of file Visualizer.h.
Referenced by onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fFrustumFar [protected]
Definition at line 151 of file Visualizer.h.
Referenced by onKeyDown(), onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fFrustumLeft [protected]
Definition at line 146 of file Visualizer.h.
Referenced by onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fFrustumNear [protected]
Definition at line 150 of file Visualizer.h.
Referenced by onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fFrustumRight [protected]
Definition at line 147 of file Visualizer.h.
Referenced by onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fFrustumTop [protected]
Definition at line 149 of file Visualizer.h.
Referenced by onReshape(), setupCamera(), and setupFrustum().
Real dg::Visualizer::m_fIsoLevel [protected]
Definition at line 127 of file Visualizer.h.
Referenced by drawText(), onSpecialKeyDown(), onStartup(), setupPolygonizer(), and setupRayTracer().
Real dg::Visualizer::m_fLastCalcTime [protected]
Definition at line 80 of file Visualizer.h.
Real dg::Visualizer::m_fOffsetX [protected]
Definition at line 136 of file Visualizer.h.
Referenced by drawText(), onSpecialKeyDown(), onStartup(), setupCamera(), setupPolygonizer(), and update().
Real dg::Visualizer::m_fOffsetY [protected]
Definition at line 137 of file Visualizer.h.
Referenced by drawText(), onSpecialKeyDown(), onStartup(), setupCamera(), setupPolygonizer(), and update().
Real dg::Visualizer::m_fOffsetZ [protected]
Definition at line 138 of file Visualizer.h.
Referenced by drawText(), onSpecialKeyDown(), onStartup(), setupCamera(), setupPolygonizer(), and update().
Real dg::Visualizer::m_fScale [protected]
Definition at line 126 of file Visualizer.h.
Referenced by drawText(), onKeyDown(), onStartup(), setupCamera(), setupHypertexture(), and setupPolygonizer().
Real dg::Visualizer::m_fTime [protected]
Definition at line 129 of file Visualizer.h.
Referenced by onDisplay(), onStartup(), and update().
Real dg::Visualizer::m_fTransparency [protected]
Definition at line 133 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), and setMaterials().
Real dg::Visualizer::m_fUpdateOffset [protected]
Definition at line 128 of file Visualizer.h.
Referenced by update().
Int dg::Visualizer::m_iCellCount [protected]
Definition at line 125 of file Visualizer.h.
Referenced by drawText(), onKeyDown(), onStartup(), setupHypertexture(), setupPolygonizer(), and setupRayTracer().
Int dg::Visualizer::m_iOrigX [protected]
Definition at line 121 of file Visualizer.h.
Referenced by onMouseClick(), onMouseMotion(), and onStartup().
Int dg::Visualizer::m_iOrigY [protected]
Definition at line 122 of file Visualizer.h.
Referenced by onMouseClick(), onMouseMotion(), and onStartup().
Int dg::Visualizer::m_iSpinX [protected]
Definition at line 119 of file Visualizer.h.
Referenced by drawText(), onMouseMotion(), onStartup(), and setupCamera().
Int dg::Visualizer::m_iSpinY [protected]
Definition at line 120 of file Visualizer.h.
Referenced by drawText(), onMouseMotion(), onStartup(), and setupCamera().
Hypertexture dg::Visualizer::m_kHyper [protected]
Definition at line 166 of file Visualizer.h.
Referenced by drawHypertexture(), drawText(), onStartup(), and setupHypertexture().
Camera dg::Visualizer::m_kHyperCam [protected]
Definition at line 167 of file Visualizer.h.
Referenced by onStartup(), and setupHypertexture().
Image dg::Visualizer::m_kHyperImage [protected]
Definition at line 168 of file Visualizer.h.
Referenced by drawHypertexture(), and setupHypertexture().
Camera dg::Visualizer::m_kPolyCam [protected]
Definition at line 158 of file Visualizer.h.
Referenced by drawPolygons(), and setupCamera().
Polygonizer dg::Visualizer::m_kPolygonizer [protected]
Definition at line 157 of file Visualizer.h.
Referenced by drawPolygons(), drawText(), onKeyDown(), onSpecialKeyDown(), and setupPolygonizer().
RayTracer dg::Visualizer::m_kRayTracer [protected]
Definition at line 161 of file Visualizer.h.
Referenced by drawRaytraced(), drawText(), onStartup(), and setupRayTracer().
Camera dg::Visualizer::m_kRayTracerCam [protected]
Definition at line 162 of file Visualizer.h.
Referenced by onStartup(), and setupRayTracer().
Image dg::Visualizer::m_kRayTracerImage [protected]
Definition at line 163 of file Visualizer.h.
Referenced by drawRaytraced(), and setupRayTracer().
Operator dg::Visualizer::m_pvFunction [protected]
Definition at line 173 of file Visualizer.h.
Referenced by onStartup(), setupHypertexture(), setupPolygonizer(), and setupRayTracer().
UInt dg::Visualizer::m_uiFuncIndex [protected]
Definition at line 171 of file Visualizer.h.
Referenced by onKeyDown(), onStartup(), setupHypertexture(), setupPolygonizer(), and setupRayTracer().
UInt dg::Visualizer::m_uiHours [protected]
Definition at line 81 of file Visualizer.h.
Referenced by drawText(), startCalcTimer(), and updateCalcTimer().
UInt dg::Visualizer::m_uiMilliSecs [protected]
Definition at line 84 of file Visualizer.h.
Referenced by drawText(), startCalcTimer(), and updateCalcTimer().
UInt dg::Visualizer::m_uiMinutes [protected]
Definition at line 82 of file Visualizer.h.
Referenced by drawText(), startCalcTimer(), and updateCalcTimer().
UInt dg::Visualizer::m_uiSeconds [protected]
Definition at line 83 of file Visualizer.h.
Referenced by drawText(), startCalcTimer(), and updateCalcTimer().
const Real dg::Visualizer::ms_fCellToHyperStepScale = 0.4 [static, protected]
Definition at line 180 of file Visualizer.h.
Referenced by setupHypertexture().
const Real dg::Visualizer::ms_fCellToRayScale = 2 [static, protected]
Definition at line 179 of file Visualizer.h.
Referenced by drawText(), and setupRayTracer().
The documentation for this class was generated from the following files:
Visualizer.h
Visualizer.cpp