dg::Tracer Class Reference
#include <Tracer.h>
Public Types
typedef Real(* Function)(Real fX, Real fY, Real fZ)
Public Methods
Tracer (Function pvFunction=NULL, Camera *pkCamera=NULL)
~Tracer ()
void setCamera (Camera *pkCamera)
const Camera * getCamera () const
void setFunction (Function pvFunction)
Vector getLightDirection () const
void setLightDirection (const Vector &rkLight)
Color getLightColor () const
void setLightColor (const Color &rkLight)
void setNormalEpsilon (Real fEpsilon)
Real getNormalEpsilon () const
void setRayEpsilon (Real fEpsilon)
Real getRayEpsilon () const
void setIsoLevel (Real fLevel)
Real getIsoLevel () const
void setSamples (UInt uiSamples)
UInt getSamples () const
UInt getRayHits () const
void setBlur (bool bBlur)
bool getBlur () const
void setBackground (const Color &rkColor)
Color getBackground () const
Real getAmbient () const
void setAmbient (Real fAmbient)
Real getDiffuse () const
void setDiffuse (Real fDiffuse)
Real getSpecular () const
void setSpecular (Real fSpecular)
Real getRoughness () const
void setRoughness (Real fRoughness)
Color getBaseColor () const
void setBaseColor (const Color &rkBase)
void render ()
void render (UInt uiStartLine, UInt uiEndLine)
Member Typedef Documentation
typedef Real(* dg::Tracer::Function)(Real fX, Real fY, Real fZ)
Definition at line 18 of file Tracer.h.
Constructor & Destructor Documentation
Tracer::Tracer (Function pvFunction = NULL, Camera * pkCamera = NULL)
Definition at line 8 of file Tracer.cpp.
Tracer::~Tracer ()
Definition at line 26 of file Tracer.cpp.
Member Function Documentation
Real dg::Tracer::getAmbient () [inline]
Definition at line 259 of file Tracer.h.
Color dg::Tracer::getBackground () [inline]
Definition at line 231 of file Tracer.h.
Color dg::Tracer::getBaseColor () [inline]
Definition at line 221 of file Tracer.h.
bool dg::Tracer::getBlur () [inline]
Definition at line 211 of file Tracer.h.
const Camera * dg::Tracer::getCamera () [inline]
Definition at line 241 of file Tracer.h.
Real dg::Tracer::getDiffuse () [inline]
Definition at line 269 of file Tracer.h.
Real dg::Tracer::getIsoLevel () [inline]
Definition at line 181 of file Tracer.h.
Color dg::Tracer::getLightColor () [inline]
Definition at line 156 of file Tracer.h.
Vector dg::Tracer::getLightDirection () [inline]
Definition at line 141 of file Tracer.h.
Real dg::Tracer::getNormalEpsilon () [inline]
Definition at line 161 of file Tracer.h.
Real dg::Tracer::getRayEpsilon () [inline]
Definition at line 171 of file Tracer.h.
UInt dg::Tracer::getRayHits () [inline]
Definition at line 201 of file Tracer.h.
Referenced by dg::Visualizer::drawText().
Real dg::Tracer::getRoughness () [inline]
Definition at line 289 of file Tracer.h.
UInt dg::Tracer::getSamples () [inline]
Definition at line 191 of file Tracer.h.
Real dg::Tracer::getSpecular () [inline]
Definition at line 279 of file Tracer.h.
void Tracer::render (UInt uiStartLine, UInt uiEndLine)
Definition at line 47 of file Tracer.cpp.
References dg::Camera::getDirection(), dg::Camera::getFar(), dg::Camera::getHalfHeight(), dg::Camera::getHalfWidth(), dg::Camera::getImage(), dg::Camera::getNear(), dg::Camera::getPosition(), dg::Camera::getRight(), dg::Camera::getUp(), dg::Image::height(), dg::Normalize(), dg::Real, dg::Image::setColor(), dg::UInt, and dg::Image::width().
void Tracer::render ()
Definition at line 31 of file Tracer.cpp.
References dg::Image::blur(), dg::Camera::getImage(), and dg::Image::height().
Referenced by dg::Visualizer::drawRaytraced().
void dg::Tracer::setAmbient (Real fAmbient) [inline]
Definition at line 264 of file Tracer.h.
void dg::Tracer::setBackground (const Color & rkColor) [inline]
Definition at line 226 of file Tracer.h.
void dg::Tracer::setBaseColor (const Color & rkBase) [inline]
Definition at line 216 of file Tracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::Tracer::setBlur (bool bBlur) [inline]
Definition at line 206 of file Tracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::Tracer::setCamera (Camera * pkCamera) [inline]
Definition at line 236 of file Tracer.h.
Referenced by dg::Visualizer::onStartup().
void dg::Tracer::setDiffuse (Real fDiffuse) [inline]
Definition at line 274 of file Tracer.h.
void dg::Tracer::setFunction (Function pvFunction) [inline]
Definition at line 246 of file Tracer.h.
Referenced by dg::Visualizer::onKeyDown(), dg::Visualizer::onStartup(), and dg::Visualizer::setupRayTracer().
void dg::Tracer::setIsoLevel (Real fLevel) [inline]
Definition at line 186 of file Tracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::Tracer::setLightColor (const Color & rkLight) [inline]
Definition at line 151 of file Tracer.h.
void dg::Tracer::setLightDirection (const Vector & rkLight) [inline]
Definition at line 146 of file Tracer.h.
Referenced by dg::Visualizer::onStartup(), and dg::Visualizer::setupRayTracer().
void dg::Tracer::setNormalEpsilon (Real fEpsilon) [inline]
Definition at line 166 of file Tracer.h.
void dg::Tracer::setRayEpsilon (Real fEpsilon) [inline]
Definition at line 176 of file Tracer.h.
void dg::Tracer::setRoughness (Real fRoughness) [inline]
Definition at line 294 of file Tracer.h.
void dg::Tracer::setSamples (UInt uiSamples) [inline]
Definition at line 196 of file Tracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::Tracer::setSpecular (Real fSpecular) [inline]
Definition at line 284 of file Tracer.h.
The documentation for this class was generated from the following files:
Tracer.h
Tracer.cpp