dg::RayTracer Class Reference
#include <RayTracer.h>
Public Types
typedef Real(* Function)(Real fX, Real fY, Real fZ)
Public Methods
RayTracer (Function pvFunction=NULL, Camera *pkCamera=NULL)
~RayTracer ()
void setCamera (Camera *pkCamera)
const Camera * getCamera () const
void setFunction (Function pvFunction)
Vector getLightDirection () const
void setLightDirection (const Vector &rkLight)
Color getLightColor () const
void setLightColor (const Color &rkLight)
void setNormalEpsilon (Real fEpsilon)
Real getNormalEpsilon () const
void setRayEpsilon (Real fEpsilon)
Real getRayEpsilon () const
void setIsoLevel (Real fLevel)
Real getIsoLevel () const
void setSamples (UInt uiSamples)
UInt getSamples () const
UInt getRayHits () const
void setBlur (bool bBlur)
bool getBlur () const
void setBackground (const Color &rkColor)
Color getBackground () const
Real getAmbient () const
void setAmbient (Real fAmbient)
Real getDiffuse () const
void setDiffuse (Real fDiffuse)
Real getSpecular () const
void setSpecular (Real fSpecular)
Real getRoughness () const
void setRoughness (Real fRoughness)
Color getBaseColor () const
void setBaseColor (const Color &rkBase)
void render ()
void render (UInt uiStartLine, UInt uiEndLine)
Member Typedef Documentation
typedef Real(* dg::RayTracer::Function)(Real fX, Real fY, Real fZ)
Definition at line 18 of file RayTracer.h.
Constructor & Destructor Documentation
RayTracer::RayTracer (Function pvFunction = NULL, Camera * pkCamera = NULL)
Definition at line 8 of file RayTracer.cpp.
RayTracer::~RayTracer ()
Definition at line 26 of file RayTracer.cpp.
Member Function Documentation
Real dg::RayTracer::getAmbient () [inline]
Definition at line 259 of file RayTracer.h.
Color dg::RayTracer::getBackground () [inline]
Definition at line 231 of file RayTracer.h.
Color dg::RayTracer::getBaseColor () [inline]
Definition at line 221 of file RayTracer.h.
bool dg::RayTracer::getBlur () [inline]
Definition at line 211 of file RayTracer.h.
const Camera * dg::RayTracer::getCamera () [inline]
Definition at line 241 of file RayTracer.h.
Real dg::RayTracer::getDiffuse () [inline]
Definition at line 269 of file RayTracer.h.
Real dg::RayTracer::getIsoLevel () [inline]
Definition at line 181 of file RayTracer.h.
Color dg::RayTracer::getLightColor () [inline]
Definition at line 156 of file RayTracer.h.
Vector dg::RayTracer::getLightDirection () [inline]
Definition at line 141 of file RayTracer.h.
Real dg::RayTracer::getNormalEpsilon () [inline]
Definition at line 161 of file RayTracer.h.
Real dg::RayTracer::getRayEpsilon () [inline]
Definition at line 171 of file RayTracer.h.
UInt dg::RayTracer::getRayHits () [inline]
Definition at line 201 of file RayTracer.h.
Referenced by dg::Visualizer::drawText().
Real dg::RayTracer::getRoughness () [inline]
Definition at line 289 of file RayTracer.h.
UInt dg::RayTracer::getSamples () [inline]
Definition at line 191 of file RayTracer.h.
Real dg::RayTracer::getSpecular () [inline]
Definition at line 279 of file RayTracer.h.
void RayTracer::render (UInt uiStartLine, UInt uiEndLine)
Definition at line 47 of file RayTracer.cpp.
References dg::Camera::getDirection(), dg::Camera::getFar(), dg::Camera::getHalfHeight(), dg::Camera::getHalfWidth(), dg::Camera::getImage(), dg::Camera::getNear(), dg::Camera::getPosition(), dg::Camera::getRight(), dg::Camera::getUp(), dg::Image::height(), dg::Normalize(), dg::Real, dg::Image::setColor(), dg::UInt, and dg::Image::width().
void RayTracer::render ()
Definition at line 31 of file RayTracer.cpp.
References dg::Image::blur(), dg::Camera::getImage(), and dg::Image::height().
Referenced by dg::Visualizer::drawRaytraced().
void dg::RayTracer::setAmbient (Real fAmbient) [inline]
Definition at line 264 of file RayTracer.h.
void dg::RayTracer::setBackground (const Color & rkColor) [inline]
Definition at line 226 of file RayTracer.h.
void dg::RayTracer::setBaseColor (const Color & rkBase) [inline]
Definition at line 216 of file RayTracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::RayTracer::setBlur (bool bBlur) [inline]
Definition at line 206 of file RayTracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::RayTracer::setCamera (Camera * pkCamera) [inline]
Definition at line 236 of file RayTracer.h.
Referenced by dg::Visualizer::onStartup().
void dg::RayTracer::setDiffuse (Real fDiffuse) [inline]
Definition at line 274 of file RayTracer.h.
void dg::RayTracer::setFunction (Function pvFunction) [inline]
Definition at line 246 of file RayTracer.h.
Referenced by dg::Visualizer::onStartup(), and dg::Visualizer::setupRayTracer().
void dg::RayTracer::setIsoLevel (Real fLevel) [inline]
Definition at line 186 of file RayTracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::RayTracer::setLightColor (const Color & rkLight) [inline]
Definition at line 151 of file RayTracer.h.
void dg::RayTracer::setLightDirection (const Vector & rkLight) [inline]
Definition at line 146 of file RayTracer.h.
Referenced by dg::Visualizer::onStartup(), and dg::Visualizer::setupRayTracer().
void dg::RayTracer::setNormalEpsilon (Real fEpsilon) [inline]
Definition at line 166 of file RayTracer.h.
void dg::RayTracer::setRayEpsilon (Real fEpsilon) [inline]
Definition at line 176 of file RayTracer.h.
void dg::RayTracer::setRoughness (Real fRoughness) [inline]
Definition at line 294 of file RayTracer.h.
void dg::RayTracer::setSamples (UInt uiSamples) [inline]
Definition at line 196 of file RayTracer.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::RayTracer::setSpecular (Real fSpecular) [inline]
Definition at line 284 of file RayTracer.h.
The documentation for this class was generated from the following files:
RayTracer.h
RayTracer.cpp