dg::Timer Class Reference
#include <Timer.h>
Public Types
enum TimerState { TS_OFF,
TS_ON,
TS_HOLD,
TS_COUNT
 }
Public Methods
Timer ()
~Timer ()
void start ()
void stop ()
void suspend ()
void resume ()
void reset ()
void count ()
Real elapsedTime ()
UInt elapsedCount ()
UInt elapsedHours ()
UInt elapsedMinutes ()
UInt elapsedSeconds ()
UInt elapsedMilliseconds ()
UInt seconds ()
UInt milliseconds ()
Member Enumeration Documentation
enum dg::Timer::TimerState
Enumeration values:
TS_OFF
TS_ON
TS_HOLD
TS_COUNT
Definition at line 38 of file Timer.h.
Constructor & Destructor Documentation
Timer::Timer ()
Definition at line 36 of file Timer.cpp.
References reset().
dg::Timer::~Timer () [inline]
Definition at line 110 of file Timer.h.
Member Function Documentation
void dg::Timer::count () [inline]
Definition at line 161 of file Timer.h.
UInt dg::Timer::elapsedCount () [inline]
Definition at line 234 of file Timer.h.
UInt dg::Timer::elapsedHours () [inline]
Definition at line 183 of file Timer.h.
Referenced by dg::Visualizer::updateCalcTimer().
UInt dg::Timer::elapsedMilliseconds () [inline]
Definition at line 213 of file Timer.h.
Referenced by dg::Visualizer::updateCalcTimer().
UInt dg::Timer::elapsedMinutes () [inline]
Definition at line 188 of file Timer.h.
Referenced by dg::Visualizer::updateCalcTimer().
UInt dg::Timer::elapsedSeconds () [inline]
Definition at line 193 of file Timer.h.
Referenced by dg::Window::drawFrameRate(), and dg::Visualizer::updateCalcTimer().
Real dg::Timer::elapsedTime () [inline]
Definition at line 166 of file Timer.h.
UInt dg::Timer::milliseconds () [inline]
Definition at line 244 of file Timer.h.
void dg::Timer::reset () [inline]
Definition at line 152 of file Timer.h.
Referenced by dg::Visualizer::startCalcTimer(), and Timer().
void dg::Timer::resume () [inline]
Definition at line 137 of file Timer.h.
UInt dg::Timer::seconds () [inline]
Definition at line 239 of file Timer.h.
void dg::Timer::start () [inline]
Definition at line 115 of file Timer.h.
Referenced by dg::Visualizer::startCalcTimer().
void dg::Timer::stop () [inline]
Definition at line 122 of file Timer.h.
void dg::Timer::suspend () [inline]
Definition at line 128 of file Timer.h.
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp