dg::Window Class Reference
#include <Window.h>
Public Methods
virtual ~Window ()
virtual Bool onStartup ()
virtual Bool onInitialize ()
virtual void onTerminate ()
virtual void onMove (Int iX, Int iY)
virtual void onReshape (Int iWidth, Int iHeight)
virtual void onUpdate (Int iValue)
virtual void onDisplay ()
virtual void postRedisplay ()
virtual void swapBuffers ()
virtual void onKeyDown (UChar ucKey, Int iX, Int iY)
virtual void onKeyUp (UChar ucKey, Int iX, Int iY)
virtual void onSpecialKeyDown (Int iKey, Int iX, Int iY)
virtual void onSpecialKeyUp (Int iKey, Int iX, Int iY)
virtual void onPassiveMotion (Int iX, Int iY)
virtual void onMouseMotion (Int iX, Int iY, UInt uiModifiers)
virtual void onMouseClick (Int iButton, Int iState, Int iX, Int iY, UInt uiModifiers)
virtual void onIdle ()
void drawImage (const UChar *aucBuffer, UInt uiPosX, UInt uiPosY, UInt uiWidth, UInt uiHeight, bool bAlpha)
void drawImage (const Real *afBuffer, UInt uiPosX, UInt uiPosY, UInt uiWidth, UInt uiHeight, bool bAlpha)
void drawString (const Char *pcString, Int iX, Int iY, const Color &rkColor)
void drawFrameRate (Int iX, Int iY, const Color &rkColor)
void updateClicks ()
void makeCurrent ()
char * title ()
UInt x ()
UInt y ()
UInt width ()
UInt height ()
const Color & bg ()
Timer & timer ()
void setWindowID (Int iWindowID)
Int id ()
Static Public Methods
Window * current ()
Static Public Attributes
const Int KEY_ESCAPE = 0x1B
const Int KEY_LEFT_ARROW = GLUT_KEY_LEFT
const Int KEY_RIGHT_ARROW = GLUT_KEY_RIGHT
const Int KEY_UP_ARROW = GLUT_KEY_UP
const Int KEY_DOWN_ARROW = GLUT_KEY_DOWN
const Int KEY_HOME = GLUT_KEY_HOME
const Int KEY_END = GLUT_KEY_END
const Int KEY_PAGE_UP = GLUT_KEY_PAGE_UP
const Int KEY_PAGE_DOWN = GLUT_KEY_PAGE_DOWN
const Int KEY_INSERT = GLUT_KEY_INSERT
const Int KEY_DELETE = 0x2E
const Int KEY_F1 = GLUT_KEY_F1
const Int KEY_F2 = GLUT_KEY_F2
const Int KEY_F3 = GLUT_KEY_F3
const Int KEY_F4 = GLUT_KEY_F4
const Int KEY_F5 = GLUT_KEY_F5
const Int KEY_F6 = GLUT_KEY_F6
const Int KEY_F7 = GLUT_KEY_F7
const Int KEY_F8 = GLUT_KEY_F8
const Int KEY_F9 = GLUT_KEY_F9
const Int KEY_F10 = GLUT_KEY_F10
const Int KEY_F11 = GLUT_KEY_F11
const Int KEY_F12 = GLUT_KEY_F12
const Int KEY_SHIFT = GLUT_ACTIVE_SHIFT
const Int KEY_CONTROL = GLUT_ACTIVE_CTRL
const Int KEY_ALT = GLUT_ACTIVE_ALT
const Int KEY_COMMAND = 0
const Int MOUSE_LEFT_BUTTON = GLUT_LEFT_BUTTON
const Int MOUSE_MIDDLE_BUTTON = GLUT_MIDDLE_BUTTON
const Int MOUSE_RIGHT_BUTTON = GLUT_RIGHT_BUTTON
const Int MOUSE_UP = GLUT_UP
const Int MOUSE_DOWN = GLUT_DOWN
const Int MOD_LBUTTON
const Int MOD_MBUTTON
const Int MOD_RBUTTON
Protected Methods
Window (char *acWindowTitle, Int iX, Int iY, Int iWidth, Int iHeight, const Color &rkBgColor)
Protected Attributes
Bool m_bMouseDown
Bool m_bLeftMousePressed
Bool m_bRightMousePressed
Bool m_bMiddleMousePressed
Int m_iLastMouseX
Int m_iLastMouseY
Real m_fFrameRate
Int m_iClicks
Int m_iTimer
Int m_iMaxTimer
char * m_acWindowTitle
Int m_iWindowID
Int m_iX
Int m_iY
Int m_iWidth
Int m_iHeight
Color m_kBgColor
Timer m_kTimer
Static Protected Attributes
Window * ms_pkWindow = NULL
Constructor & Destructor Documentation
Window::~Window () [virtual]
Definition at line 27 of file Window.cpp.
References ms_pkWindow.
Window::Window (char * acWindowTitle, Int iX, Int iY, Int iWidth, Int iHeight, const Color & rkBgColor) [protected]
Definition at line 9 of file Window.cpp.
References dg::Int, m_acWindowTitle, m_iClicks, m_iHeight, m_iMaxTimer, m_iTimer, m_iWidth, m_iX, m_iY, m_kBgColor, and ms_pkWindow.
Member Function Documentation
const Color & dg::Window::bg () [inline]
Definition at line 193 of file Window.h.
Referenced by dg::Visualizer::setupRayTracer().
Window * dg::Window::current () [inline, static]
Definition at line 163 of file Window.h.
void Window::drawFrameRate (Int iX, Int iY, const Color & rkColor)
Definition at line 132 of file Window.cpp.
References drawString(), dg::Timer::elapsedSeconds(), dg::Int, m_fFrameRate, m_iClicks, m_iMaxTimer, m_iTimer, m_kTimer, and dg::Real.
void Window::drawImage (const Real * afBuffer, UInt uiPosX, UInt uiPosY, UInt uiWidth, UInt uiHeight, bool bAlpha)
Definition at line 209 of file GlutWindow.cpp.
References m_iHeight, m_iWidth, dg::Real, and dg::UInt.
void Window::drawImage (const UChar * aucBuffer, UInt uiPosX, UInt uiPosY, UInt uiWidth, UInt uiHeight, bool bAlpha)
Definition at line 147 of file GlutWindow.cpp.
References m_iHeight, m_iWidth, dg::UChar, and dg::UInt.
Referenced by dg::Visualizer::drawHypertexture(), and dg::Visualizer::drawRaytraced().
void Window::drawString (const Char * pcString, Int iX, Int iY, const Color & rkColor)
Definition at line 131 of file GlutWindow.cpp.
References dg::Color::a(), dg::Color::b(), dg::Char, dg::Color::g(), dg::Int, dg::Color::r(), and dg::UInt.
Referenced by drawFrameRate(), and dg::Visualizer::drawText().
UInt dg::Window::height () [inline]
Definition at line 188 of file Window.h.
Referenced by dg::Visualizer::drawText(), dg::Visualizer::onInitialize(), dg::Visualizer::onKeyDown(), dg::Visualizer::setupCamera(), dg::Visualizer::setupHypertexture(), and dg::Visualizer::setupRayTracer().
Int dg::Window::id () [inline]
Definition at line 203 of file Window.h.
Referenced by makeCurrent(), and postRedisplay().
void Window::makeCurrent ()
Definition at line 115 of file GlutWindow.cpp.
References id(), and ms_pkWindow.
void Window::onDisplay () [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 55 of file Window.cpp.
Referenced by onIdle().
void Window::onIdle () [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 60 of file Window.cpp.
References onDisplay().
Bool Window::onInitialize () [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 38 of file Window.cpp.
References dg::Bool.
void Window::onKeyDown (UChar ucKey, Int iX, Int iY) [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 65 of file Window.cpp.
References dg::Int, KEY_ESCAPE, onTerminate(), and dg::UChar.
void Window::onKeyUp (UChar ucKey, Int iX, Int iY) [virtual]
Definition at line 72 of file Window.cpp.
References dg::Int, and dg::UChar.
void Window::onMouseClick (Int iButton, Int iState, Int iX, Int iY, UInt uiModifiers) [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 87 of file Window.cpp.
References dg::Int, m_bLeftMousePressed, m_bMiddleMousePressed, m_bMouseDown, m_bRightMousePressed, m_iLastMouseX, m_iLastMouseY, and dg::UInt.
void Window::onMouseMotion (Int iX, Int iY, UInt uiModifiers) [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 115 of file Window.cpp.
References dg::Int, and dg::UInt.
void Window::onMove (Int iX, Int iY) [virtual]
Definition at line 43 of file Window.cpp.
References dg::Int, m_iX, and m_iY.
void Window::onPassiveMotion (Int iX, Int iY) [virtual]
Definition at line 120 of file Window.cpp.
References dg::Int.
void Window::onReshape (Int iWidth, Int iHeight) [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 49 of file Window.cpp.
References dg::Int, m_iHeight, and m_iWidth.
void Window::onSpecialKeyDown (Int iKey, Int iX, Int iY) [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 77 of file Window.cpp.
References dg::Int.
void Window::onSpecialKeyUp (Int iKey, Int iX, Int iY) [virtual]
Definition at line 82 of file Window.cpp.
References dg::Int.
Bool Window::onStartup () [virtual]
Reimplemented in dg::Visualizer (p.).
Definition at line 33 of file Window.cpp.
References dg::Bool.
void Window::onTerminate () [virtual]
Definition at line 101 of file GlutWindow.cpp.
Referenced by onKeyDown().
void Window::onUpdate (Int iValue) [virtual]
Definition at line 107 of file GlutWindow.cpp.
References dg::Int, and postRedisplay().
void Window::postRedisplay () [virtual]
Definition at line 121 of file GlutWindow.cpp.
References id().
Referenced by dg::Visualizer::drawHypertexture(), dg::Visualizer::drawRaytraced(), onUpdate(), dg::Visualizer::setupHypertexture(), dg::Visualizer::setupPolygonizer(), and dg::Visualizer::setupRayTracer().
void dg::Window::setWindowID (Int iWindowID) [inline]
Definition at line 198 of file Window.h.
void Window::swapBuffers () [virtual]
Definition at line 126 of file GlutWindow.cpp.
Referenced by dg::Visualizer::drawHypertexture(), dg::Visualizer::drawRaytraced(), and dg::Visualizer::onDisplay().
Timer & dg::Window::timer () [inline]
Definition at line 208 of file Window.h.
char * dg::Window::title () [inline]
Definition at line 168 of file Window.h.
void Window::updateClicks ()
Definition at line 125 of file Window.cpp.
References m_iClicks.
Referenced by dg::Visualizer::onDisplay().
UInt dg::Window::width () [inline]
Definition at line 183 of file Window.h.
Referenced by dg::Visualizer::drawText(), dg::Visualizer::onInitialize(), dg::Visualizer::onKeyDown(), dg::Visualizer::setupCamera(), dg::Visualizer::setupHypertexture(), and dg::Visualizer::setupRayTracer().
UInt dg::Window::x () [inline]
Definition at line 173 of file Window.h.
UInt dg::Window::y () [inline]
Definition at line 178 of file Window.h.
Member Data Documentation
const Int Window::KEY_ALT = GLUT_ACTIVE_ALT [static]
Definition at line 34 of file GlutKeyBindings.h.
const Int Window::KEY_COMMAND = 0 [static]
Definition at line 35 of file GlutKeyBindings.h.
const Int Window::KEY_CONTROL = GLUT_ACTIVE_CTRL [static]
Definition at line 33 of file GlutKeyBindings.h.
const Int Window::KEY_DELETE = 0x2E [static]
Definition at line 18 of file GlutKeyBindings.h.
const Int Window::KEY_DOWN_ARROW = GLUT_KEY_DOWN [static]
Definition at line 12 of file GlutKeyBindings.h.
const Int Window::KEY_END = GLUT_KEY_END [static]
Definition at line 14 of file GlutKeyBindings.h.
const Int Window::KEY_ESCAPE = 0x1B [static]
Definition at line 8 of file GlutKeyBindings.h.
Referenced by onKeyDown().
const Int Window::KEY_F1 = GLUT_KEY_F1 [static]
Definition at line 19 of file GlutKeyBindings.h.
const Int Window::KEY_F10 = GLUT_KEY_F10 [static]
Definition at line 28 of file GlutKeyBindings.h.
const Int Window::KEY_F11 = GLUT_KEY_F11 [static]
Definition at line 29 of file GlutKeyBindings.h.
const Int Window::KEY_F12 = GLUT_KEY_F12 [static]
Definition at line 30 of file GlutKeyBindings.h.
const Int Window::KEY_F2 = GLUT_KEY_F2 [static]
Definition at line 20 of file GlutKeyBindings.h.
const Int Window::KEY_F3 = GLUT_KEY_F3 [static]
Definition at line 21 of file GlutKeyBindings.h.
const Int Window::KEY_F4 = GLUT_KEY_F4 [static]
Definition at line 22 of file GlutKeyBindings.h.
const Int Window::KEY_F5 = GLUT_KEY_F5 [static]
Definition at line 23 of file GlutKeyBindings.h.
const Int Window::KEY_F6 = GLUT_KEY_F6 [static]
Definition at line 24 of file GlutKeyBindings.h.
const Int Window::KEY_F7 = GLUT_KEY_F7 [static]
Definition at line 25 of file GlutKeyBindings.h.
const Int Window::KEY_F8 = GLUT_KEY_F8 [static]
Definition at line 26 of file GlutKeyBindings.h.
const Int Window::KEY_F9 = GLUT_KEY_F9 [static]
Definition at line 27 of file GlutKeyBindings.h.
const Int Window::KEY_HOME = GLUT_KEY_HOME [static]
Definition at line 13 of file GlutKeyBindings.h.
const Int Window::KEY_INSERT = GLUT_KEY_INSERT [static]
Definition at line 17 of file GlutKeyBindings.h.
const Int Window::KEY_LEFT_ARROW = GLUT_KEY_LEFT [static]
Definition at line 9 of file GlutKeyBindings.h.
const Int Window::KEY_PAGE_DOWN = GLUT_KEY_PAGE_DOWN [static]
Definition at line 16 of file GlutKeyBindings.h.
const Int Window::KEY_PAGE_UP = GLUT_KEY_PAGE_UP [static]
Definition at line 15 of file GlutKeyBindings.h.
const Int Window::KEY_RIGHT_ARROW = GLUT_KEY_RIGHT [static]
Definition at line 10 of file GlutKeyBindings.h.
const Int Window::KEY_SHIFT = GLUT_ACTIVE_SHIFT [static]
Definition at line 32 of file GlutKeyBindings.h.
const Int Window::KEY_UP_ARROW = GLUT_KEY_UP [static]
Definition at line 11 of file GlutKeyBindings.h.
char* dg::Window::m_acWindowTitle [protected]
Definition at line 152 of file Window.h.
Referenced by Window().
Bool dg::Window::m_bLeftMousePressed [protected]
Definition at line 138 of file Window.h.
Referenced by onMouseClick(), and dg::Visualizer::onMouseClick().
Bool dg::Window::m_bMiddleMousePressed [protected]
Definition at line 140 of file Window.h.
Referenced by onMouseClick(), and dg::Visualizer::onMouseClick().
Bool dg::Window::m_bMouseDown [protected]
Definition at line 137 of file Window.h.
Referenced by onMouseClick().
Bool dg::Window::m_bRightMousePressed [protected]
Definition at line 139 of file Window.h.
Referenced by onMouseClick(), and dg::Visualizer::onMouseClick().
Real dg::Window::m_fFrameRate [protected]
Definition at line 145 of file Window.h.
Referenced by drawFrameRate().
Int dg::Window::m_iClicks [protected]
Definition at line 146 of file Window.h.
Referenced by drawFrameRate(), updateClicks(), and Window().
Int dg::Window::m_iHeight [protected]
Definition at line 155 of file Window.h.
Referenced by drawImage(), onReshape(), and Window().
Int dg::Window::m_iLastMouseX [protected]
Definition at line 141 of file Window.h.
Referenced by onMouseClick().
Int dg::Window::m_iLastMouseY [protected]
Definition at line 142 of file Window.h.
Referenced by onMouseClick().
Int dg::Window::m_iMaxTimer [protected]
Definition at line 148 of file Window.h.
Referenced by drawFrameRate(), and Window().
Int dg::Window::m_iTimer [protected]
Definition at line 147 of file Window.h.
Referenced by drawFrameRate(), and Window().
Int dg::Window::m_iWidth [protected]
Definition at line 155 of file Window.h.
Referenced by drawImage(), onReshape(), and Window().
Int dg::Window::m_iWindowID [protected]
Definition at line 153 of file Window.h.
Int dg::Window::m_iX [protected]
Definition at line 154 of file Window.h.
Referenced by onMove(), and Window().
Int dg::Window::m_iY [protected]
Definition at line 154 of file Window.h.
Referenced by onMove(), and Window().
Color dg::Window::m_kBgColor [protected]
Definition at line 156 of file Window.h.
Referenced by Window().
Timer dg::Window::m_kTimer [protected]
Definition at line 157 of file Window.h.
Referenced by drawFrameRate(), dg::Visualizer::startCalcTimer(), and dg::Visualizer::updateCalcTimer().
const Int dg::Window::MOD_LBUTTON [static]
Definition at line 59 of file Window.h.
const Int dg::Window::MOD_MBUTTON [static]
Definition at line 60 of file Window.h.
const Int dg::Window::MOD_RBUTTON [static]
Definition at line 61 of file Window.h.
const Int Window::MOUSE_DOWN = GLUT_DOWN [static]
Definition at line 41 of file GlutKeyBindings.h.
const Int Window::MOUSE_LEFT_BUTTON = GLUT_LEFT_BUTTON [static]
Definition at line 37 of file GlutKeyBindings.h.
const Int Window::MOUSE_MIDDLE_BUTTON = GLUT_MIDDLE_BUTTON [static]
Definition at line 38 of file GlutKeyBindings.h.
const Int Window::MOUSE_RIGHT_BUTTON = GLUT_RIGHT_BUTTON [static]
Definition at line 39 of file GlutKeyBindings.h.
const Int Window::MOUSE_UP = GLUT_UP [static]
Definition at line 40 of file GlutKeyBindings.h.
Window * Window::ms_pkWindow = NULL [static, protected]
Definition at line 6 of file Window.cpp.
Referenced by makeCurrent(), Window(), and ~Window().
The documentation for this class was generated from the following files:
Window.h
GlutKeyBindings.h
GlutWindow.cpp
Window.cpp