dg::Image Class Reference
#include <Image.h>
Public Methods
Image (UInt uiWidth=0, UInt uiHeight=0, UInt uiChannels=0, const Color &rkClearColor=Color::GRAY)
~Image ()
const Real * operator[] (UInt uiIndex) const
Real * operator[] (UInt uiIndex)
const Real * operator() (UInt uiX, UInt uiY, UInt uiC) const
Real * operator() (UInt uiX, UInt uiY, UInt uiC)
Color operator() (UInt uiX, UInt uiY) const
UInt index (UInt uiX, UInt uiY, UInt uiC) const
UInt width () const
UInt height () const
UInt channels () const
UInt getWidth () const
UInt getHeight () const
UInt getChannels () const
const Real * pixels () const
Real * pixels ()
const Real * getPixels () const
Real * getPixels ()
Color getColor (UInt uiX, UInt uiY) const
void setColor (UInt uiX, UInt uiY, const Color &rkColor)
Color getClearColor () const
void setClearColor (const Color &rkColor)
void resize (UInt uiWidth, UInt uiHeight, UInt uiChannels)
void blur ()
Constructor & Destructor Documentation
Image::Image (UInt uiWidth = 0, UInt uiHeight = 0, UInt uiChannels = 0, const Color & rkClearColor = Color::GRAY)
Definition at line 9 of file Image.cpp.
References dg::Real, and dg::UInt.
Image::~Image ()
Definition at line 29 of file Image.cpp.
Member Function Documentation
void Image::blur ()
Definition at line 58 of file Image.cpp.
References dg::Real, and dg::UInt.
Referenced by dg::RayTracer::render().
UInt dg::Image::channels () [inline]
Definition at line 142 of file Image.h.
UInt dg::Image::getChannels () [inline]
Definition at line 167 of file Image.h.
Color dg::Image::getClearColor () [inline]
Definition at line 205 of file Image.h.
Color dg::Image::getColor (UInt uiX, UInt uiY) const [inline]
Definition at line 182 of file Image.h.
UInt dg::Image::getHeight () [inline]
Definition at line 162 of file Image.h.
Real * dg::Image::getPixels () [inline]
Definition at line 177 of file Image.h.
const Real * dg::Image::getPixels () [inline]
Definition at line 172 of file Image.h.
UInt dg::Image::getWidth () [inline]
Definition at line 157 of file Image.h.
UInt dg::Image::height () [inline]
Definition at line 137 of file Image.h.
Referenced by dg::Visualizer::drawHypertexture(), dg::Visualizer::drawRaytraced(), dg::RayTracer::render(), dg::Hypertexture::render(), and dg::Camera::setup().
UInt dg::Image::index (UInt uiX, UInt uiY, UInt uiC) const [inline]
Definition at line 127 of file Image.h.
Color dg::Image::operator() (UInt uiX, UInt uiY) const [inline]
Definition at line 114 of file Image.h.
Real * dg::Image::operator() (UInt uiX, UInt uiY, UInt uiC) [inline]
Definition at line 105 of file Image.h.
const Real * dg::Image::operator() (UInt uiX, UInt uiY, UInt uiC) const [inline]
Definition at line 96 of file Image.h.
Real * dg::Image::operator[] (UInt uiIndex) [inline]
Definition at line 88 of file Image.h.
const Real * dg::Image::operator[] (UInt uiIndex) const [inline]
Definition at line 80 of file Image.h.
Real * dg::Image::pixels () [inline]
Definition at line 152 of file Image.h.
const Real * dg::Image::pixels () [inline]
Definition at line 147 of file Image.h.
Referenced by dg::Visualizer::drawHypertexture(), and dg::Visualizer::drawRaytraced().
void Image::resize (UInt uiWidth, UInt uiHeight, UInt uiChannels)
Definition at line 35 of file Image.cpp.
References dg::Real, and dg::UInt.
Referenced by dg::Visualizer::setupHypertexture(), and dg::Visualizer::setupRayTracer().
void dg::Image::setClearColor (const Color & rkColor) [inline]
Definition at line 210 of file Image.h.
Referenced by dg::Visualizer::setupRayTracer().
void dg::Image::setColor (UInt uiX, UInt uiY, const Color & rkColor) [inline]
Definition at line 195 of file Image.h.
Referenced by dg::RayTracer::render(), and dg::Hypertexture::render().
UInt dg::Image::width () [inline]
Definition at line 132 of file Image.h.
Referenced by dg::Visualizer::drawHypertexture(), dg::Visualizer::drawRaytraced(), dg::RayTracer::render(), dg::Hypertexture::render(), and dg::Camera::setup().
The documentation for this class was generated from the following files:
Image.h
Image.cpp