dg::Polygonizer Class Reference
#include <Polygonizer.h>
Public Types
typedef Set< Color > ColorList
typedef Set< Vector > VectorList
typedef Real(* Function)(Real fX, Real fY, Real fZ)
enum MarchMethod { MM_CUBES,
MM_TETRA
 }
Public Methods
Polygonizer (Function pvFunction=NULL, Int iCellCount=8, Real fScale=1.0, Real fIsoLevel=1.0)
Real sample (Real fX, Real fY, Real fZ)
void setFunction (Function pvFunction)
void setInverseNormals (bool bInvNormals)
bool getInverseNormals ()
void setCellCount (Int iCellCount)
Int getCellCount ()
void setIsoLevel (Real fIsoLevel)
Real getIsoLevel ()
void setOffset (Real fX, Real fY, Real fZ)
void getOffset (Real &fX, Real &fY, Real &fZ)
void setScale (Real fScale)
Real getScale ()
void setEpsilon (Real fEpsilon)
Real getEpsilon ()
VectorList & getVertices ()
VectorList & getNormals ()
ColorList & getColors ()
Real getIntersect (Real fV1, Real fV2, Real fLevel)
void getColor (Color &rkColor, Vector &rkPos, Vector &rkNormal)
void getNormal (Vector &rkNormal, Real fX, Real fY, Real fZ)
void marchCube (Real fX, Real fY, Real fZ, Real fScale)
void marchTetra (Vector *pakTetraPos, Real *pafTetraValue)
void marchTetraCube (Real fX, Real fY, Real fZ, Real fScale)
void evaluate (MarchMethod eType=MM_TETRA)
Protected Attributes
Function m_pvFunction
bool m_bInverseNormals
Int m_iCellCount
Real m_fScale
Real m_fDelta
Real m_fEpsilon
Real m_fIsoLevel
Vector m_kOffset
VectorList m_kVertexList
VectorList m_kNormalList
ColorList m_kColorList
Member Typedef Documentation
typedef Set<Color> dg::Polygonizer::ColorList
Definition at line 26 of file Polygonizer.h.
typedef Real(* dg::Polygonizer::Function)(Real fX, Real fY, Real fZ)
Definition at line 28 of file Polygonizer.h.
typedef Set<Vector> dg::Polygonizer::VectorList
Definition at line 27 of file Polygonizer.h.
Member Enumeration Documentation
enum dg::Polygonizer::MarchMethod
Enumeration values:
MM_CUBES
MM_TETRA
Definition at line 19 of file Polygonizer.h.
Constructor & Destructor Documentation
Polygonizer::Polygonizer (Function pvFunction = NULL, Int iCellCount = 8, Real fScale = 1.0, Real fIsoLevel = 1.0)
Definition at line 8 of file Polygonizer.cpp.
References dg::Int, m_fDelta, m_fEpsilon, m_fIsoLevel, m_fScale, m_iCellCount, m_pvFunction, and dg::Real.
Member Function Documentation
void Polygonizer::evaluate (MarchMethod eType = MM_TETRA)
Definition at line 251 of file Polygonizer.cpp.
References dg::Int, m_fDelta, m_iCellCount, m_kColorList, m_kNormalList, m_kVertexList, m_pvFunction, marchCube(), and marchTetraCube().
Referenced by dg::Visualizer::drawPolygons().
Int dg::Polygonizer::getCellCount () [inline]
Definition at line 134 of file Polygonizer.h.
void dg::Polygonizer::getColor (Color & rkColor, Vector & rkPos, Vector & rkNormal) [inline]
Definition at line 160 of file Polygonizer.h.
Referenced by marchCube(), and marchTetra().
ColorList& dg::Polygonizer::getColors () [inline]
Definition at line 68 of file Polygonizer.h.
References m_kColorList.
Referenced by dg::Visualizer::drawPolygons().
Real dg::Polygonizer::getEpsilon () [inline]
Definition at line 204 of file Polygonizer.h.
Real dg::Polygonizer::getIntersect (Real fV1, Real fV2, Real fLevel) [inline]
Definition at line 149 of file Polygonizer.h.
Referenced by marchCube(), and marchTetra().
bool dg::Polygonizer::getInverseNormals () [inline]
Definition at line 123 of file Polygonizer.h.
Real dg::Polygonizer::getIsoLevel () [inline]
Definition at line 144 of file Polygonizer.h.
void Polygonizer::getNormal (Vector & rkNormal, Real fX, Real fY, Real fZ)
Definition at line 20 of file Polygonizer.cpp.
References m_fEpsilon, dg::Vector::normalize(), dg::Real, sample(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by marchCube(), and marchTetra().
VectorList& dg::Polygonizer::getNormals () [inline]
Definition at line 67 of file Polygonizer.h.
References m_kNormalList.
Referenced by dg::Visualizer::drawPolygons().
void dg::Polygonizer::getOffset (Real & fX, Real & fY, Real & fZ) [inline]
Definition at line 192 of file Polygonizer.h.
Real dg::Polygonizer::getScale () [inline]
Definition at line 214 of file Polygonizer.h.
VectorList& dg::Polygonizer::getVertices () [inline]
Definition at line 66 of file Polygonizer.h.
References m_kVertexList.
Referenced by dg::Visualizer::drawPolygons(), and dg::Visualizer::drawText().
void Polygonizer::marchCube (Real fX, Real fY, Real fZ, Real fScale)
Definition at line 34 of file Polygonizer.cpp.
References getColor(), getIntersect(), getNormal(), m_fIsoLevel, m_kColorList, m_kNormalList, m_kVertexList, m_pvFunction, dg::Real, sample(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by evaluate().
void Polygonizer::marchTetra (Vector * pakTetraPos, Real * pafTetraValue)
Definition at line 118 of file Polygonizer.cpp.
References getColor(), getIntersect(), getNormal(), m_fIsoLevel, m_kColorList, m_kNormalList, m_kVertexList, m_pvFunction, dg::Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by marchTetraCube().
void Polygonizer::marchTetraCube (Real fX, Real fY, Real fZ, Real fScale)
Definition at line 202 of file Polygonizer.cpp.
References m_pvFunction, marchTetra(), dg::Real, sample(), dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by evaluate().
Real dg::Polygonizer::sample (Real fX, Real fY, Real fZ) [inline]
Definition at line 219 of file Polygonizer.h.
Referenced by getNormal(), marchCube(), and marchTetraCube().
void dg::Polygonizer::setCellCount (Int iCellCount) [inline]
Definition at line 128 of file Polygonizer.h.
Referenced by dg::Visualizer::onKeyDown(), and dg::Visualizer::setupPolygonizer().
void dg::Polygonizer::setEpsilon (Real fEpsilon) [inline]
Definition at line 199 of file Polygonizer.h.
void dg::Polygonizer::setFunction (Function pvFunction) [inline]
Definition at line 113 of file Polygonizer.h.
Referenced by dg::Visualizer::setupPolygonizer().
void dg::Polygonizer::setInverseNormals (bool bInvNormals) [inline]
Definition at line 118 of file Polygonizer.h.
void dg::Polygonizer::setIsoLevel (Real fIsoLevel) [inline]
Definition at line 139 of file Polygonizer.h.
Referenced by dg::Visualizer::onSpecialKeyDown(), and dg::Visualizer::setupPolygonizer().
void dg::Polygonizer::setOffset (Real fX, Real fY, Real fZ) [inline]
Definition at line 185 of file Polygonizer.h.
Referenced by dg::Visualizer::onSpecialKeyDown(), and dg::Visualizer::setupPolygonizer().
void dg::Polygonizer::setScale (Real fScale) [inline]
Definition at line 209 of file Polygonizer.h.
Referenced by dg::Visualizer::onKeyDown(), and dg::Visualizer::setupPolygonizer().
Member Data Documentation
bool dg::Polygonizer::m_bInverseNormals [protected]
Definition at line 95 of file Polygonizer.h.
Real dg::Polygonizer::m_fDelta [protected]
Definition at line 100 of file Polygonizer.h.
Referenced by evaluate(), and Polygonizer().
Real dg::Polygonizer::m_fEpsilon [protected]
Definition at line 101 of file Polygonizer.h.
Referenced by getNormal(), and Polygonizer().
Real dg::Polygonizer::m_fIsoLevel [protected]
Definition at line 102 of file Polygonizer.h.
Referenced by marchCube(), marchTetra(), and Polygonizer().
Real dg::Polygonizer::m_fScale [protected]
Definition at line 99 of file Polygonizer.h.
Referenced by Polygonizer().
Int dg::Polygonizer::m_iCellCount [protected]
Definition at line 97 of file Polygonizer.h.
Referenced by evaluate(), and Polygonizer().
ColorList dg::Polygonizer::m_kColorList [protected]
Definition at line 108 of file Polygonizer.h.
Referenced by evaluate(), getColors(), marchCube(), and marchTetra().
VectorList dg::Polygonizer::m_kNormalList [protected]
Definition at line 107 of file Polygonizer.h.
Referenced by evaluate(), getNormals(), marchCube(), and marchTetra().
Vector dg::Polygonizer::m_kOffset [protected]
Definition at line 104 of file Polygonizer.h.
VectorList dg::Polygonizer::m_kVertexList [protected]
Definition at line 106 of file Polygonizer.h.
Referenced by evaluate(), getVertices(), marchCube(), and marchTetra().
Function dg::Polygonizer::m_pvFunction [protected]
Definition at line 93 of file Polygonizer.h.
Referenced by evaluate(), marchCube(), marchTetra(), marchTetraCube(), and Polygonizer().
The documentation for this class was generated from the following files:
Polygonizer.h
Polygonizer.cpp