dg Namespace Reference
Compounds
class Camera
class Color
class Hypertexture
class Image
struct Light
class Matrix
struct OperatorSpec
class Polygonizer
class RayTracer
class Set
class Timer
class Vector
Vector (p.) - Generic 3D mathematical Vector (p.) class.
class Visualizer
class Window
Typedefs
typedef bool Bool
typedef char Char
typedef unsigned char UChar
typedef signed short Short
typedef unsigned short UShort
typedef signed int Int
typedef unsigned int UInt
typedef signed long Long
typedef unsigned long ULong
typedef float Float
typedef double Double
typedef signed char Int8
typedef signed short Int16
typedef signed long Int32
typedef unsigned char UInt8
typedef unsigned short UInt16
typedef unsigned long UInt32
typedef float Real32
typedef double Real64
typedef float Real
typedef Real(* Operator)(Real fX, Real fY, Real fZ)
typedef Set< Light * > LightSet
Enumerations
enum ErrorType { ERROR_IGNORE,
ERROR_CONTINUE,
ERROR_ABORT
 }
Functions
Color operator * (Real fScalar, const Color &rkV)
Color Clamp (const Color &rkV, Real fMin, Real fMax)
bool IsNaN (Real fV)
bool IsInf (Real fV)
Real Validate (Real fV)
Real Torus (Real fX, Real fY, Real fZ)
Real Sphere (Real fX, Real fY, Real fZ)
Real Blob (Real fX, Real fY, Real fZ)
Real TriBlob (Real fX, Real fY, Real fZ)
Real Threads (Real fX, Real fY, Real fZ)
Real Cloth (Real fX, Real fY, Real fZ)
Real Quadric (Real fA, Real fB, Real fC)
Real SuperEllipsoid (Real fX, Real fY, Real fZ, Real fN1, Real fN2)
Real Heart (Real fX, Real fY, Real fZ)
Real KleinBottle (Real fX, Real fY, Real fZ)
Real TriConnect (Real fX, Real fY, Real fZ)
Real QuadConnect (Real fX, Real fY, Real fZ)
Real Ripples (Real fX, Real fY, Real fZ)
Real VoronoiBumps (Real fX, Real fY, Real fZ)
Real SphericalShell (Real fX, Real fY, Real fZ)
Real SphericalFalloff (Real fX, Real fY, Real fZ)
Real EggShell (Real fX, Real fY, Real fZ)
Real EggFalloff (Real fX, Real fY, Real fZ)
Real TurbulentSpace (Real fX, Real fY, Real fZ)
Real TurbulentSphere (Real fX, Real fY, Real fZ)
Real Erfc (Real fX)
Real LogGamma (Real fX)
Real Radians (Real fDeg)
Real Degrees (Real fRad)
Real Abs (Real fValue)
Real Ceil (Real fValue)
Real Clamp (Real fV, Real fMin, Real fMax)
Real Exp (Real fValue)
Real Floor (Real fValue)
Real InvSqrt (Real fValue)
Real Log (Real fValue)
Real Pow (Real fBase, Real fExponent)
Real Cub (Real fValue)
Real Square (Real fValue)
Real Sqr (Real fValue)
Real Sqrt (Real fValue)
Real Sign (Real fValue)
Real Gamma (Real fX)
Real Gaussian (Real fX, Real fStdDev)
Real Min (Real fX, Real fA)
Real Max (Real fX, Real fA)
Real Mod (Real fX, Real fA)
Real Frac (const Real fX)
Real Step (Real fX, Real fA)
Real Erf (Real fX)
Real ArcCosine (Real fValue)
Real ArcSine (Real fValue)
Real ArcTangent (Real fValue)
Real ArcTangent (Real fY, Real fX)
Real Cosine (Real fValue)
Real Sine (Real fValue)
Real Tangent (Real fValue)
Real CubicSpan (Real fX, const Real afC[4], const Real afM[4][4])
Real BicubicSpan (Real fU, Real fV, Real afBasis[4][4])
void MakeBicubicMatrix (Real afG[4][4], Real afM[4][4], Real afC[4][4])
void Info (const char *acMessage,...) PRINT_FUNC
void Notice (const char *acMessage,...) PRINT_FUNC
void Warning (const char *acMessage,...) PRINT_FUNC
void Error (const char *acMessage,...) PRINT_FUNC
void Severe (const char *acMessage,...) PRINT_FUNC
Real Spline (Real fX, UInt uiKnots, Real *apkKnots, const Real afB[4][4]=CatmullRomBasis)
Real CellNoise (Real fX, Real fY, Real fZ)
Real GradientNoise (Real fX, Real fY, Real fZ)
Real ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4]=CatmullRomBasis)
Real FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real Turbulence (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.25f, Real fLacunarity=2.0345f, Real fOffset=0.7f, Real fGain=1.0f, Real fOctaves=4.0f)
Real RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement=0.9f, Real fLacunarity=2.0345f, Real fThreshold=0.5f, Real fOffset=1.0f, Real fOctaves=4.0f)
Real FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real &rfOX, Real &rfOY, Real &rfOZ)
Real DefaultTurbulence (Real fX, Real fY, Real fZ)
Real DefaultFBM (Real fX, Real fY, Real fZ)
Real DefaultMonoFractal (Real fX, Real fY, Real fZ)
Real DefaultMultiFractal (Real fX, Real fY, Real fZ)
Real DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ)
Real fBm (Real fX, Real fY, Real fZ, Real fIncrement=0.5f, Real fLacunarity=2.0345f, Real fOctaves=4.0f)
Real r (Int iX)
Int p (Int iX)
Int Hash (Int iX, Int iY, Int iZ)
Real Lattice (Int iX, Int iY, Int iZ)
Real Gradient (Int iX, Int iY, Int iZ, Real fX, Real fY, Real fZ)
Real Bias (Real fX, Real fA)
Real Gain (Real fX, Real fA)
Real Cubic (Real fT)
Real Quintic (Real fT)
Real Lerp (Real fT, Real fA, Real fB)
Real BoxStep (Real fX, Real fA, Real fB)
Real SmoothStep (Real fA, Real fB, Real fX)
Real Pulse (Real fX, Real fA, Real fB)
Real BoxPulse (Real fX, Real fA, Real fB)
Real SmoothPulse (Real fX, Real fA, Real fB)
Real FilteredAbs (Real fX, Real fDX)
Real CatmullRomNoise (Real fX, Real fY, Real fZ)
Real HermiteNoise (Real fX, Real fY, Real fZ)
Real CardinalNoise (Real fX, Real fY, Real fZ)
Real BSplineNoise (Real fX, Real fY, Real fZ)
Real FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth)
void SeedRandom (ULong seed)
UInt RandomInt (void)
Real RandomUnitReal (void)
Real RandomUnitOpenReal (void)
Real RandomSymmetricReal (void)
Real RandomIntervalReal (Real fMin, Real fMax)
Color Ambient (const Color &rkLightColor)
Color Diffuse (const Vector &rkSurfaceNormal, const Vector &rkLightDir, const Color &rkLightColor)
Color Specular (const Vector &rkSurfaceNormal, const Vector &rkViewDir, const Vector &rkLightDir, const Color &rkLightColor, Real fRoughness)
Color Lambertian (const Vector &rkSurfaceNormal, const Vector &rkLightDir, const Color &rkLightColor, const Color &rkBaseColor, Real fAmbient=1.0, Real fDiffuse=0.8)
Color Phong (const Vector &rkSurfaceNormal, const Vector &rkViewDir, const Vector &rkLightDir, const Color &rkLightColor, const Color &rkBaseColor, Real fAmbient=1.0, Real fDiffuse=0.8, Real fSpecular=0.5, Real fRoughness=0.1)
Real RaySphere (Real fEX, Real fEY, Real fEZ, Real fIX, Real fIY, Real fIZ, Real fRadius, Real fEpsilon, Real &rfT0, Real &rfT1)
Real RaySphere (const Vector &rkPos, const Vector &rkRayDir, Real fRadius, Real fEpsilon, Real &rfT0, Real &rfT1)
Vector FaceForward (const Vector &rkN, const Vector &rkI)
Vector FaceForward (const Vector &rkN, const Vector &rkI, const Vector &rkRef)
Vector operator * (Real fScalar, const Vector &rkV)
Real Dot (const Vector &rkA, const Vector &rkB)
Vector Cross (const Vector &rkLHS, const Vector &rkRHS)
Vector Min (const Vector &rkA, const Vector &rkB)
Vector Max (const Vector &rkA, const Vector &rkB)
Vector Normalize (const Vector &rkV)
Vector Min (const Vector &rkV)
Vector Max (const Vector &rkV)
Color FilteredClownColorVolume (Real fX, Real fY, Real fZ, Real fStepSize)
Real ClownDensityVolume (Real fX, Real fY, Real fZ)
Real CloudDensityVolume (Real fX, Real fY, Real fZ)
Real CumulusDensityVolume (Real fX, Real fY, Real fZ)
Real CellCloudDensityVolume (Real fX, Real fY, Real fZ)
Real SphericalShellDensityVolume (Real fX, Real fY, Real fZ)
Real SphericalFalloffDensityVolume (Real fX, Real fY, Real fZ)
Real EggShellDensityVolume (Real fX, Real fY, Real fZ)
Real EggFalloffDensityVolume (Real fX, Real fY, Real fZ)
Real TurbulentSpaceDensityVolume (Real fX, Real fY, Real fZ)
Real TurbulentSphereDensityVolume (Real fX, Real fY, Real fZ)
Real ClothDensityVolume (Real fX, Real fY, Real fZ)
Real FilteredClownDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize=0.1)
Real FilteredCloudDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize=0.1)
Real FilteredCumulusDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize=0.1)
Typedef Documentation
typedef bool dg::Bool
Definition at line 36 of file DataTypes.h.
Referenced by dg::Window::onInitialize(), dg::Visualizer::onInitialize(), dg::Window::onStartup(), dg::Visualizer::onStartup(), dg::Color::operator!=(), and dg::Color::operator==().
typedef char dg::Char
Definition at line 37 of file DataTypes.h.
Referenced by dg::Window::drawString(), and dg::Visualizer::drawText().
typedef double dg::Double
Definition at line 46 of file DataTypes.h.
typedef float dg::Float
Definition at line 45 of file DataTypes.h.
typedef signed int dg::Int
Definition at line 41 of file DataTypes.h.
Referenced by dg::Window::drawFrameRate(), dg::Window::drawString(), dg::Visualizer::drawText(), dg::Polygonizer::evaluate(), GradientNoise(), dg::Matrix::inverse(), dg::Window::onKeyDown(), dg::Visualizer::onKeyDown(), dg::Window::onKeyUp(), dg::Window::onMouseClick(), dg::Visualizer::onMouseClick(), dg::Window::onMouseMotion(), dg::Visualizer::onMouseMotion(), dg::Window::onMove(), dg::Window::onPassiveMotion(), dg::Window::onReshape(), dg::Visualizer::onReshape(), dg::Window::onSpecialKeyDown(), dg::Visualizer::onSpecialKeyDown(), dg::Window::onSpecialKeyUp(), dg::Window::onUpdate(), dg::Color::operator *(), dg::Color::operator *=(), dg::Polygonizer::Polygonizer(), dg::Visualizer::setupFrustum(), Spline(), ValueNoise(), and dg::Window::Window().
typedef signed short dg::Int16
Definition at line 50 of file DataTypes.h.
typedef signed long dg::Int32
Definition at line 51 of file DataTypes.h.
typedef signed char dg::Int8
Definition at line 49 of file DataTypes.h.
typedef Set<Light*> dg::LightSet
Definition at line 21 of file Shading.h.
typedef signed long dg::Long
Definition at line 43 of file DataTypes.h.
typedef Real(* dg::Operator)(Real fX, Real fY, Real fZ)
Definition at line 14 of file Operators.h.
typedef float dg::Real
Definition at line 58 of file DataTypes.h.
Referenced by dg::Vector::angle(), BicubicSpan(), Blob(), dg::Image::blur(), dg::Matrix::buildRotation(), dg::Camera::Camera(), CellNoise(), Clamp(), Cloth(), dg::Color::Color(), CubicSpan(), Degrees(), Dot(), dg::Vector::dot(), dg::Window::drawFrameRate(), dg::Window::drawImage(), EggFalloff(), EggShell(), Erfc(), FilteredFBM(), FilteredTurbulence(), FractionalBrownianMotion(), dg::Matrix::fromAxisToAngle(), dg::Camera::getHorizontalFov(), dg::Polygonizer::getNormal(), dg::Camera::getVerticalFov(), GradientNoise(), Heart(), HybridMultiFractal(), dg::Image::Image(), dg::Matrix::inverse(), IsInf(), IsNaN(), KleinBottle(), Lambertian(), dg::Vector::length(), dg::Vector::lengthSquared(), LogGamma(), MakeBicubicMatrix(), dg::Polygonizer::marchCube(), dg::Polygonizer::marchTetra(), dg::Polygonizer::marchTetraCube(), dg::Matrix::Matrix(), Max(), Min(), MonoFractal(), MultiFractal(), Normalize(), dg::Vector::normalize(), dg::Vector::operator *(), dg::Matrix::operator *(), operator *(), dg::Color::operator *(), dg::Vector::operator *=(), dg::Color::operator *=(), dg::Matrix::operator Real **(), dg::Matrix::operator/(), Phong(), dg::Polygonizer::Polygonizer(), QuadConnect(), Quadric(), Radians(), RandomIntervalReal(), RandomSymmetricReal(), RaySphere(), dg::RayTracer::render(), dg::Hypertexture::render(), dg::Image::resize(), RidgedMultiFractal(), Ripples(), dg::Visualizer::setBackground(), dg::Camera::setHorizontalFov(), dg::Visualizer::setLights(), dg::Visualizer::setMaterials(), dg::Camera::setup(), dg::Visualizer::setupCamera(), dg::Visualizer::setupFrustum(), dg::Camera::setVerticalFov(), Specular(), Sphere(), SphericalFalloff(), SphericalShell(), Spline(), SuperEllipsoid(), Threads(), Torus(), TriBlob(), TriConnect(), Turbulence(), TurbulentSpace(), TurbulentSphere(), dg::Visualizer::update(), Validate(), ValueNoise(), dg::Vector::Vector(), VoronoiBumps(), VoronoiNoise(), and dg::Vector::x().
typedef float dg::Real32
Definition at line 56 of file DataTypes.h.
typedef double dg::Real64
Definition at line 57 of file DataTypes.h.
typedef signed short dg::Short
Definition at line 39 of file DataTypes.h.
typedef unsigned char dg::UChar
Definition at line 38 of file DataTypes.h.
Referenced by dg::Window::drawImage(), dg::Window::onKeyDown(), dg::Visualizer::onKeyDown(), and dg::Window::onKeyUp().
typedef unsigned int dg::UInt
Definition at line 42 of file DataTypes.h.
Referenced by dg::Image::blur(), dg::Matrix::buildRotation(), CellNoise(), dg::Visualizer::drawHypertexture(), dg::Window::drawImage(), dg::Visualizer::drawPolygons(), dg::Visualizer::drawRaytraced(), dg::Window::drawString(), dg::Visualizer::drawText(), FilteredFBM(), FilteredTurbulence(), FractionalBrownianMotion(), dg::Matrix::getColumn(), dg::Camera::getRayDir(), dg::Matrix::getRow(), dg::Matrix::getTranspose(), HybridMultiFractal(), dg::Image::Image(), dg::Matrix::inverse(), MakeBicubicMatrix(), MonoFractal(), MultiFractal(), dg::Visualizer::onKeyDown(), dg::Window::onMouseClick(), dg::Visualizer::onMouseClick(), dg::Window::onMouseMotion(), dg::Visualizer::onMouseMotion(), dg::Matrix::operator *(), dg::Matrix::operator *=(), dg::Matrix::operator+(), dg::Matrix::operator+=(), dg::Matrix::operator-(), dg::Matrix::operator-=(), dg::Matrix::operator/(), RandomInt(), dg::RayTracer::render(), dg::Hypertexture::render(), dg::Image::resize(), RidgedMultiFractal(), dg::Visualizer::setupRayTracer(), Spline(), dg::Matrix::transpose(), and Turbulence().
typedef unsigned short dg::UInt16
Definition at line 53 of file DataTypes.h.
typedef unsigned long dg::UInt32
Definition at line 54 of file DataTypes.h.
typedef unsigned char dg::UInt8
Definition at line 52 of file DataTypes.h.
typedef unsigned long dg::ULong
Definition at line 44 of file DataTypes.h.
Referenced by SeedRandom().
typedef unsigned short dg::UShort
Definition at line 40 of file DataTypes.h.
Enumeration Type Documentation
enum dg::ErrorType
Enumeration values:
ERROR_IGNORE
ERROR_CONTINUE
ERROR_ABORT
Definition at line 40 of file Messages.h.
Function Documentation
Real dg::Abs (Real fValue) [inline]
Definition at line 127 of file Maths.h.
Referenced by dg::Matrix::buildRotation(), Erfc(), dg::Matrix::inverse(), RidgedMultiFractal(), Threads(), and Turbulence().
Color Ambient (const Color & rkLightColor) [inline]
Definition at line 26 of file Shading.h.
Referenced by Lambertian(), and Phong().
Real dg::ArcCosine (Real fValue) [inline]
Definition at line 237 of file Maths.h.
Referenced by dg::Matrix::buildRotation().
Real dg::ArcSine (Real fValue) [inline]
Definition at line 252 of file Maths.h.
Real dg::ArcTangent (Real fY, Real fX) [inline]
Definition at line 272 of file Maths.h.
Real dg::ArcTangent (Real fValue) [inline]
Definition at line 267 of file Maths.h.
Referenced by dg::Camera::getHorizontalFov(), and dg::Camera::getVerticalFov().
Real dg::Bias (Real fX, Real fA) [inline]
Definition at line 193 of file Procedural.h.
Referenced by Threads().
Real dg::BicubicSpan (Real fU, Real fV, Real afBasis[4][4])
Definition at line 78 of file Maths.cpp.
References Real.
Real dg::Blob (Real fX, Real fY, Real fZ)
Definition at line 28 of file Implicits.cpp.
References Exp(), Real, and Sqr().
Real dg::BoxPulse (Real fX, Real fA, Real fB) [inline]
Definition at line 269 of file Procedural.h.
Real dg::BoxStep (Real fX, Real fA, Real fB) [inline]
Definition at line 243 of file Procedural.h.
Real dg::BSplineNoise (Real fX, Real fY, Real fZ) [inline]
Definition at line 294 of file Procedural.h.
Real dg::CardinalNoise (Real fX, Real fY, Real fZ) [inline]
Definition at line 289 of file Procedural.h.
Real dg::CatmullRomNoise (Real fX, Real fY, Real fZ) [inline]
Definition at line 279 of file Procedural.h.
Real dg::Ceil (Real fValue) [inline]
Definition at line 132 of file Maths.h.
Real dg::CellCloudDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 84 of file Volumes.h.
Real dg::CellNoise (Real fX, Real fY, Real fZ)
Definition at line 52 of file Procedural.cpp.
References Floor(), Hash(), r(), Real, and UInt.
Referenced by VoronoiNoise().
Real dg::Clamp (Real fV, Real fMin, Real fMax) [inline]
Definition at line 137 of file Maths.h.
Color dg::Clamp (const Color & rkV, Real fMin, Real fMax)
Definition at line 191 of file Color.cpp.
References dg::Color::b(), dg::Color::g(), dg::Color::r(), and Real.
Referenced by RidgedMultiFractal(), Spline(), and TriConnect().
Real dg::Cloth (Real fX, Real fY, Real fZ)
Definition at line 241 of file Implicits.cpp.
References Real, and Threads().
Real dg::ClothDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 126 of file Volumes.h.
Real dg::CloudDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 38 of file Volumes.h.
Real dg::ClownDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 33 of file Volumes.h.
Real dg::Cosine (Real fValue) [inline]
Definition at line 277 of file Maths.h.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::fromAxisToAngle(), Ripples(), and Threads().
Vector dg::Cross (const Vector & rkLHS, const Vector & rkRHS)
Definition at line 228 of file Vector.cpp.
References dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Real dg::Cub (Real fValue) [inline]
Definition at line 167 of file Maths.h.
Referenced by Heart().
Real dg::Cubic (Real fT) [inline]
Definition at line 223 of file Procedural.h.
Referenced by GradientNoise().
Real dg::CubicSpan (Real fX, const Real afC[4], const Real afM[4][4])
Definition at line 61 of file Maths.cpp.
References Real.
Referenced by Spline().
Real dg::CumulusDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 43 of file Volumes.h.
Real dg::DefaultFBM (Real fX, Real fY, Real fZ) [inline]
Definition at line 327 of file Procedural.h.
Real dg::DefaultMonoFractal (Real fX, Real fY, Real fZ) [inline]
Definition at line 333 of file Procedural.h.
Real dg::DefaultMultiFractal (Real fX, Real fY, Real fZ) [inline]
Definition at line 339 of file Procedural.h.
Real dg::DefaultRidgedMultiFractal (Real fX, Real fY, Real fZ) [inline]
Definition at line 345 of file Procedural.h.
Real dg::DefaultTurbulence (Real fX, Real fY, Real fZ) [inline]
Definition at line 321 of file Procedural.h.
Referenced by TurbulentSpace().
Real Degrees (Real fRad) [inline]
Definition at line 28 of file Maths.h.
References Real.
Referenced by dg::Camera::getHorizontalFov(), and dg::Camera::getVerticalFov().
Color Diffuse (const Vector & rkSurfaceNormal, const Vector & rkLightDir, const Color & rkLightColor) [inline]
Definition at line 32 of file Shading.h.
References Dot(), and Max().
Referenced by Lambertian(), and Phong().
Real dg::Dot (const Vector & rkA, const Vector & rkB)
Definition at line 219 of file Vector.cpp.
References Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by Diffuse(), RaySphere(), and Specular().
Real dg::EggFalloff (Real fX, Real fY, Real fZ)
Definition at line 177 of file Implicits.cpp.
References Real.
Real dg::EggFalloffDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 111 of file Volumes.h.
Real dg::EggShell (Real fX, Real fY, Real fZ)
Definition at line 155 of file Implicits.cpp.
References Real.
Real dg::EggShellDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 106 of file Volumes.h.
Real dg::Erf (Real fX) [inline]
Definition at line 232 of file Maths.h.
Real dg::Erfc (Real fX)
Definition at line 33 of file Maths.cpp.
References Abs(), Exp(), and Real.
void dg::Error (const char * acMessage, ...) [inline]
Definition at line 96 of file Messages.cpp.
References ERROR_CONTINUE.
Real dg::Exp (Real fValue) [inline]
Definition at line 142 of file Maths.h.
Referenced by Blob(), and Erfc().
Vector dg::FaceForward (const Vector & rkN, const Vector & rkI, const Vector & rkRef) [inline]
Definition at line 115 of file Shading.h.
Vector dg::FaceForward (const Vector & rkN, const Vector & rkI) [inline]
Definition at line 107 of file Shading.h.
Real dg::fBm (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f) [inline]
Definition at line 351 of file Procedural.h.
Real dg::FilteredAbs (Real fX, Real fDX) [inline]
Definition at line 299 of file Procedural.h.
Referenced by FilteredTurbulence().
Real dg::FilteredCloudDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize = 0.1) [inline]
Definition at line 66 of file Volumes.h.
Color dg::FilteredClownColorVolume (Real fX, Real fY, Real fZ, Real fStepSize) [inline]
Definition at line 48 of file Volumes.h.
Referenced by dg::Visualizer::setupHypertexture().
Real dg::FilteredClownDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize = 0.1) [inline]
Definition at line 57 of file Volumes.h.
Real dg::FilteredCumulusDensityVolume (Real fX, Real fY, Real fZ, Real fStepSize = 0.1) [inline]
Definition at line 75 of file Volumes.h.
Real dg::FilteredFBM (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 185 of file Procedural.cpp.
References FilteredGradientNoise(), Real, and UInt.
Real dg::FilteredGradientNoise (Real fX, Real fY, Real fZ, Real fFilterWidth) [inline]
Definition at line 314 of file Procedural.h.
Referenced by FilteredFBM(), and FilteredTurbulence().
Real dg::FilteredTurbulence (Real fX, Real fY, Real fZ, Real fFilterWidth, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 291 of file Procedural.cpp.
References FilteredAbs(), FilteredGradientNoise(), Real, and UInt.
Real dg::Floor (Real fValue) [inline]
Definition at line 147 of file Maths.h.
Referenced by CellNoise(), GradientNoise(), and VoronoiNoise().
Real dg::Frac (const Real fX) [inline]
Definition at line 227 of file Maths.h.
Real dg::FractionalBrownianMotion (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 141 of file Procedural.cpp.
References GradientNoise(), Real, and UInt.
Real dg::Gain (Real fX, Real fA) [inline]
Definition at line 202 of file Procedural.h.
Referenced by Threads().
Real dg::Gamma (Real fX) [inline]
Definition at line 197 of file Maths.h.
Real dg::Gaussian (Real fX, Real fStdDev) [inline]
Definition at line 202 of file Maths.h.
Real dg::Gradient (Int iX, Int iY, Int iZ, Real fX, Real fY, Real fZ) [inline]
Definition at line 173 of file Procedural.h.
Referenced by GradientNoise().
Real dg::GradientNoise (Real fX, Real fY, Real fZ)
Definition at line 61 of file Procedural.cpp.
References Cubic(), Floor(), Gradient(), Int, Lerp(), and Real.
Referenced by FractionalBrownianMotion(), HybridMultiFractal(), MonoFractal(), MultiFractal(), RidgedMultiFractal(), and Turbulence().
Int dg::Hash (Int iX, Int iY, Int iZ) [inline]
Definition at line 163 of file Procedural.h.
Referenced by CellNoise().
Real dg::Heart (Real fX, Real fY, Real fZ)
Definition at line 44 of file Implicits.cpp.
References Cub(), Real, and Sqr().
Real dg::HermiteNoise (Real fX, Real fY, Real fZ) [inline]
Definition at line 284 of file Procedural.h.
Real dg::HybridMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.25f, Real fLacunarity = 2.0345f, Real fOffset = 0.7f, Real fGain = 1.0f, Real fOctaves = 4.0f)
Definition at line 448 of file Procedural.cpp.
References GradientNoise(), Real, and UInt.
void dg::Info (const char * acMessage, ...) [inline]
Definition at line 72 of file Messages.cpp.
References ERROR_CONTINUE.
Real dg::InvSqrt (Real fValue) [inline]
Definition at line 152 of file Maths.h.
bool IsInf (Real fV) [inline]
Definition at line 77 of file DataTypes.h.
References Real.
Referenced by Validate().
bool IsNaN (Real fV) [inline]
Definition at line 72 of file DataTypes.h.
References Real.
Referenced by Validate().
Real dg::KleinBottle (Real fX, Real fY, Real fZ)
Definition at line 51 of file Implicits.cpp.
References Real, and Sqr().
Color Lambertian (const Vector & rkSurfaceNormal, const Vector & rkLightDir, const Color & rkLightColor, const Color & rkBaseColor, Real fAmbient = 1.0, Real fDiffuse = 0.8) [inline]
Definition at line 54 of file Shading.h.
References Ambient(), Diffuse(), and Real.
Real dg::Lattice (Int iX, Int iY, Int iZ) [inline]
Definition at line 168 of file Procedural.h.
Referenced by ValueNoise().
Real dg::Lerp (Real fT, Real fA, Real fB) [inline]
Definition at line 233 of file Procedural.h.
Referenced by GradientNoise().
Real dg::Log (Real fValue) [inline]
Definition at line 157 of file Maths.h.
Referenced by LogGamma().
Real dg::LogGamma (Real fX)
Definition at line 8 of file Maths.cpp.
References Log(), and Real.
void dg::MakeBicubicMatrix (Real afG[4][4], Real afM[4][4], Real afC[4][4])
Definition at line 89 of file Maths.cpp.
References Real, and UInt.
Vector Max (const Vector & rkV)
Vector dg::Max (const Vector & rkA, const Vector & rkB)
Definition at line 246 of file Vector.cpp.
References Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Real dg::Max (Real fX, Real fA) [inline]
Definition at line 222 of file Maths.h.
Referenced by Diffuse(), Specular(), and TurbulentSpace().
Vector Min (const Vector & rkV)
Vector dg::Min (const Vector & rkA, const Vector & rkB)
Definition at line 237 of file Vector.cpp.
References Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Real dg::Min (Real fX, Real fA) [inline]
Definition at line 217 of file Maths.h.
Referenced by TurbulentSpace().
Real dg::Mod (Real fX, Real fA) [inline]
Definition at line 207 of file Maths.h.
Real dg::MonoFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 350 of file Procedural.cpp.
References GradientNoise(), Real, and UInt.
Real dg::MultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 400 of file Procedural.cpp.
References GradientNoise(), Real, and UInt.
Vector dg::Normalize (const Vector & rkV)
Definition at line 255 of file Vector.cpp.
References dg::Vector::lengthSquared(), Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Referenced by Phong(), dg::RayTracer::render(), dg::Hypertexture::render(), and Specular().
void dg::Notice (const char * acMessage, ...) [inline]
Definition at line 80 of file Messages.cpp.
References ERROR_CONTINUE.
Vector dg::operator * (Real fScalar, const Vector & rkV)
Definition at line 271 of file Vector.cpp.
References Real, dg::Vector::x(), dg::Vector::y(), and dg::Vector::z().
Color dg::operator * (Real fScalar, const Color & rkV)
Definition at line 184 of file Color.cpp.
References dg::Color::b(), dg::Color::g(), dg::Color::r(), and Real.
Int dg::p (Int iX) [inline]
Definition at line 158 of file Procedural.h.
Color Phong (const Vector & rkSurfaceNormal, const Vector & rkViewDir, const Vector & rkLightDir, const Color & rkLightColor, const Color & rkBaseColor, Real fAmbient = 1.0, Real fDiffuse = 0.8, Real fSpecular = 0.5, Real fRoughness = 0.1) [inline]
Definition at line 66 of file Shading.h.
References Ambient(), Diffuse(), Normalize(), Real, and Specular().
Real dg::Pow (Real fBase, Real fExponent) [inline]
Definition at line 162 of file Maths.h.
Referenced by Specular(), and SuperEllipsoid().
Real dg::Pulse (Real fX, Real fA, Real fB) [inline]
Definition at line 264 of file Procedural.h.
Real dg::QuadConnect (Real fX, Real fY, Real fZ)
Definition at line 71 of file Implicits.cpp.
References Real.
Real dg::Quadric (Real fA, Real fB, Real fC)
Definition at line 588 of file Procedural.cpp.
References Real.
Real dg::Quintic (Real fT) [inline]
Definition at line 228 of file Procedural.h.
Real dg::r (Int iX) [inline]
Definition at line 153 of file Procedural.h.
Referenced by CellNoise().
Real Radians (Real fDeg) [inline]
Definition at line 27 of file Maths.h.
References Real.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::fromAxisToAngle(), dg::Camera::setHorizontalFov(), and dg::Camera::setVerticalFov().
UInt dg::RandomInt (void)
Definition at line 64 of file Random.cpp.
References LOWER_MASK, M, MATRIX_A, N, SeedRandom(), UInt, and UPPER_MASK.
Referenced by dg::Visualizer::onKeyDown(), RandomUnitOpenReal(), and RandomUnitReal().
Real RandomIntervalReal (Real fMin, Real fMax) [inline]
Definition at line 82 of file Random.h.
References RandomUnitReal(), and Real.
Real RandomSymmetricReal (void) [inline]
Definition at line 76 of file Random.h.
References RandomUnitReal(), and Real.
float dg::RandomUnitOpenReal (void)
Definition at line 113 of file Random.cpp.
References RandomInt().
float dg::RandomUnitReal (void)
Definition at line 106 of file Random.cpp.
References RandomInt().
Referenced by RandomIntervalReal(), and RandomSymmetricReal().
Real dg::RaySphere (const Vector & rkPos, const Vector & rkRayDir, Real fRadius, Real fEpsilon, Real & rfT0, Real & rfT1)
Definition at line 7 of file Shading.cpp.
References Dot(), and Real.
Real dg::RaySphere (Real fEX, Real fEY, Real fEZ, Real fIX, Real fIY, Real fIZ, Real fRadius, Real fEpsilon, Real & rfT0, Real & rfT1)
Definition at line 51 of file Shading.cpp.
References Real.
Real dg::RidgedMultiFractal (Real fX, Real fY, Real fZ, Real fIncrement = 0.9f, Real fLacunarity = 2.0345f, Real fThreshold = 0.5f, Real fOffset = 1.0f, Real fOctaves = 4.0f)
Definition at line 518 of file Procedural.cpp.
References Abs(), Clamp(), GradientNoise(), Real, and UInt.
Real dg::Ripples (Real fX, Real fY, Real fZ)
Definition at line 94 of file Implicits.cpp.
References Cosine(), Real, Sine(), and Sqrt().
void dg::SeedRandom (ULong seed)
Definition at line 46 of file Random.cpp.
References N, and ULong.
Referenced by RandomInt().
void dg::Severe (const char * acMessage, ...) [inline]
Definition at line 104 of file Messages.cpp.
References ERROR_ABORT.
Real dg::Sign (Real fValue) [inline]
Definition at line 187 of file Maths.h.
Real dg::Sine (Real fValue) [inline]
Definition at line 282 of file Maths.h.
Referenced by dg::Matrix::buildRotation(), dg::Matrix::fromAxisToAngle(), Ripples(), and dg::Visualizer::update().
Real dg::SmoothPulse (Real fX, Real fA, Real fB) [inline]
Definition at line 274 of file Procedural.h.
Real dg::SmoothStep (Real fA, Real fB, Real fX) [inline]
Definition at line 248 of file Procedural.h.
Color Specular (const Vector & rkSurfaceNormal, const Vector & rkViewDir, const Vector & rkLightDir, const Color & rkLightColor, Real fRoughness) [inline]
Definition at line 41 of file Shading.h.
References Dot(), Max(), Normalize(), Pow(), and Real.
Referenced by Phong().
Real dg::Sphere (Real fX, Real fY, Real fZ)
Definition at line 21 of file Implicits.cpp.
References Real, and Validate().
Referenced by TriBlob(), and TriConnect().
Real dg::SphericalFalloff (Real fX, Real fY, Real fZ)
Definition at line 136 of file Implicits.cpp.
References Real.
Referenced by TurbulentSphere().
Real dg::SphericalFalloffDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 101 of file Volumes.h.
Real dg::SphericalShell (Real fX, Real fY, Real fZ)
Definition at line 117 of file Implicits.cpp.
References Real.
Real dg::SphericalShellDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 96 of file Volumes.h.
Real dg::Spline (Real fX, UInt uiKnots, Real * apkKnots, const Real afB[4][4] = CatmullRomBasis)
Definition at line 30 of file Procedural.cpp.
References Clamp(), CubicSpan(), Int, Real, and UInt.
Referenced by ValueNoise().
Real dg::Sqr (Real fValue) [inline]
Definition at line 177 of file Maths.h.
Referenced by Blob(), dg::Matrix::fromAxisToAngle(), Heart(), and KleinBottle().
Real dg::Sqrt (Real fValue) [inline]
Definition at line 182 of file Maths.h.
Referenced by Ripples().
Real dg::Square (Real fValue) [inline]
Definition at line 172 of file Maths.h.
Real dg::Step (Real fX, Real fA) [inline]
Definition at line 238 of file Procedural.h.
Real dg::SuperEllipsoid (Real fX, Real fY, Real fZ, Real fN1, Real fN2)
Definition at line 246 of file Implicits.cpp.
References Pow(), and Real.
Real dg::Tangent (Real fValue) [inline]
Definition at line 287 of file Maths.h.
Referenced by dg::Camera::setHorizontalFov(), and dg::Camera::setVerticalFov().
Real dg::Threads (Real fX, Real fY, Real fZ)
Definition at line 219 of file Implicits.cpp.
References Abs(), Bias(), Cosine(), Gain(), and Real.
Referenced by Cloth().
Real dg::Torus (Real fX, Real fY, Real fZ)
Definition at line 11 of file Implicits.cpp.
References Real, and Validate().
Real dg::TriBlob (Real fX, Real fY, Real fZ)
Definition at line 36 of file Implicits.cpp.
References Real, Sphere(), and Validate().
Real dg::TriConnect (Real fX, Real fY, Real fZ)
Definition at line 61 of file Implicits.cpp.
References Clamp(), Real, and Sphere().
Real dg::Turbulence (Real fX, Real fY, Real fZ, Real fIncrement = 0.5f, Real fLacunarity = 2.0345f, Real fOctaves = 4.0f)
Definition at line 234 of file Procedural.cpp.
References Abs(), GradientNoise(), Real, and UInt.
Real dg::TurbulentSpace (Real fX, Real fY, Real fZ)
Definition at line 200 of file Implicits.cpp.
References DefaultTurbulence(), Max(), Min(), and Real.
Referenced by TurbulentSphere().
Real dg::TurbulentSpaceDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 116 of file Volumes.h.
Real dg::TurbulentSphere (Real fX, Real fY, Real fZ)
Definition at line 209 of file Implicits.cpp.
References Real, SphericalFalloff(), and TurbulentSpace().
Real dg::TurbulentSphereDensityVolume (Real fX, Real fY, Real fZ) [inline]
Definition at line 121 of file Volumes.h.
Real Validate (Real fV) [inline]
Definition at line 82 of file DataTypes.h.
References IsInf(), IsNaN(), and Real.
Referenced by Sphere(), Torus(), and TriBlob().
Real dg::ValueNoise (Real fX, Real fY, Real fZ, const Real afB[4][4] = CatmullRomBasis)
Definition at line 110 of file Procedural.cpp.
References Int, Lattice(), Real, and Spline().
Real dg::VoronoiBumps (Real fX, Real fY, Real fZ)
Definition at line 107 of file Implicits.cpp.
References Real, and VoronoiNoise().
Real dg::VoronoiNoise (Real fX, Real fY, Real fZ, Real fJitter, Real & rfOX, Real & rfOY, Real & rfOZ)
Definition at line 614 of file Procedural.cpp.
References CellNoise(), Floor(), and Real.
Referenced by VoronoiBumps().
void dg::Warning (const char * acMessage, ...) [inline]
Definition at line 88 of file Messages.cpp.
References ERROR_CONTINUE.